import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const target = resolve(packageRoot, "src/skills-content.generated.ts");
const definitions = [
  {
    exportName: "CAPTURE_SKILL_MD",
    source: resolve(packageRoot, "skills/capture/SKILL.md"),
  },
  {
    exportName: "RECALL_SKILL_MD",
    source: resolve(packageRoot, "skills/recall/SKILL.md"),
  },
];

function normalizeLf(value) {
  return value.replace(/\r\n?/g, "\n");
}

const entries = await Promise.all(
  definitions.map(async ({ exportName, source }) => ({
    exportName,
    content: normalizeLf(await readFile(source, "utf8")),
  })),
);

const output = [
  "// AUTO-GENERATED by scripts/generate-skills.mjs.",
  "// Edit skills/*/SKILL.md, then run `npm run generate:skills`.",
  "",
  ...entries.map(
    ({ exportName, content }) =>
      `export const ${exportName} = ${JSON.stringify(content)};`,
  ),
  "",
].join("\n");

if (process.argv.includes("--check")) {
  let current;
  try {
    current = normalizeLf(await readFile(target, "utf8"));
  } catch {
    current = null;
  }

  if (current !== output) {
    console.error(
      "Generated skill bundle is stale. Run `npm run generate:skills` and commit the result.",
    );
    process.exitCode = 1;
  } else {
    console.log("Generated skill bundle is in sync.");
  }
} else {
  await writeFile(target, output, "utf8");
}
