import { supportEmailHref, type Brand } from '../ui.ts';
import { PUBLIC_ORIGIN } from '../config.ts';
/** Static same-origin management console. All server data is rendered as text. */
export function renderManagement(brand: Brand, origin = PUBLIC_ORIGIN): string {
    const escape = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
    const replacements: Record<string, string> = {
        '<title>Memory': '<title>' + escape(brand.name),
        'MEMORY / MANAGED STANDARD': escape(brand.shortName) + ' / MANAGED STANDARD',
        '기억과 접근 권한 관리</h1>': escape(brand.name) + ' · 기억과 접근 권한 관리</h1>',
        'Release candidate · 실환경': '<a href="' + escape(supportEmailHref(brand.supportEmail)) + '">문의</a> · Release candidate · 실환경',
        'https://memory.allenlabs.org/mcp': escape(new URL('/mcp', origin).href),
    };
    return managementHtml.replace(/<title>Memory|MEMORY \/ MANAGED STANDARD|기억과 접근 권한 관리<\/h1>|Release candidate · 실환경|https:\/\/memory\.allenlabs\.org\/mcp/g,
        marker => replacements[marker]!);
}
export const managementHtml = String.raw `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Memory · 서비스 관리</title><link rel="stylesheet" href="/assets/release.css"><script defer src="/assets/release.js"></script></head><body>
<header><div><small>MEMORY / MANAGED STANDARD</small><h1>기억과 접근 권한 관리</h1></div><nav><a href="/">기존 조직 콘솔</a><a href="/auth/login">로그인</a><button id="reload">새로고침</button><button id="logout">로그아웃</button></nav></header>
<main><p class="notice">Standard 모드에서는 서비스가 메모리 본문을 읽을 수 있습니다. 원문 추출은 임시 암호화 저장 후 검토하며, 이 서비스는 Zero-Access 모드가 아닙니다.</p><p id="status" role="status">로그인 상태를 확인합니다.</p><p id="feature-status" role="status"></p><div id="reauth-actions" hidden><a href="/auth/login" target="_blank" rel="noopener noreferrer">새 탭에서 같은 계정으로 로그인</a><button id="resume-session">로그인 후 다시 연결</button><p>초안은 이 창에만 남습니다. 닫거나 새로고침하지 말고 필요하면 복사하세요.</p></div><details id="recovery-drafts" hidden><summary>보존된 공간별 초안 복사</summary><pre id="recovery-text"></pre></details>
<section class="toolbar"><label>메모리 저장소(Space)<select id="space"></select></label><label>도메인·SCIM 관리 조직<select id="organization"><option value="">개인</option></select></label><button id="usage">공동 사용량</button><button id="refresh-memories">기억 목록</button><button id="trash">휴지통</button><p id="space-permission" role="status"></p></section>
<div class="grid"><section><h2>기억 저장·검색</h2><form id="add-form"><label>기억 본문<textarea name="body" rows="5" required maxlength="16384"></textarea></label><label>원문 또는 출처<input name="source" maxlength="2048"></label><label>대체할 기존 기억 ID (선택)<input name="supersedesMemoryId"></label><button>저장</button><small>본문은 UTF-8 16,384바이트, 출처는 2,048바이트까지 입력할 수 있습니다. 응답이 유실되면 같은 내용으로 다시 제출하세요. 현재 페이지에서 작업 키를 유지합니다.</small></form><form id="search-form"><label>검색어<input name="query" required aria-describedby="search-limits"></label><button>검색</button><small id="search-limits">검색어 전체는 UTF-8 1,024바이트, 단어별 접두어는 31자까지 지원합니다.</small></form><div id="memories"></div><button id="more" hidden>다음 페이지</button></section>
<section><h2>최근 본인 확인</h2><p>PAT 발급·이메일 변경·영구 제거·결제 관리에는 5분 이내 확인이 필요합니다.</p><form id="reauth-start"><label>기존 확인된 이메일<select name="emailId" id="email-select"></select></label><button>확인 코드 발송</button></form><form id="reauth-complete"><label>Challenge ID<input name="challengeId" id="reauth-id" required></label><label>이메일의 Proof<input name="proof" autocomplete="off" required></label><button>본인 확인</button></form>
<details><summary>이메일 연결·회수</summary><form id="email-start"><label>추가 이메일<input type="email" name="email" required></label><button>확인 메일 발송</button></form><form id="email-complete"><label>Challenge ID<input name="challengeId" id="email-challenge" required></label><label>Proof<input name="proof" autocomplete="off" required></label><button>이메일 연결</button></form><form id="email-unlink"><label>회수할 이메일 ID<input name="emailId" required></label><button>연결 해제 및 종속 권한 회수</button></form></details>
<details><summary>PAT (개인 액세스 토큰)</summary><form id="key-form"><label>PAT 이름<input name="label" required></label><fieldset><legend>허용 동작</legend><label><input type="checkbox" name="cap" value="read" checked>조회</label><label><input type="checkbox" name="cap" value="create">추가</label><label><input type="checkbox" name="cap" value="update">수정</label><label><input type="checkbox" name="cap" value="delete">삭제</label><label><input type="checkbox" name="cap" value="export">내보내기</label></fieldset><label><input type="checkbox" name="singleSpace" checked>현재 메모리 저장소만 허용 (기본)</label><p id="pat-scope" aria-live="polite"></p><small>해제하면 조직 범위는 해당 조직의 모든 저장소를, 개인 범위는 소유한 저장소와 수락한 공유 저장소(다른 조직 소유 포함)를 포함합니다. 선택한 동작만 허용하며, 공유 저장소는 조회 동작만 지원합니다. 쓰기 동작은 현재 쓰기 권한이 있는 저장소에서만 허용됩니다. 다른 조직이나 하위 조직으로 권한이 확대되지는 않습니다.</small><label>유효기간(일)<input type="number" name="expiresInDays" value="30" min="1" max="90" required></label><button>PAT 발급</button></form><form id="key-revoke"><label>회수할 PAT ID<input name="keyId" required></label><button>PAT 회수</button></form></details>
<details><summary>삭제·보존·내보내기</summary><form id="retention-form"><label>휴지통 복원 가능 일수<input name="days" type="number" min="1" max="3650" value="30" required></label><button>복원 기간 저장</button></form><p id="retention-status"></p><p>영구 제거는 현재 DB의 본문·이력을 제거합니다. 검색 인덱스 정리와 백업 만료는 별도 수명주기를 따릅니다.</p><button id="export">JSON 내보내기</button><button id="rebuild">검색 인덱스 재생성</button><button id="jobs">작업 상태 조회</button><form id="job-retry"><label>실패 작업 ID<input name="jobId" required></label><button>재시도</button></form></details>
</section></div>
<div class="grid"><section><h2>대화에서 추출</h2><form id="ingest-form"><label>대화 JSON 배열<textarea name="messages" rows="6" required placeholder='[{"id":"m1","role":"user","content":"기억할 사실"}]'></textarea></label><button>추출 제안 만들기</button></form><button id="ingests">추출 작업 새로고침</button><div id="proposals"></div><p>추출 모델이 만든 내용은 사실 확정이 아닙니다. 원문 인용을 확인하고 저장할 항목만 승인하세요.</p>
<details><summary>승인 기반 읽기 공유</summary><form id="share-form"><label>이미 가입·확인된 수신 이메일<input type="email" name="email" required></label><label>유효 일수<input type="number" name="days" min="1" max="30" value="7"></label><button>공유 제안</button><small>응답을 확인할 수 없으면 다시 제안하기 전에 아래 보낸 공유 목록을 확인하세요.</small></form><section aria-labelledby="outbound-shares-title"><h3 id="outbound-shares-title">보낸 공유</h3><p>현재 Space에서 제안한 공유를 최근 생성 순으로 조회합니다. 회수·만료된 기록도 포함합니다. 표시 시각은 저장된 기록이며, 실제 접근에는 현재 계정·이메일·조직·Space 권한이 적용됩니다. 회수에는 최근 본인 확인이 필요합니다.</p><button id="outbound-shares-refresh">보낸 공유 새로고침</button><div id="outbound-shares" aria-live="polite"></div><p id="outbound-shares-status" role="status"></p><button id="outbound-shares-more" hidden>보낸 공유 더 불러오기</button></section><button id="invitations">받은 공유 제안</button><div id="shares"></div><button id="shares-more" hidden>공유 제안 더 불러오기</button><form id="share-revoke"><label>공유 ID<input name="shareId" required></label><button>공유 회수</button></form></details></section>
<section><h2>도메인·조직 관리</h2><form id="domain-start"><label>관리할 정확한 도메인<input name="domain" placeholder="example.com" required></label><button>DNS TXT 확인값 만들기</button></form><form id="domain-verify"><label>Domain challenge ID<input name="challengeId" required></label><button>DNS 소유권 확인</button></form><form id="domain-delegate"><label>Domain ID<input name="domainId" required></label><label>위임할 멤버십 ID<input name="membershipId" required></label><button>도메인 관리자 위임</button></form><form id="domain-revoke"><label>Domain ID<input name="domainId" required></label><label>회수할 이메일<input type="email" name="email" required></label><button>해당 주소의 서비스 접근 회수</button></form><p>도메인 검증은 30일 동안 유효합니다. 상위 조직의 권한은 하위 조직에 자동 상속되지 않습니다.</p><details><summary>SCIM 회수 연동</summary><button id="scim-key">조직 SCIM 키 발급</button><p>현재는 목록·비활성화 전용입니다. 사용자 생성·수정 전체를 지원하는 SCIM 구현은 아닙니다.</p></details>
<details><summary>결제</summary><form id="checkout-form"><label>상품<select name="priceId" id="prices"></select></label><button>구독 결제</button></form><button id="checkout-new-attempt" hidden>만료된 결제 요청 대신 새 시도 준비</button><button id="portal">구독·결제 관리</button><p>사용량은 조직 공동으로 합산됩니다. 제공자 토큰 사용량과 다른 서비스 단위이며 매월 UTC 기준으로 초기화됩니다.</p></details></section></div>
<section id="mcp-connection"><h2>MCP 연결</h2><p>엔드포인트: <code>https://memory.allenlabs.org/mcp</code></p><p>PAT 방식: 클라이언트의 비밀 환경 변수(예: <code>MEMORY_SAAS_PAT</code>)에서 토큰을 읽어 <code>Authorization: Bearer &lt;PAT&gt;</code> 헤더로 전송하세요.</p><p>OAuth 지원 클라이언트에서는 allen.company 중앙 SSO로 연결할 수 있습니다. Claude Code SSO는 중앙 callback 등록 호환성 확인이 필요합니다. 현재는 PAT 연결을 사용하세요. PAT과 OAuth 모두 서버가 현재 저장소 권한을 확인하며, PAT에 지정한 저장소·동작 범위를 넘을 수 없습니다.</p></section><section id="mutation-receipts" hidden aria-live="polite"><h2>발급·확인 결과 보관</h2><p>후속 작업에 필요한 식별자는 이 페이지에 보관하고, 비밀 값과 확인 코드는 60초 동안 표시합니다. 새로고침하거나 페이지를 닫기 전에 필요한 결과를 복사하세요. 결과 지우기, 로그아웃, 계정 변경 시 지웁니다.</p><div id="receipt-list"></div></section><section><h2>작업 결과</h2><pre id="result" tabindex="0"></pre><button id="clear-result">결과 지우기</button></section></main><footer>Release candidate · 실환경 로그인·메일·검색·결제·복원 검증 후 출시하세요.</footer></body></html>`;
export const managementStyles = String.raw `*{box-sizing:border-box}body{margin:0;background:#f5f6f8;color:#17202b;font:15px/1.6 system-ui,sans-serif}header,main,footer{max-width:1240px;margin:auto;padding:24px}header{display:flex;gap:24px;align-items:center;justify-content:space-between}header small{letter-spacing:.13em;color:#506279}h1{font-size:28px;margin:6px 0}h2{font-size:21px}nav,.toolbar{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}section{background:white;padding:22px;margin-bottom:22px;border:1px solid #dce1e8;border-radius:12px}.grid section{min-width:0}.notice{border-left:4px solid #526d82;padding:12px 16px;background:#e9eff5}label{display:block;margin:10px 0}input:not([type=checkbox]),textarea,select{width:100%;padding:9px;border:1px solid #aeb9c8;border-radius:5px;font:inherit}textarea{resize:vertical}button,a{font:inherit}button{padding:8px 13px;border:1px solid #64778e;border-radius:5px;background:#f4f7fa;cursor:pointer;margin:5px 5px 5px 0}button:hover{background:#e5edf5}button:disabled{opacity:.55;cursor:wait}form{margin:16px 0;padding-bottom:14px;border-bottom:1px solid #e5e9ef}fieldset{border:1px solid #dce1e8}fieldset label{display:inline-block;margin-right:16px}small{display:block;color:#536374}details{padding:12px 0;border-top:1px solid #dce1e8}summary{cursor:pointer;font-weight:600}.memory,.proposal{padding:16px 0;border-bottom:1px solid #dce1e8;overflow-wrap:anywhere}.memory p,.proposal p{white-space:pre-wrap}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:440px;overflow:auto;font:13px/1.6 ui-monospace,monospace}#status{min-height:24px}footer{color:#536374}@media(max-width:800px){.grid{grid-template-columns:1fr}header{display:block}header,main,footer{padding:16px}h1{font-size:24px}}`;
export function renderManagementStyles(brand: Brand): string {
    const accent = /^#[0-9a-f]{6}$/i.test(brand.accentColor) ? brand.accentColor : '#276747';
    return managementStyles + ':root{--brand-accent:' + accent + '}a{color:var(--brand-accent)}button,.notice{border-color:var(--brand-accent)}:focus-visible{outline:2px solid var(--brand-accent);outline-offset:2px}input[type=checkbox]{accent-color:var(--brand-accent)}';
}
export const managementScript = String.raw `'use strict';
const $=id=>document.getElementById(id),pending=new Map(),drafts=new Map(),editDrafts=new Map(),spaceMetadata=new Map(),ingestOutcomes=new Map(),revokedShares=new Set(),receiptTimers=new Set(),secretResults=new WeakSet();let requestEpoch=0,verifiedRequestEpoch=0,authenticationEpoch=0,receiptEpoch=0,spaceEpoch=0,memoryQuery=null,workspace=null,cursor=null,deleted=false,secretTimer,epoch=0,memoryEpoch=0,ingestEpoch=0,shareEpoch=0,shareCursor=null,sharesLoading=false,outboundEpoch=0,outboundCursor=null,outboundLoading=false,organizationEpoch=0,taskEpoch=0,checkoutExpired=null,workspaceEpoch=0,workspaceLoading=false,authExpired=false,signedOut=false,selectedSpace='',logoutAccountId=null,logoutPending=false;
class StaleResponse extends Error {}
class CancelledAction extends Error {}
function cancelAction(message='작업을 취소했습니다. 요청을 보내지 않았습니다.'){throw new CancelledAction(message);}
function originContext(){const accountId=workspace?.account.id,selected=selectedSpace,spaceGeneration=spaceEpoch,workspaceGeneration=workspaceEpoch;return()=>{if(signedOut||workspace?.account.id!==accountId||selectedSpace!==selected||spaceEpoch!==spaceGeneration||workspaceEpoch!==workspaceGeneration)throw new StaleResponse();};}
function invalidate(clearPanels=false){epoch++;resetViews(clearPanels);}
function resetViews(clearPanels=false){memoryEpoch++;ingestEpoch++;shareEpoch++;outboundEpoch++;outboundCursor=null;outboundLoading=false;$('outbound-shares-more').hidden=true;$('outbound-shares-status').textContent='';clearTimeout(secretTimer);$('result').textContent='';shareCursor=null;sharesLoading=false;$('shares-more').hidden=true;checkoutExpired=null;$('checkout-new-attempt').hidden=true;if(clearPanels){ingestOutcomes.clear();revokedShares.clear();for(const id of ['memories','proposals','shares','outbound-shares'])$(id).replaceChildren();cursor=null;$('more').hidden=true;}}
function draft(){return Object.fromEntries(new FormData($('add-form')));}
function captureDraft(){return{...draft(),messages:$('ingest-form').elements.messages.value};}
function restoreDraft(id){const form=$('add-form'),saved=drafts.get(id)||{};for(const name of ['body','source','supersedesMemoryId'])form.elements[name].value=saved[name]||'';$('ingest-form').elements.messages.value=saved.messages||'';}
function patSpace(){const value=spaceMetadata.get($('space').value);if(!value||(value.organizationId!==null&&typeof value.organizationId!=='string'))throw Error('메모리 저장소 정보를 새로고침하세요.');return value;}
function patSelection(selected){const membership=workspace?.organizations.find(o=>o.id===selected.organizationId),shared=selected.organizationId?!membership:Array.isArray(workspace?.spaces)&&(!workspace.spaces.some(s=>s.id===selected.id)||workspace.spaces.find(s=>s.id===selected.id)?.canWrite===false);return{shared,organizationId:membership?selected.organizationId:null};}
function canWriteSpace(){const selected=spaceMetadata.get($('space').value);if(!selected)return false;const metadata=workspace?.spaces?.find(s=>s.id===selected.id);if(typeof metadata?.canWrite==='boolean')return metadata.canWrite;if(selected.organizationId)return workspace?.organizations.some(o=>o.id===selected.organizationId&&['owner','admin'].includes(o.role));return !Array.isArray(workspace?.spaces)||Boolean(metadata);}
function canManageOrganization(){return Boolean(workspace?.organizations.some(o=>o.id===$('organization').value&&['owner','admin'].includes(o.role)));}
function updateControls(){for(const button of document.querySelectorAll('main button'))button.disabled=signedOut||workspaceLoading||(authExpired&&button.id!=='resume-session')||button.dataset.unavailable==='true'||button.dataset.pending==='true'||(button.dataset.write==='true'&&!canWriteSpace())||(button.dataset.organization==='true'&&!canManageOrganization())||(button.id==='shares-more'&&sharesLoading)||(button.id==='outbound-shares-more'&&outboundLoading);for(const id of ['space','organization'])$(id).disabled=signedOut||workspaceLoading||authExpired;for(const el of document.querySelectorAll('#add-form input,#add-form textarea,#ingest-form textarea'))el.readOnly=authExpired||!canWriteSpace();$('space-permission').textContent=canWriteSpace()?'편집 가능':'읽기 전용 · 현재 저장소에 기억을 추가하거나 수정할 수 없습니다.';}
function configureFeatures(config){const f=config.features||{};for(const [selector,enabled]of [['#ingest-form button',f.ingestion],['#rebuild',f.indexRebuild],['#checkout-form button',f.billing],['#portal',f.billing],['#checkout-new-attempt',f.billing],['#reauth-start button',f.mail],['#email-start button',f.mail]]){const button=document.querySelector(selector);button.dataset.unavailable=String(!enabled);button.disabled=!enabled;}const unavailable=[];if(!f.ingestion)unavailable.push('대화 추출');if(!f.indexRebuild)unavailable.push('검색 인덱스 재생성');if(!f.billing)unavailable.push('결제');if(!f.mail)unavailable.push('확인 메일 발송');$('feature-status').textContent=unavailable.length?unavailable.join(' · ')+' 기능은 현재 사용할 수 없습니다. 메모리 저장·조회와 기본 검색은 사용할 수 있습니다.':'';$('retention-status').textContent=config.policy?.automaticErasure?'복원 기간이 지난 휴지통 기억은 정기 정리에서 영구 제거됩니다.':'자동 영구 제거가 꺼져 있습니다. 기간이 지나면 복원할 수 없으며, 본문과 이력은 직접 영구 제거할 때까지 보관됩니다.';}
function updatePatScope(){const selected=spaceMetadata.get($('space').value);if(!selected){$('pat-scope').textContent='먼저 메모리 저장소를 선택하세요.';return;}const {shared}=patSelection(selected),form=$('key-form');for(const checkbox of form.querySelectorAll('input[name="cap"]')){checkbox.disabled=shared||(!canWriteSpace()&&checkbox.value!=='read');if(shared)checkbox.checked=checkbox.value==='read';else if(!canWriteSpace()&&checkbox.value!=='read')checkbox.checked=false;}form.elements.singleSpace.disabled=shared;if(shared){form.elements.singleSpace.checked=true;$('pat-scope').textContent=selected.name+' · 개인 PAT로 승인된 공유 저장소만 조회합니다. 공유가 회수되면 키의 접근도 해제됩니다.';return;}const org=workspace?.organizations.find(o=>o.id===selected.organizationId),tenant=selected.organizationId?'조직 '+(org?.name||selected.organizationId):'현재 계정의 개인 범위';$('pat-scope').textContent=form.elements.singleSpace.checked?selected.name+' 저장소만 · '+tenant:selected.organizationId?tenant+'의 모든 저장소':'현재 계정이 소유한 모든 저장소와 수락한 공유 저장소(다른 조직 소유 포함) · 선택한 동작에 한함, 공유는 조회만 지원';}
// Both explicit selection and a refreshed workspace use this same draft boundary.
function transitionSpace(next){const previous=selectedSpace;if(previous)drafts.set(previous,captureDraft());selectedSpace=next;$('space').value=next;if(previous!==next){spaceEpoch++;memoryQuery=null;deleted=false;$('search-form').elements.query.value='';resetViews(true);}restoreDraft(next);updatePatScope();updateControls();if([...drafts].some(([id,value])=>!spaceMetadata.has(id)&&Object.values(value).some(part=>typeof part==='string'&&part.length)))preserveSubmittedCopies();}
function changeSpace(){if(workspaceLoading||signedOut||authExpired){$('space').value=selectedSpace;return;}transitionSpace($('space').value);task(()=>memories());}
function preserveSubmittedCopies(){if(selectedSpace)drafts.set(selectedSpace,captureDraft());$('recovery-drafts').hidden=false;$('recovery-text').textContent='작업이 적용된 제출본도 포함할 수 있습니다. 현재 저장된 본문이 아니므로 비교 후 사용하세요.\n'+JSON.stringify({spaces:[...drafts],edits:[...editDrafts]},null,2);}
function clearReceipts(){receiptEpoch++;for(const timer of receiptTimers)clearTimeout(timer);receiptTimers.clear();$('receipt-list').replaceChildren();$('mutation-receipts').hidden=true;}
function retainReceipt(value,context){if(!value||typeof value!=='object')return;const row=document.createElement('article');row.className='receipt';text(row,'p','계정 '+context.accountId+' · 요청 당시 선택 Space '+context.spaceId+' · '+context.scope);text(row,'pre',JSON.stringify(value,null,2));$('receipt-list').append(row);$('mutation-receipts').hidden=false;if(context.secret){const timer=setTimeout(()=>{row.remove();receiptTimers.delete(timer);$('mutation-receipts').hidden=!$('receipt-list').children.length;},60000);receiptTimers.add(timer);}}
function suspendSession(){authenticationEpoch++;clearReceipts();if(!workspace){endSession();return;}if(selectedSpace)drafts.set(selectedSpace,captureDraft());invalidate(true);authExpired=true;$('reauth-actions').hidden=false;$('recovery-drafts').hidden=false;$('recovery-text').textContent=JSON.stringify({spaces:[...drafts],edits:[...editDrafts]},null,2);for(const id of ['reauth-complete','email-complete'])$(id).elements.proof.value='';$('status').textContent='로그인이 만료되었습니다. 초안을 보존했으니 같은 계정으로 로그인하고 다시 연결하세요.';updateControls();}
function endSession(){authenticationEpoch++;clearReceipts();$('status').textContent='로그인이 필요합니다. 로그인한 뒤 페이지를 다시 불러오세요.';invalidate(true);signedOut=true;authExpired=false;workspace=null;pending.clear();drafts.clear();editDrafts.clear();$('reauth-actions').hidden=true;$('recovery-drafts').hidden=true;$('recovery-text').textContent='';spaceMetadata.clear();$('pat-scope').textContent='';for(const id of ['space','organization','email-select'])$(id).replaceChildren();for(const el of document.querySelectorAll('input,textarea')){if(el.type!=='checkbox')el.value='';}for(const el of document.querySelectorAll('form button,input,textarea,select'))el.disabled=true;updateControls();}
const space=()=>{if(!$('space').value)throw Error('Space를 선택하세요.');return encodeURIComponent($('space').value);};const organization=()=>{if(!$('organization').value)throw Error('조직을 선택하세요.');return encodeURIComponent($('organization').value);};
function renderResult(value){$('result').textContent=typeof value==='string'?value:JSON.stringify(value,null,2);clearTimeout(secretTimer);if(value&&typeof value==='object'&&(secretResults.has(value)||'token'in value))secretTimer=setTimeout(()=>$('result').textContent='비밀 값·확인 결과 표시 시간이 종료되었습니다.',60000);}

// Retain identifiers independently of task results; never retain memory bodies.
function receiptPolicy(path,method,data){
 const mutation=!['GET','HEAD'].includes(method),secret=method==='POST'&&(/^\/v1\/(keys|account\/reauth|account\/emails)$/.test(path)||/^\/v1\/organizations\/[^/]+\/(scim-keys|domains)$/.test(path)||/\/billing\/(checkout|portal)$/.test(path));
 const routeSpace=/^\/v1\/spaces\/([^/]+)/.exec(path),routeOrg=/^\/v1\/organizations\/([^/]+)/.exec(path);
 const label=path==='/v1/keys'?'PAT · '+$('pat-scope').textContent:path==='/v1/domains/verify'?'도메인 검증 · Challenge '+(data?.challengeId||''):path.includes('/scim-keys')?'SCIM 키':path.includes('/domains')?'도메인 확인':path.includes('/shares')?'읽기 공유':path.includes('/exports')?'내보내기 세션':path.includes('/ingests')?'대화 추출·승인':path.includes('/billing')?'결제 세션':path.includes('/memories')?'기억 작업':path.includes('/account/reauth')?'계정 본인 확인':path.includes('/account/emails')?'이메일 연결':'작업 식별자';
 const scope=(routeOrg?'조직 '+decodeURIComponent(routeOrg[1])+' · ':routeSpace?'Space '+decodeURIComponent(routeSpace[1])+' · ':'')+label;
 return{scope,secret,project(value){if(!mutation||!value||typeof value!=='object')return null;if(secret)return value;const receipt={};for(const key of ['id','emailId','challengeId','spaceId','revision','committedRevision','representation','replayed','state','status','accessRemoved','payloadCleanup','indexCleanup','expiresAt','verifiedUntil','name'])if(value[key]!==undefined)receipt[key]=value[key];if(Array.isArray(value.memories))receipt.memories=value.memories.flatMap(item=>typeof item==='string'?[item]:item?.id?[item.id]:[]);if(!receipt.id&&!receipt.emailId&&!receipt.challengeId&&!receipt.memories)return null;if(data?.operationId)receipt.operationId=data.operationId;return receipt;}};
}
async function api(path,method='GET',data,accountId=path==='/v1/workspace'?null:workspace?.account.id,allowExpired=false,isCurrent=()=>true){
 const policy=receiptPolicy(path,method,data),receiptContext={generation:receiptEpoch,accountId:workspace?.account.id,spaceId:selectedSpace,scope:policy.scope,secret:policy.secret};
 const receiptCurrent=()=>receiptContext.generation===receiptEpoch&&workspace?.account.id===receiptContext.accountId&&!authExpired&&!signedOut;
 const request=++requestEpoch,authGeneration=authenticationEpoch,requestAccount=workspace?.account.id,generation=epoch,spaceGeneration=spaceEpoch,workspaceGeneration=workspaceEpoch,orgGeneration=organizationEpoch,orgScoped=path.startsWith('/v1/organizations/')||path.startsWith('/v1/domains');
 const stale=()=>signedOut||generation!==epoch||spaceGeneration!==spaceEpoch||workspaceGeneration!==workspaceEpoch||!isCurrent()||(orgScoped&&orgGeneration!==organizationEpoch);
 const authenticationCurrent=()=>!signedOut&&authGeneration===authenticationEpoch&&requestAccount===workspace?.account.id&&request>=verifiedRequestEpoch;
 if(signedOut||(authExpired&&!allowExpired))throw new StaleResponse();
 let res,responseText;try{res=await fetch(path,{method,credentials:'same-origin',headers:{accept:'application/json',...(accountId?{'x-memory-account-id':accountId}:{}),...(data===undefined?{}:{'content-type':'application/json'})},...(data===undefined?{}:{body:JSON.stringify(data)})});}catch(error){if(stale())throw new StaleResponse();error.uncertain=!['GET','HEAD'].includes(method);throw error;}
 if(res.status===401){if(authenticationCurrent())suspendSession();throw new StaleResponse();}
 try{responseText=await res.text();}catch(error){if(stale())throw new StaleResponse();error.status=res.status;error.uncertain=(res.ok||res.status>=500)&&!['GET','HEAD'].includes(method);throw error;}
 let value;try{value=responseText?JSON.parse(responseText):null;}catch{if(stale())throw new StaleResponse();const error=Error('서버 응답을 확인할 수 없습니다.');error.uncertain=(res.ok||res.status>=500)&&!['GET','HEAD'].includes(method);throw error;}
 if(res.status===409&&value?.error==='account_mismatch'){if(authenticationCurrent()){endSession();$('status').textContent='다른 계정으로 로그인되어 이전 계정의 초안과 화면을 지웠습니다. 페이지를 새로고침하거나 다시 로그인하세요.';}throw new StaleResponse();}
 if(res.ok&&authGeneration===authenticationEpoch&&requestAccount===workspace?.account.id)verifiedRequestEpoch=Math.max(verifiedRequestEpoch,request);
 if(res.ok&&receiptCurrent()){const receipt=policy.project(value);if(receipt){if(policy.secret)secretResults.add(receipt);retainReceipt(receipt,receiptContext);}}if(stale())throw new StaleResponse();
 if(!res.ok){const error=Error(value?.error==='search_token_too_long'?'검색 단어는 각각 31자까지 입력할 수 있습니다. 검색어를 줄여 주세요.':value?.error==='restore_expired'?'복원 기간이 지나 이 기억을 복원할 수 없습니다.':(value&&value.error)||('HTTP '+res.status));error.code=value?.error;error.status=res.status;error.uncertain=res.status>=500&&!['GET','HEAD'].includes(method);throw error;}return value;
}
async function task(fn){const generation=epoch,ticket=++taskEpoch,current=()=>generation===epoch&&ticket===taskEpoch&&!signedOut;if(signedOut)return;let completion='완료';const assertContext=originContext(),result=value=>{assertContext();if(!current())return false;renderResult(value);if(value?.status==='access_removed_cleanup_pending')completion='접근 차단 · 원문·인덱스 정리 확인 대기';return true;};result.assertContext=assertContext;$('status').textContent='처리 중';try{await fn(result);if(current())$('status').textContent=completion;}catch(e){if(!current())return;if(e instanceof StaleResponse){$('status').textContent='이전 요청을 종료했습니다. 최신 화면을 확인하세요.';return;}$('status').textContent=e.message;if(!(e instanceof CancelledAction))renderResult({error:e.message});}}
function operation(name,data){const fingerprint=JSON.stringify(data),old=pending.get(name);if(old&&old.fingerprint===fingerprint)return old.id;const id=crypto.randomUUID();pending.set(name,{id,fingerprint});return id;}
function validateMemory(input){if(typeof input.body!=='string'||!input.body.trim()||input.body.includes('\0')||new TextEncoder().encode(input.body).length>16384)throw Error('본문은 비어 있지 않은 UTF-8 16,384바이트 이하여야 합니다.');if(input.source&&(input.source.includes('\0')||new TextEncoder().encode(input.source).length>2048))throw Error('출처는 UTF-8 2,048바이트 이하여야 합니다.');}
function form(name,fn){const el=$(name);el.addEventListener('submit',e=>{e.preventDefault();const button=el.querySelector('button');if(signedOut||authExpired||workspaceLoading||button.disabled)return;button.dataset.pending='true';button.disabled=true;task(async result=>{await fn(Object.fromEntries(new FormData(el)),el,result);}).finally(()=>{delete button.dataset.pending;if(!signedOut)updateControls();});});}
function issue(id,fn){const button=$(id);button.addEventListener('click',()=>{if(signedOut||authExpired||workspaceLoading||button.disabled)return;button.dataset.pending='true';button.disabled=true;task(fn).finally(()=>{delete button.dataset.pending;updateControls();});});}
function click(id,fn){$(id).addEventListener('click',()=>{if(!workspaceLoading)task(fn);});}function option(el,value,label){const n=document.createElement('option');n.value=value;n.textContent=label;el.append(n);}function text(el,tag,value){const n=document.createElement(tag);n.textContent=value;el.append(n);return n;}function action(el,label,fn,write=true){const b=document.createElement('button');b.textContent=label;b.dataset.write=String(write);b.disabled=workspaceLoading||authExpired||(write&&!canWriteSpace());b.addEventListener('click',()=>{if(b.disabled||workspaceLoading||authExpired)return;b.dataset.pending='true';b.disabled=true;task(fn).finally(()=>{delete b.dataset.pending;updateControls();});});el.append(b);return b;}
async function load(recover=false){const generation=++workspaceEpoch;workspaceLoading=true;updateControls();try{const next=await api('/v1/workspace','GET',undefined,recover?workspace?.account.id:null,recover,()=>generation===workspaceEpoch);if(generation!==workspaceEpoch)throw new StaleResponse();if(workspace&&workspace.account.id!==next.account.id){authenticationEpoch++;clearReceipts();memoryQuery=null;invalidate(true);pending.clear();drafts.clear();editDrafts.clear();spaceMetadata.clear();$('recovery-drafts').hidden=true;$('recovery-text').textContent='';selectedSpace='';deleted=false;for(const form of document.forms)form.reset();for(const id of ['space','organization','email-select','prices'])$(id).replaceChildren();await task(()=>loadWorkspace(next,generation,recover));}else await loadWorkspace(next,generation,recover);}finally{if(generation===workspaceEpoch){workspaceLoading=false;updateControls();}}}
async function loadWorkspace(nextWorkspace,generation,recover=false){
 const spaces=[];let next=null;
 do{const page=await api('/v1/spaces?limit=100'+(next?'&cursor='+encodeURIComponent(next):''),'GET',undefined,nextWorkspace.account.id,recover,()=>generation===workspaceEpoch);if(generation!==workspaceEpoch)throw new StaleResponse();spaces.push(...page.results);next=page.nextCursor;}while(next);
 const config=await api('/v1/release/config','GET',undefined,nextWorkspace.account.id,recover,()=>generation===workspaceEpoch);if(generation!==workspaceEpoch)throw new StaleResponse();
 // Install a complete, account-bound snapshot synchronously. Until now the old
 // selection and its draft remain paired, and all actions are paused.
 const old=selectedSpace;authenticationEpoch++;workspace=nextWorkspace;authExpired=false;$('reauth-actions').hidden=true;
 $('email-select').replaceChildren();for(const e of workspace.account.emails)option($('email-select'),e.id,e.address+' · '+e.id);
 $('organization').replaceChildren();option($('organization'),'','개인');for(const o of workspace.organizations)option($('organization'),o.id,o.name+' · '+o.role);
 $('space').replaceChildren();spaceMetadata.clear();for(const s of spaces){spaceMetadata.set(s.id,s);option($('space'),s.id,s.name+' · '+s.id);}if(spaces.some(s=>s.id===old))$('space').value=old;
 configureFeatures(config);updateControls();$('prices').replaceChildren();for(const [id,p]of Object.entries(config.prices))option($('prices'),id,p.plan+' · '+p.monthlyUnits+' units/month');
 transitionSpace($('space').value);if(selectedSpace)await memories();
}
async function memories(next=false){const generation=++memoryEpoch;if(!next){cursor=null;$('memories').replaceChildren();}const search=memoryQuery!==null,path='/v1/spaces/'+space()+'/memories'+(search?'?query='+encodeURIComponent(memoryQuery):'?limit=25&deleted='+deleted+(cursor?'&cursor='+encodeURIComponent(cursor):''));const page=await api(path,'GET',undefined,undefined,false,()=>generation===memoryEpoch);if(generation!==memoryEpoch)throw new StaleResponse();renderMemories(page.results);cursor=search?null:page.nextCursor;$('more').hidden=!cursor;return page;}
// A refresh changes the fetch generation, but keeps the same selected view.
function memoryView(){const origin=originContext(),query=memoryQuery,trash=deleted;return()=>{origin();return query===memoryQuery&&trash===deleted;};}
async function refreshMemoryView(view){if(view())await memories();}
function restoreAction(card,m){
 const help=text(card,'p','');help.id='restore-help-'+encodeURIComponent(m.id);help.className='field-help';
 const expired=()=>{button.dataset.unavailable='true';button.disabled=true;help.textContent='복원 기간이 지나 이 기억을 복원할 수 없습니다.';};
 const button=action(card,'복원',async result=>{const view=memoryView();try{result(await api('/v1/spaces/'+space()+'/memories/'+encodeURIComponent(m.id)+'/restore','POST',{expectedRevision:m.revision,operationId:operation('restore:'+m.id,{revision:m.revision})}));}catch(error){if(error.code==='restore_expired')expired();throw error;}await refreshMemoryView(view);});
 button.setAttribute('aria-describedby',help.id);if(m.restoreExpired===true)expired();else help.textContent=Number.isFinite(m.restoreUntil)?'복원 가능 기한: '+new Date(m.restoreUntil).toISOString():'복원 가능 여부는 서버에서 현재 보존 정책에 따라 확인합니다.';
}
function renderMemories(items){for(const m of items){const card=document.createElement('article');card.className='memory';const editKey=selectedSpace+':'+m.id;const showDraft=()=>{card.querySelector('.edit-draft')?.remove();const saved=editDrafts.get(editKey);if(!saved)return;const label=document.createElement('label');label.className='edit-draft';label.textContent=saved.receipt?'적용된 작업 제출본 · 현재 본문을 확인할 수 없어 복사용으로 보존합니다.':'저장되지 않은 수정 초안 · 현재 본문과 비교 후 수정으로 다시 제출하세요.';const textarea=document.createElement('textarea');textarea.readOnly=true;textarea.value=saved.body;label.append(textarea);card.append(label);};text(card,'small',m.id+' · revision '+m.revision);text(card,'p',m.body);text(card,'small',JSON.stringify(m.provenance||{}));if(m.deletedAt){restoreAction(card,m);action(card,'영구 제거',async result=>{const view=memoryView();const confirmation=prompt('접근을 차단하고 원문·이력 및 검색 인덱스의 영구 정리를 요청합니다. 물리적 정리는 비동기로 진행됩니다. 확인하려면 기억 ID를 입력하세요.', '');if(confirmation!==m.id)cancelAction(confirmation===null?undefined:'확인 ID가 일치하지 않아 요청을 보내지 않았습니다.');result(await api('/v1/spaces/'+space()+'/memories/'+encodeURIComponent(m.id)+'/erase','POST',{expectedRevision:m.revision,confirmation,operationId:operation('erase:'+m.id,{revision:m.revision})}));await refreshMemoryView(view);});}else{action(card,'수정',async result=>{const view=memoryView();const body=prompt('기억 본문 수정',editDrafts.get(editKey)?.body??m.body);if(body===null)cancelAction();const input={body,expectedRevision:m.revision};editDrafts.set(editKey,input);showDraft();preserveSubmittedCopies();validateMemory(input);const operationId=operation('edit:'+m.id,input),saved=await api('/v1/spaces/'+space()+'/memories/'+encodeURIComponent(m.id),'PATCH',{...input,operationId});result(saved);if(saved.representation==='receipt'){const copyKey=editDrafts.get(editKey)===input?editKey:editKey+':submitted:'+operationId;editDrafts.set(copyKey,{...input,receipt:true});preserveSubmittedCopies();}else if(editDrafts.get(editKey)===input)editDrafts.delete(editKey);await refreshMemoryView(view);});action(card,'휴지통',async result=>{const view=memoryView();if(!confirm('이 기억을 휴지통으로 이동할까요?'))cancelAction();result(await api('/v1/spaces/'+space()+'/memories/'+encodeURIComponent(m.id),'DELETE',{expectedRevision:m.revision,operationId:operation('delete:'+m.id,{revision:m.revision})}));await refreshMemoryView(view);});}showDraft();$('memories').append(card);}}
$('reload').addEventListener('click',()=>{if(signedOut){location.reload();return;}if(authExpired){task(()=>load(true));return;}invalidate(true);task(()=>load());});$('logout').addEventListener('click',async()=>{if(logoutPending)return;const accountId=logoutAccountId??workspace?.account.id;if(!accountId){endSession();$('status').textContent='계정을 확인할 수 없어 로그아웃 요청을 보내지 않았습니다. 페이지를 새로고침하세요.';return;}logoutAccountId=accountId;logoutPending=true;endSession();$('status').textContent='로그아웃 중';try{const response=await fetch('/auth/logout',{method:'POST',credentials:'same-origin',headers:{'x-memory-account-id':accountId}});if(!response.ok){const detail=await response.json().catch(()=>null);throw Error(detail?.error||'logout_failed');}location.assign('/manage');}catch(error){$('status').textContent=error.message==='account_mismatch'?'계정이 변경되어 로그아웃을 중단했습니다. 페이지를 새로고침하세요.':'로그아웃 요청을 완료하지 못했습니다. 다시 시도하세요.';}finally{logoutPending=false;}});click('refresh-memories',async()=>{memoryQuery=null;deleted=false;await memories();});click('trash',async()=>{memoryQuery=null;deleted=true;await memories();});click('more',()=>memories(true));$('space').addEventListener('change',changeSpace);$('key-form').elements.singleSpace.addEventListener('change',updatePatScope);$('organization').addEventListener('change',()=>{organizationEpoch++;taskEpoch++;clearTimeout(secretTimer);$('result').textContent='';$('status').textContent='';updateControls();});$('clear-result').addEventListener('click',()=>{if(workspaceLoading||signedOut||authExpired)return;clearReceipts();taskEpoch++;clearTimeout(secretTimer);$('result').textContent='';$('status').textContent='결과를 지웠습니다.';});
form('add-form',async(d,el,result)=>{const view=memoryView(),selected=space(),submitted=JSON.stringify(d);const input={body:d.body,...(d.source?{source:d.source}:{}),...(d.supersedesMemoryId?{supersedesMemoryId:d.supersedesMemoryId}:{})};validateMemory(input);const saved=await api('/v1/spaces/'+selected+'/memories','POST',{...input,operationId:operation('add:'+selected,input)});result(saved);if(saved.representation==='receipt'){editDrafts.set(decodeURIComponent(selected)+':submitted:'+saved.id,{...input,receipt:true});preserveSubmittedCopies();}else{pending.delete('add:'+selected);if(JSON.stringify(draft())===submitted){el.reset();drafts.delete(decodeURIComponent(selected));}}await refreshMemoryView(view);});
form('search-form',async(d,el,result)=>{memoryQuery=d.query;deleted=false;const r=await memories();result({mode:r.mode,degradedReason:r.degradedReason});});
const challengeEdits=new Map();for(const id of ['reauth-complete','email-complete'])for(const event of ['input','change'])$(id).addEventListener(event,()=>challengeEdits.set(id,(challengeEdits.get(id)||0)+1));
function challengeFields(id){const el=$(id),generation=challengeEdits.get(id)||0,before=[el.elements.challengeId.value,el.elements.proof.value];const unchanged=()=>generation===(challengeEdits.get(id)||0)&&before[0]===el.elements.challengeId.value&&before[1]===el.elements.proof.value;return{install(value){if(unchanged()){el.elements.challengeId.value=value;el.elements.proof.value='';}},clearProof(){if(unchanged())el.elements.proof.value='';}};}
form('reauth-start',async(d,el,result)=>{const fields=challengeFields('reauth-complete'),r=await api('/v1/account/reauth','POST',d);if(result(r))fields.install(r.id);});form('reauth-complete',async(d,el,result)=>{const fields=challengeFields(el.id);result(await api('/v1/account/reauth/complete','POST',d));fields.clearProof();});
form('email-start',async(d,el,result)=>{const fields=challengeFields('email-complete'),r=await api('/v1/account/emails','POST',d);if(result(r))fields.install(r.challengeId);});form('email-complete',async(d,el,result)=>{const fields=challengeFields(el.id);result(await api('/v1/account/emails/verify','POST',d));fields.clearProof();await load();});form('email-unlink',async(d,el,result)=>{if(!confirm('종속 조직 멤버십과 키가 회수됩니다. 계속할까요?'))cancelAction();result(await api('/v1/account/emails/'+encodeURIComponent(d.emailId),'DELETE'));await load();});
form('key-form',async(d,el,result)=>{const selected=patSpace(),{shared,organizationId:org}=patSelection(selected),caps=shared?['read']:[...new FormData(el).getAll('cap')];result(await api('/v1/keys','POST',{label:d.label,capabilities:caps,expiresInDays:Number(d.expiresInDays),...(shared||d.singleSpace?{spaceIds:[selected.id]}:{}),...(org?{organizationId:org}:{})}));});form('key-revoke',async(d,el,result)=>{result(await api('/v1/keys/'+encodeURIComponent(d.keyId),'DELETE'));});
form('retention-form',async(d,el,result)=>result(await api('/v1/spaces/'+space()+'/retention','PUT',{days:Number(d.days)})));click('usage',async result=>result(await api('/v1/spaces/'+space()+'/usage')));click('rebuild',async result=>result(await api('/v1/spaces/'+space()+'/index/rebuild','POST',{})));click('jobs',async result=>result(await api('/v1/spaces/'+space()+'/jobs')));form('job-retry',async(d,el,result)=>result(await api('/v1/spaces/'+space()+'/jobs/'+encodeURIComponent(d.jobId)+'/retry','POST',{})));
issue('export',async result=>{const s=space(),session=await api('/v1/spaces/'+s+'/exports','POST',{}),records=[];let cursor=null;do{const page=await api('/v1/spaces/'+s+'/exports/'+encodeURIComponent(session.id)+(cursor?'?cursor='+encodeURIComponent(cursor):''));records.push(...page.results);cursor=page.nextCursor;}while(cursor);result.assertContext();const blob=new Blob([JSON.stringify({format:'memory-export-v1',spaceId:decodeURIComponent(s),memories:records},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='memory-export-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);result({exported:records.length});});
form('ingest-form',async(d,el,result)=>{const s=space(),input={messages:JSON.parse(d.messages)};result(await api('/v1/spaces/'+s+'/ingests','POST',{...input,operationId:operation('ingest:'+s,input)}));pending.delete('ingest:'+s);});
function installIngestCard(card){const prior=[...$('proposals').children].find(row=>row.dataset.ingestId===card.dataset.ingestId);if(prior)prior.replaceWith(card);else $('proposals').append(card);}
function completeIngest(id,state){ingestOutcomes.set(id,state);const card=document.createElement('article');card.className='proposal';card.dataset.ingestId=id;text(card,'small',id+' · '+state);text(card,'p',state==='approved'?'승인 완료':'취소 완료');installIngestCard(card);}
click('ingests',async()=>{
 const generation=++ingestEpoch;$('proposals').replaceChildren();const s=space(),page=await api('/v1/spaces/'+s+'/ingests','GET',undefined,undefined,false,()=>generation===ingestEpoch);if(generation!==ingestEpoch)throw new StaleResponse();
 for(const job of page.results){
  let current=ingestOutcomes.has(job.id)?{...job,state:ingestOutcomes.get(job.id)}:job.state==='review'?await api('/v1/spaces/'+s+'/ingests/'+encodeURIComponent(job.id),'GET',undefined,undefined,false,()=>generation===ingestEpoch):job;if(generation!==ingestEpoch)throw new StaleResponse();
  if(ingestOutcomes.has(job.id))current={...current,state:ingestOutcomes.get(job.id),proposals:[]};
  const card=document.createElement('article');card.className='proposal';card.dataset.ingestId=job.id;text(card,'small',job.id+' · '+current.state);
  if(current.state==='review'){
   const checks=[];current.proposals.forEach((p,index)=>{const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=true;checks.push(check);label.append(check,document.createTextNode(p.body));card.append(label);text(card,'small','근거 ['+p.sourceMessageId+']: '+p.quote);});
   action(card,'선택 항목 승인',async result=>{const selected=checks.flatMap((c,i)=>c.checked?[i]:[]);result(await api('/v1/spaces/'+s+'/ingests/'+encodeURIComponent(job.id)+'/approve','POST',{selected,operationId:operation('approve:'+job.id,selected)}));completeIngest(job.id,'approved');});
  }
  if(['queued','review','failed'].includes(current.state))action(card,'취소 및 원문 제거',async result=>{result(await api('/v1/spaces/'+s+'/ingests/'+encodeURIComponent(job.id),'DELETE'));completeIngest(job.id,'cancelled');});installIngestCard(card);
 }
});
async function shareMutation(path,method,data){try{return await api(path,method,data);}catch(error){if(error.uncertain&&method==='DELETE')throw Error('공유 회수 요청의 처리 결과를 확인할 수 없습니다. 보낸 공유 새로고침에서 해당 ID의 회수 기록을 확인하세요.');if(error.uncertain)throw Error('공유 요청의 처리 결과를 확인할 수 없습니다. 보낸 공유 새로고침에서 기록을 확인한 뒤 필요한 작업을 선택하세요. 공유 제안을 다시 보내면 별도 공유가 생성될 수 있습니다.');throw error;}}
form('share-form',async(d,el,result)=>result(await shareMutation('/v1/spaces/'+space()+'/shares','POST',{email:d.email,days:Number(d.days)})));
function confirmShareRow(row){for(const button of row.querySelectorAll('button'))button.remove();const history=row.querySelector('.share-history');if(history)history.textContent=history.textContent.replace(/ · 회수 .*$/,' · 회수 완료 (저장 시각 조회 필요)');row.querySelector('.revoke-confirmation')?.remove();text(row,'p','회수를 완료했습니다. 저장된 회수 시각은 새로고침하여 확인하세요.').className='revoke-confirmation';}
async function revokeShare(shareId,result){const selected=space();await shareMutation('/v1/spaces/'+selected+'/shares/'+encodeURIComponent(shareId),'DELETE');result({id:shareId,spaceId:decodeURIComponent(selected),revoked:true});revokedShares.add(shareId);for(const row of $('outbound-shares').children)if(row.dataset.shareId===shareId)confirmShareRow(row);}
form('share-revoke',async(d,el,result)=>revokeShare(d.shareId,result));
async function outboundShares(append=false){
 if(append&&(!outboundCursor||outboundLoading))cancelAction('추가 보낸 공유를 불러올 수 없거나 이미 요청 중입니다.');
 const generation=++outboundEpoch,selected=space();outboundLoading=true;updateControls();$('outbound-shares-status').textContent='보낸 공유를 불러오는 중입니다.';
 try{
  const page=await api('/v1/spaces/'+selected+'/shares?limit=25'+(append?'&cursor='+encodeURIComponent(outboundCursor):''),'GET',undefined,undefined,false,()=>generation===outboundEpoch);if(generation!==outboundEpoch)throw new StaleResponse();
  const fragment=document.createDocumentFragment();for(const share of page.results){
   if(append&&[...$('outbound-shares').children].some(row=>row.dataset.shareId===share.id))continue;
   const row=document.createElement('article');row.className='receipt';row.dataset.shareId=share.id;text(row,'p',share.recipientEmail);text(row,'pre',share.id);
   const timestamp=value=>value==null?'기록 없음':new Date(value).toISOString();text(row,'p','생성 '+timestamp(share.createdAt)+' · 만료 '+timestamp(share.expiresAt)+' · 수락 '+timestamp(share.acceptedAt)+' · 회수 '+timestamp(share.revokedAt)).className='share-history';
   if(share.revokedAt!=null)text(row,'p','회수된 공유');else if(revokedShares.has(share.id))confirmShareRow(row);else action(row,'공유 회수',result=>revokeShare(share.id,result));fragment.append(row);
  }
  if(!append)$('outbound-shares').replaceChildren();$('outbound-shares').append(fragment);outboundCursor=page.nextCursor||null;$('outbound-shares-more').hidden=!outboundCursor;$('outbound-shares-status').textContent=$('outbound-shares').children.length?'조회한 저장 기록입니다.':'보낸 공유 기록이 없습니다.';
 }catch(error){if(generation===outboundEpoch&&!(error instanceof StaleResponse))$('outbound-shares-status').textContent='목록을 확인하지 못했습니다. 새로고침하거나 다음 페이지를 다시 불러오세요.';throw error;}
 finally{if(generation===outboundEpoch){outboundLoading=false;updateControls();}}
}
click('outbound-shares-refresh',()=>outboundShares());click('outbound-shares-more',()=>outboundShares(true));
async function invitations(append=false){if(append&&(!shareCursor||sharesLoading))cancelAction('추가 공유 제안을 불러올 수 없거나 이미 요청 중입니다.');const generation=++shareEpoch;if(!append){shareCursor=null;$('shares-more').hidden=true;$('shares').replaceChildren();}sharesLoading=true;updateControls();try{const page=await api('/v1/shares?limit=25'+(append?'&cursor='+encodeURIComponent(shareCursor):''),'GET',undefined,undefined,false,()=>generation===shareEpoch);if(generation!==shareEpoch)throw new StaleResponse();for(const invite of page.results){if([...$('shares').children].some(row=>row.dataset.inviteId===invite.id))continue;const row=document.createElement('div');row.dataset.inviteId=invite.id;text(row,'p',JSON.stringify(invite));action(row,'읽기 공유 수락',async result=>{result(await api('/v1/shares/'+encodeURIComponent(invite.id)+'/accept','POST',{}));await load();},false);$('shares').append(row);}shareCursor=page.nextCursor||null;$('shares-more').hidden=!shareCursor;}finally{if(generation===shareEpoch){sharesLoading=false;updateControls();}}}
click('invitations',()=>invitations());click('shares-more',()=>invitations(true));
form('domain-start',async(d,el,result)=>result(await api('/v1/organizations/'+organization()+'/domains','POST',d)));form('domain-verify',async(d,el,result)=>result(await api('/v1/domains/verify','POST',d)));form('domain-delegate',async(d,el,result)=>result(await api('/v1/domains/'+encodeURIComponent(d.domainId)+'/delegates','POST',{membershipId:d.membershipId})));form('domain-revoke',async(d,el,result)=>{if(!confirm('해당 이메일의 서비스 접근을 회수할까요?'))cancelAction();result(await api('/v1/domains/'+encodeURIComponent(d.domainId)+'/emails/revoke','POST',{email:d.email}));});issue('scim-key',async result=>result(await api('/v1/organizations/'+organization()+'/scim-keys','POST',{})));
form('checkout-form',async(d,el,result)=>{const selected=space(),operationId=operation('checkout:'+selected,d);try{const r=await api('/v1/spaces/'+selected+'/billing/checkout','POST',{priceId:d.priceId,operationId});result.assertContext();checkoutExpired=null;$('checkout-new-attempt').hidden=true;location.assign(r.url);}catch(error){if(error.code==='checkout_expired'){checkoutExpired={space:selected,operationId};$('checkout-new-attempt').hidden=false;}throw error;}});click('checkout-new-attempt',result=>{if(!checkoutExpired||checkoutExpired.space!==space())cancelAction('현재 Space에서 새 결제 시도를 시작할 요청이 없습니다.');const name='checkout:'+space();if(pending.get(name)?.id===checkoutExpired.operationId)pending.delete(name);checkoutExpired=null;$('checkout-new-attempt').hidden=true;result('새 결제 시도를 준비했습니다. 상품을 확인하고 구독 결제를 다시 누르세요. 이전 세션의 대조와 안전 검사는 서버에서 계속 수행됩니다.');});issue('portal',async result=>{const r=await api('/v1/spaces/'+space()+'/billing/portal','POST',{});result.assertContext();location.assign(r.url);});
for(const selector of ['#add-form button','#ingest-form button','#retention-form button','#share-form button','#share-revoke button','#job-retry button','#rebuild','#checkout-form button','#checkout-new-attempt','#portal','#jobs','#export','#outbound-shares-refresh','#outbound-shares-more'])document.querySelector(selector).dataset.write='true';
for(const selector of ['#scim-key','#domain-start button','#domain-verify button','#domain-delegate button','#domain-revoke button'])document.querySelector(selector).dataset.organization='true';
$('resume-session').addEventListener('click',()=>{if(authExpired&&!workspaceLoading)task(()=>load(true));});
task(()=>load());
`;
