import type { Brand } from '../ui.ts';
/** Static same-origin management console. All server data is rendered as text. */
export function renderManagement(brand: Brand): string {
    const escape = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
    return managementHtml.replace('<title>Memory', '<title>' + escape(brand.name))
        .replace('MEMORY / MANAGED STANDARD', escape(brand.shortName) + ' / MANAGED STANDARD')
        .replace('기억과 접근 권한 관리</h1>', escape(brand.name) + ' · 기억과 접근 권한 관리</h1>')
        .replace('Release candidate · 실환경', '<a href="mailto:' + escape(brand.supportEmail) + '">문의</a> · Release candidate · 실환경');
}
export const managementHtml = String.raw `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Memory · 서비스 관리</title><link rel="stylesheet" href="/assets/release.css"><script defer src="/assets/release.js"></script></head><body>
<header><div><small>MEMORY / MANAGED STANDARD</small><h1>기억과 접근 권한 관리</h1></div><nav><a href="/">기존 조직 콘솔</a><a href="/auth/login">로그인</a><button id="reload">새로고침</button><button id="logout">로그아웃</button></nav></header>
<main><p class="notice">Standard 모드에서는 서비스가 메모리 본문을 읽을 수 있습니다. 원문 추출은 임시 암호화 저장 후 검토하며, 이 서비스는 Zero-Access 모드가 아닙니다.</p><p id="status" role="status">로그인 상태를 확인합니다.</p><p id="feature-status" role="status"></p>
<section class="toolbar"><label>메모리 저장소(Space)<select id="space"></select></label><label>도메인·SCIM 관리 조직<select id="organization"><option value="">개인</option></select></label><button id="usage">공동 사용량</button><button id="refresh-memories">기억 목록</button><button id="trash">휴지통</button></section>
<div class="grid"><section><h2>기억 저장·검색</h2><form id="add-form"><label>기억 본문<textarea name="body" rows="5" required maxlength="16000"></textarea></label><label>원문 또는 출처<input name="source" maxlength="2048"></label><label>대체할 기존 기억 ID (선택)<input name="supersedesMemoryId"></label><button>저장</button><small>응답이 유실되면 같은 내용으로 다시 제출하세요. 현재 페이지에서 작업 키를 유지합니다.</small></form><form id="search-form"><label>검색어<input name="query" required></label><button>검색</button></form><div id="memories"></div><button id="more" hidden>다음 페이지</button></section>
<section><h2>최근 본인 확인</h2><p>PAT 발급·이메일 변경·영구 제거·결제 관리에는 5분 이내 확인이 필요합니다.</p><form id="reauth-start"><label>기존 확인된 이메일<select name="emailId" id="email-select"></select></label><button>확인 코드 발송</button></form><form id="reauth-complete"><label>Challenge ID<input name="challengeId" id="reauth-id" required></label><label>이메일의 Proof<input name="proof" autocomplete="off" required></label><button>본인 확인</button></form>
<details><summary>이메일 연결·회수</summary><form id="email-start"><label>추가 이메일<input type="email" name="email" required></label><button>확인 메일 발송</button></form><form id="email-complete"><label>Challenge ID<input name="challengeId" id="email-challenge" required></label><label>Proof<input name="proof" autocomplete="off" required></label><button>이메일 연결</button></form><form id="email-unlink"><label>회수할 이메일 ID<input name="emailId" required></label><button>연결 해제 및 종속 권한 회수</button></form></details>
<details><summary>PAT (개인 액세스 토큰)</summary><form id="key-form"><label>PAT 이름<input name="label" required></label><fieldset><legend>허용 동작</legend><label><input type="checkbox" name="cap" value="read" checked>조회</label><label><input type="checkbox" name="cap" value="create">추가</label><label><input type="checkbox" name="cap" value="update">수정</label><label><input type="checkbox" name="cap" value="delete">삭제</label><label><input type="checkbox" name="cap" value="export">내보내기</label></fieldset><label><input type="checkbox" name="singleSpace" checked>현재 메모리 저장소만 허용 (기본)</label><p id="pat-scope" aria-live="polite"></p><small>해제하면 선택한 저장소가 속한 개인 계정 또는 조직의 모든 저장소를 허용합니다. 다른 조직이나 하위 조직으로 권한이 확대되지는 않습니다.</small><label>유효기간(일)<input type="number" name="expiresInDays" value="30" min="1" max="90" required></label><button>PAT 발급</button></form><form id="key-revoke"><label>회수할 PAT ID<input name="keyId" required></label><button>PAT 회수</button></form></details>
<details><summary>삭제·보존·내보내기</summary><form id="retention-form"><label>휴지통 복원 가능 일수<input name="days" type="number" min="1" max="3650" value="30" required></label><button>복원 기간 저장</button></form><p id="retention-status"></p><p>영구 제거는 현재 DB의 본문·이력을 제거합니다. 검색 인덱스 정리와 백업 만료는 별도 수명주기를 따릅니다.</p><button id="export">JSON 내보내기</button><button id="rebuild">검색 인덱스 재생성</button><button id="jobs">작업 상태 조회</button><form id="job-retry"><label>실패 작업 ID<input name="jobId" required></label><button>재시도</button></form></details>
</section></div>
<div class="grid"><section><h2>대화에서 추출</h2><form id="ingest-form"><label>대화 JSON 배열<textarea name="messages" rows="6" required placeholder='[{"id":"m1","role":"user","content":"기억할 사실"}]'></textarea></label><button>추출 제안 만들기</button></form><button id="ingests">추출 작업 새로고침</button><div id="proposals"></div><p>추출 모델이 만든 내용은 사실 확정이 아닙니다. 원문 인용을 확인하고 저장할 항목만 승인하세요.</p>
<details><summary>승인 기반 읽기 공유</summary><form id="share-form"><label>이미 가입·확인된 수신 이메일<input type="email" name="email" required></label><label>유효 일수<input type="number" name="days" min="1" max="30" value="7"></label><button>공유 제안</button></form><button id="invitations">받은 공유 제안</button><div id="shares"></div><form id="share-revoke"><label>공유 ID<input name="shareId" required></label><button>공유 회수</button></form></details></section>
<section><h2>도메인·조직 관리</h2><form id="domain-start"><label>관리할 정확한 도메인<input name="domain" placeholder="example.com" required></label><button>DNS TXT 확인값 만들기</button></form><form id="domain-verify"><label>Domain challenge ID<input name="challengeId" required></label><button>DNS 소유권 확인</button></form><form id="domain-delegate"><label>Domain ID<input name="domainId" required></label><label>위임할 멤버십 ID<input name="membershipId" required></label><button>도메인 관리자 위임</button></form><form id="domain-revoke"><label>Domain ID<input name="domainId" required></label><label>회수할 이메일<input type="email" name="email" required></label><button>해당 주소의 서비스 접근 회수</button></form><p>도메인 검증은 30일 동안 유효합니다. 상위 조직의 권한은 하위 조직에 자동 상속되지 않습니다.</p><details><summary>SCIM 회수 연동</summary><button id="scim-key">조직 SCIM 키 발급</button><p>현재는 목록·비활성화 전용입니다. 사용자 생성·수정 전체를 지원하는 SCIM 구현은 아닙니다.</p></details>
<details><summary>결제</summary><form id="checkout-form"><label>상품<select name="priceId" id="prices"></select></label><button>구독 결제</button></form><button id="portal">구독·결제 관리</button><p>사용량은 조직 공동으로 합산됩니다. 제공자 토큰 사용량과 다른 서비스 단위이며 매월 UTC 기준으로 초기화됩니다.</p></details></section></div>
<section id="mcp-connection"><h2>MCP 연결</h2><p>엔드포인트: <code>https://memory.allenlabs.org/mcp</code></p><p>PAT 방식: 클라이언트의 비밀 환경 변수(예: <code>MEMORY_SAAS_PAT</code>)에서 토큰을 읽어 <code>Authorization: Bearer &lt;PAT&gt;</code> 헤더로 전송하세요.</p><p>OAuth 지원 클라이언트에서는 allen.company 중앙 SSO로 연결할 수 있습니다. PAT과 OAuth 모두 서버가 현재 저장소 권한을 확인하며, PAT에 지정한 저장소·동작 범위를 넘을 수 없습니다.</p></section><section><h2>작업 결과</h2><pre id="result" tabindex="0"></pre><button id="clear-result">결과 지우기</button></section></main><footer>Release candidate · 실환경 로그인·메일·검색·결제·복원 검증 후 출시하세요.</footer></body></html>`;
export const managementStyles = String.raw `*{box-sizing:border-box}body{margin:0;background:#f5f6f8;color:#17202b;font:15px/1.6 system-ui,sans-serif}header,main,footer{max-width:1240px;margin:auto;padding:24px}header{display:flex;gap:24px;align-items:center;justify-content:space-between}header small{letter-spacing:.13em;color:#506279}h1{font-size:28px;margin:6px 0}h2{font-size:21px}nav,.toolbar{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}section{background:white;padding:22px;margin-bottom:22px;border:1px solid #dce1e8;border-radius:12px}.grid section{min-width:0}.notice{border-left:4px solid #526d82;padding:12px 16px;background:#e9eff5}label{display:block;margin:10px 0}input:not([type=checkbox]),textarea,select{width:100%;padding:9px;border:1px solid #aeb9c8;border-radius:5px;font:inherit}textarea{resize:vertical}button,a{font:inherit}button{padding:8px 13px;border:1px solid #64778e;border-radius:5px;background:#f4f7fa;cursor:pointer;margin:5px 5px 5px 0}button:hover{background:#e5edf5}button:disabled{opacity:.55;cursor:wait}form{margin:16px 0;padding-bottom:14px;border-bottom:1px solid #e5e9ef}fieldset{border:1px solid #dce1e8}fieldset label{display:inline-block;margin-right:16px}small{display:block;color:#536374}details{padding:12px 0;border-top:1px solid #dce1e8}summary{cursor:pointer;font-weight:600}.memory,.proposal{padding:16px 0;border-bottom:1px solid #dce1e8;overflow-wrap:anywhere}.memory p,.proposal p{white-space:pre-wrap}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:440px;overflow:auto;font:13px/1.6 ui-monospace,monospace}#status{min-height:24px}footer{color:#536374}@media(max-width:800px){.grid{grid-template-columns:1fr}header{display:block}header,main,footer{padding:16px}h1{font-size:24px}}`;
export const managementScript = String.raw `'use strict';
const $=id=>document.getElementById(id),pending=new Map(),drafts=new Map(),spaceMetadata=new Map();let workspace=null,cursor=null,deleted=false,secretTimer,epoch=0,memoryEpoch=0,ingestEpoch=0,shareEpoch=0,signedOut=false,selectedSpace='';
class StaleResponse extends Error {}
function invalidate(clearPanels=false){epoch++;memoryEpoch++;ingestEpoch++;shareEpoch++;clearTimeout(secretTimer);$('result').textContent='';if(clearPanels){for(const id of ['memories','proposals','shares'])$(id).replaceChildren();cursor=null;$('more').hidden=true;}}
function draft(){return Object.fromEntries(new FormData($('add-form')));}
function restoreDraft(id){const form=$('add-form'),saved=drafts.get(id)||{};for(const name of ['body','source','supersedesMemoryId'])form.elements[name].value=saved[name]||'';}
function patSpace(){const value=spaceMetadata.get($('space').value);if(!value||(value.organizationId!==null&&typeof value.organizationId!=='string'))throw Error('메모리 저장소 정보를 새로고침하세요.');return value;}
function configureFeatures(config){const f=config.features||{};for(const [selector,enabled]of [['#ingest-form button',f.ingestion],['#rebuild',f.indexRebuild],['#checkout-form button',f.billing],['#portal',f.billing],['#reauth-start button',f.mail],['#email-start button',f.mail]]){const button=document.querySelector(selector);button.dataset.unavailable=String(!enabled);button.disabled=!enabled;}const unavailable=[];if(!f.ingestion)unavailable.push('대화 추출');if(!f.indexRebuild)unavailable.push('검색 인덱스 재생성');if(!f.billing)unavailable.push('결제');if(!f.mail)unavailable.push('확인 메일 발송');$('feature-status').textContent=unavailable.length?unavailable.join(' · ')+' 기능은 현재 사용할 수 없습니다. 메모리 저장·조회와 기본 검색은 사용할 수 있습니다.':'';$('retention-status').textContent=config.policy?.automaticErasure?'복원 기간이 지난 휴지통 기억은 정기 정리에서 영구 제거됩니다.':'자동 영구 제거가 꺼져 있습니다. 기간이 지나면 복원할 수 없으며, 본문과 이력은 직접 영구 제거할 때까지 보관됩니다.';}
function updatePatScope(){const selected=spaceMetadata.get($('space').value);if(!selected){$('pat-scope').textContent='먼저 메모리 저장소를 선택하세요.';return;}const org=workspace?.organizations.find(o=>o.id===selected.organizationId),tenant=selected.organizationId?'조직 '+(org?.name||selected.organizationId):'현재 계정의 개인 범위';$('pat-scope').textContent=$('key-form').elements.singleSpace.checked?selected.name+' 저장소만 · '+tenant:tenant+'의 모든 저장소';}
function changeSpace(){if(selectedSpace)drafts.set(selectedSpace,draft());selectedSpace=$('space').value;restoreDraft(selectedSpace);invalidate(true);updatePatScope();task(()=>memories());}
function endSession(){invalidate(true);signedOut=true;workspace=null;pending.clear();drafts.clear();spaceMetadata.clear();$('pat-scope').textContent='';for(const id of ['space','organization','email-select'])$(id).replaceChildren();for(const el of document.querySelectorAll('input,textarea')){if(el.type!=='checkbox')el.value='';}for(const el of document.querySelectorAll('form button,input,textarea,select'))el.disabled=true;}
const space=()=>{if(!$('space').value)throw Error('Space를 선택하세요.');return encodeURIComponent($('space').value);};const organization=()=>{if(!$('organization').value)throw Error('조직을 선택하세요.');return encodeURIComponent($('organization').value);};
function result(value){$('result').textContent=typeof value==='string'?value:JSON.stringify(value,null,2);clearTimeout(secretTimer);if(value&&typeof value==='object'&&'token'in value)secretTimer=setTimeout(()=>$('result').textContent='키 표시 시간이 종료되었습니다.',60000);}
async function api(path,method='GET',data){const generation=epoch;if(signedOut)throw new StaleResponse();const res=await fetch(path,{method,credentials:'same-origin',headers:{accept:'application/json',...(data===undefined?{}:{'content-type':'application/json'})},...(data===undefined?{}:{body:JSON.stringify(data)})});const text=await res.text();if(generation!==epoch||signedOut)throw new StaleResponse();if(res.status===401){endSession();$('status').textContent='로그인이 만료되었습니다. 다시 로그인하세요.';throw new StaleResponse();}let value;try{value=text?JSON.parse(text):null;}catch{throw Error('서버 응답을 확인할 수 없습니다.');}if(!res.ok)throw Error((value&&value.error)||('HTTP '+res.status));return value;}
async function task(fn){const generation=epoch;if(signedOut)return;$('status').textContent='처리 중';try{await fn();if(generation===epoch&&!signedOut)$('status').textContent='완료';}catch(e){if(e instanceof StaleResponse||generation!==epoch||signedOut)return;$('status').textContent=e.message;result({error:e.message});}}
function operation(name,data){const fingerprint=JSON.stringify(data),old=pending.get(name);if(old&&old.fingerprint===fingerprint)return old.id;const id=crypto.randomUUID();pending.set(name,{id,fingerprint});return id;}
function form(name,fn){const el=$(name);el.addEventListener('submit',e=>{e.preventDefault();const button=el.querySelector('button');button.disabled=true;task(async()=>{await fn(Object.fromEntries(new FormData(el)),el);}).finally(()=>{if(!signedOut)button.disabled=button.dataset.unavailable==='true';});});}
function click(id,fn){$(id).addEventListener('click',()=>task(fn));}function option(el,value,label){const n=document.createElement('option');n.value=value;n.textContent=label;el.append(n);}function text(el,tag,value){const n=document.createElement(tag);n.textContent=value;el.append(n);return n;}function action(el,label,fn){const b=document.createElement('button');b.textContent=label;b.addEventListener('click',()=>task(fn));el.append(b);}
async function load(){const next=await api('/v1/workspace');if(workspace&&workspace.account.id!==next.account.id){invalidate(true);pending.clear();drafts.clear();spaceMetadata.clear();selectedSpace='';deleted=false;for(const form of document.forms)form.reset();for(const id of ['space','organization','email-select','prices'])$(id).replaceChildren();return task(()=>loadWorkspace(next));}await loadWorkspace(next);}
async function loadWorkspace(nextWorkspace){workspace=nextWorkspace;$('email-select').replaceChildren();for(const e of workspace.account.emails)option($('email-select'),e.id,e.address+' · '+e.id);$('organization').replaceChildren();option($('organization'),'','개인');for(const o of workspace.organizations)option($('organization'),o.id,o.name+' · '+o.role);const old=$('space').value;$('space').replaceChildren();spaceMetadata.clear();let next=null;do{const page=await api('/v1/spaces?limit=100'+(next?'&cursor='+encodeURIComponent(next):''));for(const s of page.results){spaceMetadata.set(s.id,s);option($('space'),s.id,s.name+' · '+s.id);}next=page.nextCursor;}while(next);if([...$('space').options].some(o=>o.value===old))$('space').value=old;const config=await api('/v1/release/config');configureFeatures(config);$('prices').replaceChildren();for(const [id,p]of Object.entries(config.prices))option($('prices'),id,p.plan+' · '+p.monthlyUnits+' units/month');if(selectedSpace)drafts.set(selectedSpace,draft());selectedSpace=$('space').value;restoreDraft(selectedSpace);updatePatScope();if(selectedSpace)await memories();}
async function memories(next=false){const generation=++memoryEpoch;if(!next){cursor=null;$('memories').replaceChildren();}const page=await api('/v1/spaces/'+space()+'/memories?limit=25&deleted='+deleted+(cursor?'&cursor='+encodeURIComponent(cursor):''));if(generation!==memoryEpoch)throw new StaleResponse();renderMemories(page.results);cursor=page.nextCursor;$('more').hidden=!cursor;}
function renderMemories(items){for(const m of items){const card=document.createElement('article');card.className='memory';text(card,'small',m.id+' · revision '+m.revision);text(card,'p',m.body);text(card,'small',JSON.stringify(m.provenance||{}));if(m.deletedAt){action(card,'복원',async()=>{result(await api('/v1/spaces/'+space()+'/memories/'+encodeURIComponent(m.id)+'/restore','POST',{expectedRevision:m.revision,operationId:operation('restore:'+m.id,{revision:m.revision})}));await memories();});action(card,'영구 제거',async()=>{const confirmation=prompt('현재 본문과 모든 이력을 영구 제거합니다. 확인하려면 기억 ID를 입력하세요.', '');if(confirmation!==m.id)return;result(await api('/v1/spaces/'+space()+'/memories/'+encodeURIComponent(m.id)+'/erase','POST',{expectedRevision:m.revision,confirmation,operationId:operation('erase:'+m.id,{revision:m.revision})}));await memories();});}else{action(card,'수정',async()=>{const body=prompt('기억 본문 수정',m.body);if(body===null)return;const input={body,expectedRevision:m.revision};result(await api('/v1/spaces/'+space()+'/memories/'+encodeURIComponent(m.id),'PATCH',{...input,operationId:operation('edit:'+m.id,input)}));await memories();});action(card,'휴지통',async()=>{if(!confirm('이 기억을 휴지통으로 이동할까요?'))return;result(await api('/v1/spaces/'+space()+'/memories/'+encodeURIComponent(m.id),'DELETE',{expectedRevision:m.revision,operationId:operation('delete:'+m.id,{revision:m.revision})}));await memories();});}$('memories').append(card);}}
$('reload').addEventListener('click',()=>{invalidate(true);task(load);});$('logout').addEventListener('click',async()=>{endSession();$('status').textContent='로그아웃 중';try{const response=await fetch('/auth/logout',{method:'POST',credentials:'same-origin'});if(!response.ok)throw Error('logout_failed');location.assign('/manage');}catch{$('status').textContent='로그아웃 요청을 완료하지 못했습니다. 다시 시도하세요.';}});click('refresh-memories',async()=>{deleted=false;await memories();});click('trash',async()=>{deleted=true;await memories();});click('more',()=>memories(true));$('space').addEventListener('change',changeSpace);$('key-form').elements.singleSpace.addEventListener('change',updatePatScope);$('organization').addEventListener('change',()=>invalidate(true));click('clear-result',()=>invalidate());
form('add-form',async(d,el)=>{const selected=space(),submitted=JSON.stringify(d);const input={body:d.body,...(d.source?{source:d.source}:{}),...(d.supersedesMemoryId?{supersedesMemoryId:d.supersedesMemoryId}:{})};result(await api('/v1/spaces/'+space()+'/memories','POST',{...input,operationId:operation('add:'+space(),input)}));pending.delete('add:'+selected);if(JSON.stringify(draft())===submitted){el.reset();drafts.delete(decodeURIComponent(selected));}await memories();});
form('search-form',async d=>{const generation=++memoryEpoch;const r=await api('/v1/spaces/'+space()+'/memories?query='+encodeURIComponent(d.query));if(generation!==memoryEpoch)throw new StaleResponse();$('memories').replaceChildren();renderMemories(r.results);$('more').hidden=true;result({mode:r.mode,degradedReason:r.degradedReason});});
form('reauth-start',async d=>{const r=await api('/v1/account/reauth','POST',d);$('reauth-id').value=r.id;result(r);});form('reauth-complete',async(d,el)=>{result(await api('/v1/account/reauth/complete','POST',d));el.elements.proof.value='';});
form('email-start',async d=>{const r=await api('/v1/account/emails','POST',d);$('email-challenge').value=r.challengeId;result(r);});form('email-complete',async(d,el)=>{result(await api('/v1/account/emails/verify','POST',d));el.elements.proof.value='';await load();});form('email-unlink',async d=>{if(!confirm('종속 조직 멤버십과 키가 회수됩니다. 계속할까요?'))return;result(await api('/v1/account/emails/'+encodeURIComponent(d.emailId),'DELETE'));await load();});
form('key-form',async(d,el)=>{const caps=[...new FormData(el).getAll('cap')],selected=patSpace(),org=selected.organizationId;result(await api('/v1/keys','POST',{label:d.label,capabilities:caps,expiresInDays:Number(d.expiresInDays),...(d.singleSpace?{spaceIds:[selected.id]}:{}),...(org?{organizationId:org}:{})}));});form('key-revoke',async d=>{result(await api('/v1/keys/'+encodeURIComponent(d.keyId),'DELETE'));});
form('retention-form',async d=>result(await api('/v1/spaces/'+space()+'/retention','PUT',{days:Number(d.days)})));click('usage',async()=>result(await api('/v1/spaces/'+space()+'/usage')));click('rebuild',async()=>result(await api('/v1/spaces/'+space()+'/index/rebuild','POST',{})));click('jobs',async()=>result(await api('/v1/spaces/'+space()+'/jobs')));form('job-retry',async d=>result(await api('/v1/spaces/'+space()+'/jobs/'+encodeURIComponent(d.jobId)+'/retry','POST',{})));
click('export',async()=>{const s=space(),session=await api('/v1/spaces/'+s+'/exports','POST',{}),records=[];let cursor=null;do{const page=await api('/v1/spaces/'+s+'/exports/'+encodeURIComponent(session.id)+(cursor?'?cursor='+encodeURIComponent(cursor):''));records.push(...page.results);cursor=page.nextCursor;}while(cursor);const blob=new Blob([JSON.stringify({format:'memory-export-v1',spaceId:decodeURIComponent(s),memories:records},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='memory-export-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);result({exported:records.length});});
form('ingest-form',async d=>{const input={messages:JSON.parse(d.messages)};result(await api('/v1/spaces/'+space()+'/ingests','POST',{...input,operationId:operation('ingest:'+space(),input)}));});
click('ingests',async()=>{const generation=++ingestEpoch;$('proposals').replaceChildren();const s=space(),page=await api('/v1/spaces/'+s+'/ingests');if(generation!==ingestEpoch)throw new StaleResponse();for(const job of page.results){const card=document.createElement('article');card.className='proposal';text(card,'small',job.id+' · '+job.state);if(job.state==='review'){const review=await api('/v1/spaces/'+s+'/ingests/'+encodeURIComponent(job.id)),checks=[];if(generation!==ingestEpoch)throw new StaleResponse();review.proposals.forEach((p,index)=>{const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=true;checks.push(check);label.append(check,document.createTextNode(p.body));card.append(label);text(card,'small','근거 ['+p.sourceMessageId+']: '+p.quote);});action(card,'선택 항목 승인',async()=>{const selected=checks.flatMap((c,i)=>c.checked?[i]:[]);result(await api('/v1/spaces/'+s+'/ingests/'+encodeURIComponent(job.id)+'/approve','POST',{selected,operationId:operation('approve:'+job.id,selected)}));card.replaceChildren();text(card,'p','승인 완료');});}if(['queued','review'].includes(job.state))action(card,'취소 및 원문 제거',async()=>{result(await api('/v1/spaces/'+s+'/ingests/'+encodeURIComponent(job.id),'DELETE'));card.replaceChildren();text(card,'p','취소 완료');});$('proposals').append(card);}});
form('share-form',async d=>result(await api('/v1/spaces/'+space()+'/shares','POST',{email:d.email,days:Number(d.days)})));form('share-revoke',async d=>result(await api('/v1/spaces/'+space()+'/shares/'+encodeURIComponent(d.shareId),'DELETE')));click('invitations',async()=>{const generation=++shareEpoch;$('shares').replaceChildren();const page=await api('/v1/shares');if(generation!==shareEpoch)throw new StaleResponse();for(const invite of page.results){const row=document.createElement('div');text(row,'p',JSON.stringify(invite));action(row,'읽기 공유 수락',async()=>{result(await api('/v1/shares/'+encodeURIComponent(invite.id)+'/accept','POST',{}));await load();});$('shares').append(row);}});
form('domain-start',async d=>result(await api('/v1/organizations/'+organization()+'/domains','POST',d)));form('domain-verify',async d=>result(await api('/v1/domains/verify','POST',d)));form('domain-delegate',async d=>result(await api('/v1/domains/'+encodeURIComponent(d.domainId)+'/delegates','POST',{membershipId:d.membershipId})));form('domain-revoke',async d=>{if(!confirm('해당 이메일의 서비스 접근을 회수할까요?'))return;result(await api('/v1/domains/'+encodeURIComponent(d.domainId)+'/emails/revoke','POST',{email:d.email}));});click('scim-key',async()=>result(await api('/v1/organizations/'+organization()+'/scim-keys','POST',{})));
form('checkout-form',async d=>{const r=await api('/v1/spaces/'+space()+'/billing/checkout','POST',{priceId:d.priceId,operationId:operation('checkout:'+space(),d)});location.assign(r.url);});click('portal',async()=>{const r=await api('/v1/spaces/'+space()+'/billing/portal','POST',{});location.assign(r.url);});
task(load);
`;
