import type { Database, Statement, Value } from './types.ts';

export type CommandCaptureScope = {
  commandType: 'email-link' | 'domain-email-revoke' | 'scim-deactivate' | 'scim-delete' | 'space-create';
  entityId: string; receiptId: string | null; actorDigest: string; commandAt: number;
  challengeId?: string; domainId?: string; address?: string; organizationId?: string | null;
};
const ISSUER='https://auth-api.allen.company';
const bytes=(v:string)=>`coalesce(length(CAST(${v} AS BLOB)),0)`;
const cost=(...v:string[])=>`6*(${v.map(bytes).join('+')})`;
const validId=(v:string)=>`(typeof(${v})='text' AND length(${v}) BETWEEN 1 AND 256 AND substr(${v},1,1) GLOB '[A-Za-z0-9]' AND ${v} NOT GLOB '*[^A-Za-z0-9._:-]*')`;
const time=(v:string)=>`(typeof(${v})='integer' AND ${v} BETWEEN 0 AND 9007199254740991)`;
const nullableTime=(v:string)=>`(${v} IS NULL OR ${time(v)})`;
const positions='positions(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM positions WHERE n<512)';
const whitespace='char(9)||char(10)||char(11)||char(12)||char(13)||char(32)||char(160)||char(5760)||char(8192)||char(8193)||char(8194)||char(8195)||char(8196)||char(8197)||char(8198)||char(8199)||char(8200)||char(8201)||char(8202)||char(8232)||char(8233)||char(8239)||char(8287)||char(12288)||char(65279)';
const subject=(p:string)=>`(typeof(${p}.subject)='text' AND length(${p}.subject) BETWEEN 1 AND 512 AND instr(${p}.subject,char(0))=0 AND length(trim(${p}.subject,${whitespace}))>0
 AND (SELECT sum(CASE WHEN unicode(substr(${p}.subject,n,1))>65535 THEN 2 ELSE 1 END) FROM positions WHERE n<=length(${p}.subject))<=512
 AND NOT EXISTS(SELECT 1 FROM positions WHERE n<=length(${p}.subject) AND (unicode(substr(${p}.subject,n,1)) BETWEEN 55296 AND 57343 OR hex(CAST(char(unicode(substr(${p}.subject,n,1))) AS BLOB))<>hex(CAST(substr(${p}.subject,n,1) AS BLOB)))))`;
const uuid=`lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-8'||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6)))`;
const credentialCost=`4096+${cost('c.id','c.account_id','c.membership_id','c.email_id','p.capabilities','p.space_ids')}`;
const memberCost=`4096+${cost('m.id','m.account_id','m.email_id','m.organization_id')}`;
const policy=`(SELECT json_object('capabilities',json((SELECT json_group_array(value) FROM (SELECT DISTINCT value FROM json_each(p.capabilities) ORDER BY value COLLATE BINARY))),
 'spaceIds',CASE WHEN p.space_ids IS NULL THEN NULL ELSE json((SELECT json_group_array(value) FROM (SELECT DISTINCT value FROM json_each(p.space_ids) ORDER BY value COLLATE BINARY))) END) FROM release_credential_policies p WHERE p.credential_id=c.id)`;
function state():string {
 return `CASE k.stream_kind
 WHEN 'membership' THEN (SELECT json_object('version',3,'kind','membership-source','id',m.id,'organizationId',m.organization_id,'accountId',m.account_id,'emailId',m.email_id,'role',m.role,'expiresAtMs',m.expires_at,'revokedAtMs',m.revoked_at) FROM memberships m WHERE m.id=k.entity_id)
 WHEN 'credential' THEN (SELECT json_object('version',3,'kind','credential-source','id',c.id,'accountId',c.account_id,'credentialKind',c.kind,'tokenDigest',c.token_digest,'membershipId',c.membership_id,'emailId',c.email_id,'permission',c.permission,'expiresAtMs',c.expires_at,'revokedAtMs',c.revoked_at,'policy',json(${policy})) FROM credentials c WHERE c.id=k.entity_id AND c.kind IN ('personal_key','api_key'))
 WHEN 'space' THEN (SELECT json_object('version',3,'kind','space-source','id',s.id,'accountId',s.account_id,'organizationId',s.organization_id,'securityMode',s.security_mode,'createdAtMs',s.created_at) FROM spaces s WHERE s.id=k.entity_id)
 WHEN 'email' THEN (SELECT json_object('version',3,'kind','email-source','issuer',k.issuer,'subject',k.subject,'address',k.address,'accountId',a.account_id,
  'liveClaim',json((SELECT json_object('id',e.id,'verifiedAtMs',e.verified_at) FROM account_emails e WHERE e.address=k.address AND e.account_id=a.account_id AND e.revoked_at IS NULL)),
  'changedClaim',NULL,'addressBlocked',json(CASE WHEN EXISTS(SELECT 1 FROM email_blocks b WHERE b.address=k.address) OR EXISTS(SELECT 1 FROM release_external_email_blocks b WHERE b.account_id=a.account_id AND b.address=k.address) THEN 'true' ELSE 'false' END),
  'legacyRevoked',json(CASE WHEN EXISTS(SELECT 1 FROM release_provider_revocations r WHERE r.issuer=k.issuer AND r.subject=k.subject AND r.kind='email.revoked' AND r.address=k.address) THEN 'true' ELSE 'false' END),
  'lifecycle',json(coalesce((SELECT json_object('state','event','eventId',l.event_id,'sequence',l.sequence,'kind',l.kind,'occurredAtMs',l.occurred_at) FROM release_identity_lifecycle_state l WHERE l.issuer=k.issuer AND l.subject=k.subject AND l.address=k.address),' {"state":"absent"}')))
  FROM release_seoul_command_attempts a WHERE a.id=k.attempt_id) END`;
}

/** Trusted same-database composition: staging surrounds the unchanged command. */
export function commandStatements(database:Database, scope:CommandCaptureScope, command:Statement):{statements:Statement[];commandIndex:number} {
 const attempt=crypto.randomUUID(),statements:Statement[]=[];
 const add=(sql:string,values:Value[]=[attempt])=>statements.push(database.prepare(sql).bind(...values));
 const link=scope.commandType==='email-link',domain=scope.commandType==='domain-email-revoke',space=scope.commandType==='space-create',deletion=scope.commandType==='scim-delete';
 const scim=!link&&!domain&&!space;
 add(`INSERT INTO release_seoul_command_attempts(id,command_kind,receipt_id,entity_id,actor_id,challenge_id,domain_id,address,organization_id,scim_key_id,command_at)
 VALUES(?,?,?,?,(SELECT id FROM credentials WHERE token_digest=?),?,?,?,?,(SELECT id FROM release_scim_keys WHERE token_digest=?),?)`,[attempt,scope.commandType,scope.receiptId,scope.entityId,scope.actorDigest,scope.challengeId??null,scope.domainId??null,scope.address??null,scope.organizationId??null,scope.actorDigest,scope.commandAt]);
 if(link)add(`UPDATE release_seoul_command_attempts AS a SET account_id=(SELECT account_id FROM email_challenges WHERE id=a.challenge_id),address=(SELECT address FROM email_challenges WHERE id=a.challenge_id),email_id=entity_id,receipt_before=EXISTS(SELECT 1 FROM email_consumptions WHERE id=a.receipt_id),entity_before=EXISTS(SELECT 1 FROM account_emails WHERE id=a.entity_id) WHERE id=?`);
 else if(domain){
  // Global partial unique index bounds this lookup to the sole live claim.
  add(`UPDATE release_seoul_command_attempts AS a SET account_id=(SELECT account_id FROM account_emails WHERE address=a.address AND revoked_at IS NULL),email_id=(SELECT id FROM account_emails WHERE address=a.address AND revoked_at IS NULL),receipt_before=EXISTS(SELECT 1 FROM revocations WHERE id=a.receipt_id) WHERE id=?`);
 }else if(scim)add(`UPDATE release_seoul_command_attempts AS a SET account_id=(SELECT account_id FROM memberships WHERE id=a.entity_id AND organization_id=a.organization_id),email_id=(SELECT email_id FROM memberships WHERE id=a.entity_id AND organization_id=a.organization_id),receipt_before=EXISTS(SELECT 1 FROM release_scim_deletions WHERE membership_id=a.entity_id),member_was_live=EXISTS(SELECT 1 FROM memberships WHERE id=a.entity_id AND organization_id=a.organization_id AND revoked_at IS NULL) WHERE id=?`);
 else add(`UPDATE release_seoul_command_attempts AS a SET account_id=(SELECT account_id FROM credentials WHERE id=a.actor_id),entity_before=EXISTS(SELECT 1 FROM spaces WHERE id=a.entity_id) WHERE id=?`);
 if(scim)add(`UPDATE release_seoul_command_attempts AS a SET address=(SELECT address FROM account_emails WHERE id=a.email_id) WHERE id=?`);
 add(`WITH RECURSIVE ${positions}, bounded AS (SELECT p.* FROM provider_identities p JOIN release_seoul_command_attempts a ON a.account_id=p.account_id WHERE a.id=? LIMIT 513)
 UPDATE release_seoul_command_attempts AS a SET identity_count=(SELECT count(*) FROM bounded),identity_bytes=coalesce((SELECT sum(256+${cost('p.issuer','p.subject','p.account_id')}) FROM bounded p),0),
 anchor_subject=(SELECT p.subject FROM (SELECT p.* FROM provider_identities p WHERE p.account_id=a.account_id AND p.issuer='${ISSUER}' LIMIT 513) p WHERE ${subject('p')} ORDER BY p.subject COLLATE BINARY LIMIT 1),
 exclusion_reason=CASE WHEN a.account_id IS NULL THEN 'unmapped' WHEN NOT ${validId('a.account_id')} THEN 'unsupported-state' WHEN NOT EXISTS(SELECT 1 FROM bounded) THEN 'unmapped' WHEN (SELECT count(*) FROM bounded)>512 THEN 'identity-count'
 WHEN EXISTS(SELECT 1 FROM bounded p WHERE p.issuer<>'${ISSUER}' OR NOT ${subject('p')} OR NOT ${time('p.created_at')}) THEN 'unsupported-mapping' ELSE (SELECT reason FROM release_seoul_account_exclusions x WHERE x.account_id=a.account_id) END WHERE a.id=?`,[attempt,attempt]);
 const members=domain?'m.email_id=a.email_id AND m.revoked_at IS NULL':'m.id=a.entity_id AND m.account_id=a.account_id AND m.organization_id=a.organization_id AND m.revoked_at IS NULL';
 const credentials=domain?"c.email_id=a.email_id AND c.revoked_at IS NULL AND c.kind='api_key'":"c.membership_id=a.entity_id AND c.revoked_at IS NULL AND c.kind='api_key'";
 add(`UPDATE release_seoul_command_attempts AS a SET membership_count=${domain||scim?`(SELECT count(*) FROM (SELECT id FROM memberships m WHERE ${members} LIMIT 513))`:'0'},credential_count=${domain||scim?`(SELECT count(*) FROM (SELECT id FROM credentials c WHERE ${credentials} LIMIT 513))`:'0'} WHERE id=? AND exclusion_reason IS NULL`);
 add(`UPDATE release_seoul_command_attempts SET source_count=${link||domain?'identity_count+':'0+'}membership_count+credential_count+${space?'1':'0'},exclusion_reason=CASE WHEN identity_bytes+8192>131072 THEN 'identity-bytes' WHEN identity_count+${link||domain?'identity_count+':''}membership_count+credential_count+${space?'1':'0'}>512 THEN 'fanout-count' END WHERE id=? AND exclusion_reason IS NULL`);
 const spaces=space?'SELECT a.entity_id id':link?'SELECT s.id FROM spaces s WHERE s.account_id=a.account_id':domain?`SELECT s.id FROM spaces s WHERE s.account_id=a.account_id UNION ALL SELECT s.id FROM memberships m JOIN spaces s ON s.organization_id=m.organization_id WHERE ${members}`:'SELECT s.id FROM spaces s WHERE s.organization_id=a.organization_id';
 add(`UPDATE release_seoul_command_attempts AS a SET space_count=(SELECT count(*) FROM (SELECT DISTINCT id FROM (${spaces}) LIMIT 513)) WHERE id=? AND exclusion_reason IS NULL`);
 add(`UPDATE release_seoul_command_attempts AS a SET exclusion_reason=CASE WHEN space_count>512 THEN 'fanout-count' WHEN EXISTS(SELECT 1 FROM (${spaces}) s WHERE length(s.id)>128 OR NOT ${validId('s.id')}) THEN 'unsupported-state' END WHERE id=? AND exclusion_reason IS NULL`);
 add(`UPDATE release_seoul_command_attempts AS a SET largest_source=max(8192+identity_bytes+${cost('a.address','a.email_id','a.entity_id','a.account_id','a.organization_id')},${domain||scim?`coalesce((SELECT max(${credentialCost}) FROM credentials c LEFT JOIN release_credential_policies p ON p.credential_id=c.id WHERE ${credentials}),0),coalesce((SELECT max(${memberCost}) FROM memberships m WHERE ${members}),0)`:'0'}) WHERE id=? AND exclusion_reason IS NULL`);
 add(`UPDATE release_seoul_command_attempts SET source_bytes=source_count*largest_source,exclusion_reason=CASE WHEN largest_source>131072 OR source_count*largest_source>524288 THEN 'source-bytes' END WHERE id=? AND exclusion_reason IS NULL`);
 add(`UPDATE release_seoul_command_attempts AS a SET exclusion_reason='unsupported-state' WHERE id=? AND exclusion_reason IS NULL AND (NOT ${validId('a.entity_id')} OR (a.organization_id IS NOT NULL AND NOT ${validId('a.organization_id')}) OR (a.email_id IS NOT NULL AND NOT ${validId('a.email_id')})
 OR EXISTS(SELECT 1 FROM account_emails e WHERE e.id=a.email_id AND (NOT ${time('e.verified_at')} OR NOT ${nullableTime('e.revoked_at')}))
 ${domain||scim?`OR EXISTS(SELECT 1 FROM memberships m WHERE ${members} AND (NOT ${validId('m.id')} OR NOT ${validId('m.account_id')} OR NOT ${validId('m.organization_id')} OR NOT ${validId('m.email_id')} OR NOT ${time('m.expires_at')} OR NOT ${nullableTime('m.revoked_at')}))
 OR EXISTS(SELECT 1 FROM credentials c LEFT JOIN release_credential_policies p ON p.credential_id=c.id WHERE ${credentials} AND (NOT ${validId('c.id')} OR NOT ${validId('c.account_id')} OR NOT ${time('c.expires_at')} OR NOT ${nullableTime('c.revoked_at')} OR NOT ${validId('c.membership_id')} OR NOT ${validId('c.email_id')}
 OR (p.credential_id IS NOT NULL AND (NOT EXISTS(SELECT 1 FROM json_each(p.capabilities)) OR EXISTS(SELECT 1 FROM json_each(p.capabilities) j WHERE j.type<>'text' OR j.value NOT IN ('create','delete','export','read','update'))
 OR (p.space_ids IS NOT NULL AND (NOT EXISTS(SELECT 1 FROM json_each(p.space_ids)) OR (SELECT count(DISTINCT value) FROM json_each(p.space_ids))>50 OR EXISTS(SELECT 1 FROM json_each(p.space_ids) j WHERE j.type<>'text' OR NOT ${validId('j.value')} OR length(j.value)>128)))))))`:''})`);
 if(!space){
  add(`WITH RECURSIVE bounded AS (SELECT address FROM release_seoul_command_attempts WHERE id=? AND exclusion_reason IS NULL AND length(CAST(address AS BLOB)) BETWEEN 3 AND 254 AND instr(address,char(0))=0),parts AS (SELECT address,substr(address,1,instr(address,'@')-1) local,substr(address,instr(address,'@')+1) domain FROM bounded),labels(label,remaining) AS (SELECT NULL,domain||'.' FROM parts UNION ALL SELECT substr(remaining,1,instr(remaining,'.')-1),substr(remaining,instr(remaining,'.')+1) FROM labels WHERE remaining<>'')
  UPDATE release_seoul_command_attempts SET exclusion_reason='unsupported-state' WHERE id=? AND exclusion_reason IS NULL AND NOT EXISTS(SELECT 1 FROM parts WHERE address=lower(trim(address)) AND instr(address,'@')>1 AND instr(domain,'@')=0 AND length(local) BETWEEN 1 AND 64 AND local NOT GLOB '*[^a-z0-9!#$%&''*+/=?^_\`{|}~.-]*' AND substr(local,1,1)<>'.' AND substr(local,-1)<>'.' AND instr(local,'..')=0 AND length(domain)<=253 AND instr(domain,'.')>0 AND domain NOT GLOB '*[^a-z0-9.-]*' AND NOT EXISTS(SELECT 1 FROM labels WHERE label IS NOT NULL AND (length(label) NOT BETWEEN 1 AND 63 OR substr(label,1,1) NOT GLOB '[a-z0-9]' OR substr(label,-1) NOT GLOB '[a-z0-9]')))`,[attempt,attempt]);
  add(`UPDATE release_seoul_command_attempts AS a SET exclusion_reason='unsupported-state' WHERE id=? AND exclusion_reason IS NULL AND EXISTS(SELECT 1 FROM provider_identities p WHERE p.account_id=a.account_id AND ${bytes('p.issuer')}+1+${bytes('p.subject')}+1+${bytes('a.address')}>2048)`);
 }
 if(link||domain)add(`INSERT INTO release_seoul_command_scope(attempt_id,stream_kind,stream_key,issuer,subject,address) SELECT a.id,'email',p.issuer||char(10)||p.subject||char(10)||a.address,p.issuer,p.subject,a.address FROM release_seoul_command_attempts a JOIN provider_identities p ON p.account_id=a.account_id WHERE a.id=? AND a.exclusion_reason IS NULL`);
 if(domain||scim){
  add(`INSERT INTO release_seoul_command_scope(attempt_id,stream_kind,stream_key,entity_id) SELECT a.id,'membership',m.id,m.id FROM release_seoul_command_attempts a JOIN memberships m ON ${members} WHERE a.id=? AND a.exclusion_reason IS NULL`);
  add(`INSERT INTO release_seoul_command_scope(attempt_id,stream_kind,stream_key,entity_id) SELECT a.id,'credential',c.id,c.id FROM release_seoul_command_attempts a JOIN credentials c ON ${credentials} WHERE a.id=? AND a.exclusion_reason IS NULL`);
 }
 if(space)add(`INSERT INTO release_seoul_command_scope(attempt_id,stream_kind,stream_key,entity_id) SELECT id,'space',entity_id,entity_id FROM release_seoul_command_attempts WHERE id=? AND exclusion_reason IS NULL`);
 add(`UPDATE release_seoul_command_attempts AS a SET exclusion_reason='unsupported-state' WHERE id=? AND exclusion_reason IS NULL AND EXISTS(SELECT 1 FROM release_seoul_command_scope k JOIN release_identity_lifecycle_state l ON l.issuer=k.issuer AND l.subject=k.subject AND l.address=k.address WHERE k.attempt_id=a.id AND (NOT ${validId('l.event_id')} OR NOT ${time('l.sequence')} OR l.sequence<1 OR NOT ${time('l.occurred_at')}))`);
 add(`INSERT INTO release_seoul_command_spaces(attempt_id,space_id) SELECT a.id,s.id FROM release_seoul_command_attempts a JOIN (${space?'SELECT entity_id id,id attempt_id FROM release_seoul_command_attempts':'SELECT id FROM spaces'}) s ON ${space?'s.attempt_id=a.id':`s.id IN (${spaces})`} WHERE a.id=? AND a.exclusion_reason IS NULL ${space?'':`AND (EXISTS(SELECT 1 FROM release_seoul_targets t WHERE t.space_id=s.id AND t.selected=1) OR EXISTS(SELECT 1 FROM release_seoul_dirty_spaces d WHERE d.space_id=s.id))`}`);
 add(`UPDATE release_seoul_command_scope AS k SET before_bytes=${state()} WHERE attempt_id=? AND EXISTS(SELECT 1 FROM release_seoul_command_attempts a WHERE a.id=k.attempt_id AND a.exclusion_reason IS NULL)`);
 const commandIndex=statements.length;statements.push(command);
 const accepted=link?`a.receipt_before=0 AND a.entity_before=0 AND EXISTS(SELECT 1 FROM email_consumptions r JOIN email_challenges p ON p.id=r.challenge_id JOIN account_emails e ON e.id=r.id WHERE r.id=a.receipt_id AND r.challenge_id=a.challenge_id AND r.actor_credential_id=a.actor_id AND r.created_at=a.command_at AND p.account_id=a.account_id AND p.address=a.address AND p.used_at=a.command_at AND e.account_id=a.account_id AND e.address=a.address AND e.verified_at=a.command_at AND e.revoked_at IS NULL)`:
 domain?`a.receipt_before=0 AND EXISTS(SELECT 1 FROM revocations r JOIN email_blocks b ON b.address=r.address WHERE r.id=a.receipt_id AND r.kind='domain' AND r.domain_id=a.domain_id AND r.address=a.address AND r.actor_credential_id=a.actor_id AND r.created_at=a.command_at)`:
 deletion?`a.member_was_live=1 AND a.receipt_before=0 AND EXISTS(SELECT 1 FROM release_scim_deletions d WHERE d.membership_id=a.entity_id AND d.scim_key_id=a.scim_key_id AND d.deleted_at=a.command_at)`:
 space?`a.entity_before=0 AND EXISTS(SELECT 1 FROM spaces s WHERE s.id=a.entity_id AND s.account_id IS CASE WHEN a.organization_id IS NULL THEN a.account_id ELSE NULL END AND s.organization_id IS a.organization_id AND s.security_mode='managed' AND s.created_at=a.command_at AND s.actor_credential_id=a.actor_id)`:
 `a.member_was_live=1 AND EXISTS(SELECT 1 FROM memberships m WHERE m.id=a.entity_id AND m.account_id=a.account_id AND m.organization_id=a.organization_id AND m.email_id=a.email_id AND m.revoked_at=a.command_at)`;
 add(`UPDATE release_seoul_command_attempts AS a SET accepted=CASE WHEN ${accepted} THEN 1 ELSE 0 END WHERE id=?`);
 add(`UPDATE release_seoul_command_scope AS k SET after_bytes=${state()} WHERE attempt_id=? AND EXISTS(SELECT 1 FROM release_seoul_command_attempts a WHERE a.id=k.attempt_id AND a.accepted=1 AND a.exclusion_reason IS NULL)`);
 add(`INSERT INTO release_seoul_account_exclusions(account_id,reason,capture_attempt_id,count_lower_bound,byte_estimate,captured_at) SELECT account_id,exclusion_reason,id,min(2049,identity_count+membership_count+credential_count+space_count),max(identity_bytes,source_bytes),captured_at FROM release_seoul_command_attempts a WHERE id=? AND accepted=1 AND exclusion_reason IS NOT NULL AND EXISTS(SELECT 1 FROM accounts WHERE id=a.account_id) AND NOT EXISTS(SELECT 1 FROM release_seoul_account_exclusions x WHERE x.account_id=a.account_id)`);
 add(`INSERT INTO release_seoul_authority_changes(source_command_id,stream_kind,stream_key,event_id,record_bytes,created_at) SELECT id,'subject','${ISSUER}'||char(10)||anchor_subject,${uuid},json_object('version',3,'kind','subject-source-unrepresentable','issuer','${ISSUER}','subject',anchor_subject,'accountId',account_id,'reason',exclusion_reason,'countLowerBound',min(2049,identity_count+membership_count+credential_count+space_count),'byteEstimate',max(identity_bytes,source_bytes),'captureAttemptId',id),captured_at FROM release_seoul_command_attempts WHERE id=? AND accepted=1 AND exclusion_reason IS NOT NULL AND anchor_subject IS NOT NULL AND ${validId('account_id')}`);
 add(`INSERT INTO release_seoul_authority_changes(source_command_id,stream_kind,stream_key,event_id,record_bytes,created_at)
 SELECT a.id,k.stream_kind,k.stream_key,${uuid},json_set(${domain?`CASE WHEN k.stream_kind='email' THEN json_set(k.after_bytes,'$.changedClaim',json((SELECT json_object('id',e.id,'verifiedAtMs',e.verified_at,'revokedAtMs',e.revoked_at) FROM account_emails e WHERE e.id=a.email_id AND e.revoked_at IS NOT NULL))) ELSE k.after_bytes END`:'k.after_bytes'},'$.origin',json_object('kind','command','commandType',a.command_kind,'receiptId',a.receipt_id),'$.effect',json(CASE WHEN k.stream_kind IN ('membership','credential') THEN json_object('type','entity-negative','entityKind',k.stream_kind,'entityId',k.entity_id,'state','revoked','occurredAtMs',json_extract(k.after_bytes,'$.revokedAtMs')) ELSE json_object('type','entity-head','disposition','changed') END)),a.captured_at
 FROM release_seoul_command_scope k JOIN release_seoul_command_attempts a ON a.id=k.attempt_id WHERE a.id=? AND a.accepted=1 AND a.exclusion_reason IS NULL AND k.after_bytes IS NOT NULL AND k.before_bytes IS NOT k.after_bytes AND (k.stream_kind IN ('email','space') OR (k.before_bytes IS NOT NULL AND json_extract(k.before_bytes,'$.revokedAtMs') IS NULL AND json_extract(k.after_bytes,'$.revokedAtMs') IS NOT NULL)) ORDER BY k.stream_kind COLLATE BINARY,k.stream_key COLLATE BINARY`);
 add(`INSERT INTO release_seoul_dirty_spaces(space_id,dirty_revision,captured_revision) SELECT s.space_id,(SELECT max(revision) FROM release_seoul_authority_changes WHERE source_command_id=a.id),coalesce((SELECT d.captured_revision FROM release_seoul_dirty_spaces d WHERE d.space_id=s.space_id),0) FROM release_seoul_command_spaces s JOIN release_seoul_command_attempts a ON a.id=s.attempt_id WHERE a.id=? AND a.accepted=1 AND a.exclusion_reason IS NULL AND EXISTS(SELECT 1 FROM release_seoul_authority_changes WHERE source_command_id=a.id) ON CONFLICT(space_id) DO UPDATE SET dirty_revision=max(release_seoul_dirty_spaces.dirty_revision,excluded.dirty_revision)`);
 add('DELETE FROM release_seoul_command_scope WHERE attempt_id=?');add('DELETE FROM release_seoul_command_spaces WHERE attempt_id=?');add('DELETE FROM release_seoul_command_attempts WHERE id=?');
 if(statements.length>100)throw new Error('seoul_command_statement_bound');return {statements,commandIndex};
}
