import type {Database,Value} from './types.ts';
import {prepareSeoulTargetManifest,prepareSeoulTargetSet} from './seoul-projection-target-manifest-codec.ts';
import {observeTargetCommands,prepareTargetPrior,prepareTargetCompletion,ownTargetCommand,TARGET_COMPLETION_FOR_S_SQL,type SeoulTargetCommand,type TargetPrior,type TargetCompletionWitness,type TargetControlObservation} from './seoul-projection-target-internal.ts';

type Ref=Readonly<{manifestId:string;generation:number}>;
type Phase='desired'|'omitted';
type StepInput=Readonly<{spaceId:string;commandId:string;expectedRevision:number|null}>;
type PageInput=Ref&Readonly<{phase:Phase;pageNo:number;afterSpaceId:string|null;steps:readonly StepInput[]}>;
type Statement=Readonly<{sql:string;values:readonly Value[];mode:'all'}>;
type CurrentStatus='planning'|'applying'|'complete'|'cancelled'|'superseded';
type ManifestStatus='invalid_input'|'manifest_conflict'|'generation_conflict'|'manifest_missing'|'superseded'|'cancelled'|'not_sealed'|'not_complete'|'page_conflict'|'target_state_invalid'|'staging_retained'|'capacity'|'request_limit'|'configuration_mismatch'|'uncertain'|'published'|'already_published'|'observed'|'planning_page'|'page_recorded'|'already_recorded'|'sealed'|'already_sealed'|'already_cancelled'|'steps'|'page_verified'|'already_verified'|'completed'|'already_completed'|'agreed'|'inventory_sealed'|'already_complete';
export type SeoulTargetManifestResult=Readonly<{status:ManifestStatus;manifestId?:string;generation?:number;currentGeneration?:number|null;currentStatus?:CurrentStatus;manifestSha256?:string;setSha256?:string;publishedAtMs?:number;completedAtMs?:number;steps?:readonly Readonly<{spaceId:string;expectedRevision:number|null;commandId?:string;selected?:boolean;operatorReference?:string;receiptPresent?:boolean;historyValid?:boolean;currentResultValid?:boolean}>[];terminal?:boolean;pageNo?:number;observedAtMs?:number}>;
export interface SeoulProjectionTargetManifest{
 publish(input:unknown):Promise<SeoulTargetManifestResult>;
 readManifest(input:unknown):Promise<SeoulTargetManifestResult>;
 readPlanningPage(input:unknown):Promise<SeoulTargetManifestResult>;
 appendPlanningPage(input:unknown):Promise<SeoulTargetManifestResult>;
 seal(input:unknown):Promise<SeoulTargetManifestResult>;
 cancel(input:unknown):Promise<SeoulTargetManifestResult>;
 readSteps(input:unknown):Promise<SeoulTargetManifestResult>;
 verifyPage(input:unknown):Promise<SeoulTargetManifestResult>;
 complete(input:unknown):Promise<SeoulTargetManifestResult>;
 observeAgreement(input:unknown):Promise<SeoulTargetManifestResult>;
}
const H='release_seoul_target_manifests',M='release_seoul_target_manifest_members',C='release_seoul_target_manifest_control',A='release_seoul_target_manifest_attempt',P='release_seoul_target_manifest_pages',S='release_seoul_target_manifest_steps';
const utf8=new TextEncoder(),refKeys=['manifestId','generation'] as const;
function own(value:unknown,keys:readonly string[]):Record<string,unknown>{
 if(!value||typeof value!=='object'||(Object.getPrototypeOf(value)!==Object.prototype&&Object.getPrototypeOf(value)!==null))throw Error();const actual=Reflect.ownKeys(value);if(actual.length!==keys.length||actual.some(k=>typeof k!=='string'||!keys.includes(k)))throw Error();const out:Record<string,unknown>={};for(const k of keys){const d=Object.getOwnPropertyDescriptor(value,k);if(!d||!d.enumerable||!('value'in d))throw Error();out[k]=d.value;}return out;
}
function array(value:unknown,max:number):readonly unknown[]{if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype||value.length>max||Reflect.ownKeys(value).length!==value.length+1)throw Error();const out:unknown[]=[];for(let i=0;i<value.length;i++){const d=Object.getOwnPropertyDescriptor(value,String(i));if(!d||!d.enumerable||!('value'in d))throw Error();out.push(d.value);}return Object.freeze(out);}
function queryRows(value:unknown,max:number):readonly unknown[]{const x=own(value,['success','results','meta']);if(x.success!==true||!x.meta||typeof x.meta!=='object')throw Error();return array(x.results,max);}
function integer(value:unknown,min=1):number{if(typeof value!=='number'||!Number.isSafeInteger(value)||Object.is(value,-0)||value<min)throw Error();return value;}
function uuid(value:unknown):string{if(typeof value!=='string'||value.length!==36||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(value))throw Error();return value;}
function id(value:unknown,max=128):string{if(typeof value!=='string'||!value.length||value.length>max||!/^[A-Za-z0-9]/.test(value)||/[^A-Za-z0-9._:-]/.test(value))throw Error();return value;}
function ref(x:Record<string,unknown>):Ref{return Object.freeze({manifestId:uuid(x.manifestId),generation:integer(x.generation)});}
function phase(x:unknown):Phase{if(x!=='desired'&&x!=='omitted')throw Error();return x;}
function cursor(x:unknown):string|null{return x===null?null:id(x);}
function list(value:unknown):readonly StepInput[]{
 if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype||value.length>32||Reflect.ownKeys(value).length!==value.length+1)throw Error();const out:StepInput[]=[];for(let i=0;i<value.length;i++){const d=Object.getOwnPropertyDescriptor(value,String(i));if(!d||!d.enumerable||!('value'in d))throw Error();const x=own(d.value,['spaceId','commandId','expectedRevision']),row=Object.freeze({spaceId:id(x.spaceId),commandId:uuid(x.commandId),expectedRevision:x.expectedRevision===null?null:integer(x.expectedRevision)});if(i&&out[i-1]!.spaceId>=row.spaceId||out.some(o=>o.commandId===row.commandId))throw Error();out.push(row);}return Object.freeze(out);
}
const statement=(sql:string,values:readonly Value[]=[]):Statement=>({sql,values,mode:'all'});
const guard=(condition:string)=>`SELECT CASE WHEN ${condition} THEN 1 ELSE abs(-9223372036854775808) END complete_guard`;
const empty=`NOT EXISTS(SELECT 1 FROM ${A} LIMIT 1) AND NOT EXISTS(SELECT 1 FROM release_seoul_target_attempt LIMIT 1)`;
const now="CAST(round(unixepoch('subsec')*1000) AS INTEGER)";
const current=`(SELECT current_generation FROM ${C} WHERE singleton=1)`;
const exactMembers=(h:string)=>`(SELECT count(*) FROM ${M} m WHERE m.generation=${h}.generation)=${h}.desired_count AND NOT EXISTS(SELECT 1 FROM json_each(${h}.manifest_bytes,'$.spaceIds') j WHERE NOT EXISTS(SELECT 1 FROM ${M} m WHERE m.generation=${h}.generation AND m.ordinal=CAST(j.key AS INTEGER)+1 AND m.space_id=j.value))`;
const pageJson=(phase:string)=>`(SELECT json_object('pageNo',page_no,'lastSpaceId',last_space_id,'cumulativeCount',cumulative_count,'terminal',terminal) FROM ${P} WHERE generation=h.generation AND phase='${phase}' ORDER BY page_no DESC LIMIT 1)`;
const OBSERVE=`WITH v(manifest_id,generation,input_bytes,manifest_sha256,set_sha256) AS (VALUES(?,?,?,?,?)) SELECT (SELECT version FROM release_meta) schema_version,${current} current_generation,
 EXISTS(SELECT 1 FROM ${A} LIMIT 1) OR EXISTS(SELECT 1 FROM release_seoul_target_attempt LIMIT 1) stage_present,
 h.generation,h.manifest_id,h.expected_generation,h.manifest_sha256,h.set_sha256,h.desired_count,h.operator_reference,h.published_at,
 CASE WHEN h.generation IS NULL THEN 0 WHEN v.input_bytes IS NULL THEN 1 ELSE h.manifest_bytes=v.input_bytes END manifest_exact,
 CASE WHEN h.generation IS NOT NULL AND ${current}>=h.generation AND ${exactMembers('h')} AND (v.input_bytes IS NULL OR h.manifest_bytes=v.input_bytes AND h.manifest_sha256=v.manifest_sha256 AND h.set_sha256=v.set_sha256) THEN 1 ELSE 0 END publication_valid,
 x.cancellation_id,x.operator_reference cancellation_reference,z.total_count,z.desired_terminal_page,z.omitted_terminal_page,
 f.completed_at,${pageJson('desired')} desired_page,${pageJson('omitted')} omitted_page,${pageJson('verify')} verify_page,${now} observed_at
 FROM v LEFT JOIN ${H} h ON h.manifest_id=v.manifest_id AND (v.generation IS NULL OR h.generation=v.generation)
 LEFT JOIN release_seoul_target_manifest_cancellations x ON x.generation=h.generation LEFT JOIN release_seoul_target_manifest_seals z ON z.generation=h.generation LEFT JOIN release_seoul_target_manifest_completions f ON f.generation=h.generation`;
const observationKeys=['schema_version','current_generation','stage_present','generation','manifest_id','expected_generation','manifest_sha256','set_sha256','desired_count','operator_reference','published_at','manifest_exact','publication_valid','cancellation_id','cancellation_reference','total_count','desired_terminal_page','omitted_terminal_page','completed_at','desired_page','omitted_page','verify_page','observed_at'] as const;
type Observation=Record<typeof observationKeys[number],string|number|null>;
function observation(value:unknown):Observation{
 const x=own(value,observationKeys);
 if(integer(x.schema_version)<35)throw Error();for(const k of ['current_generation','generation','expected_generation','total_count','desired_terminal_page','omitted_terminal_page','completed_at'] as const)if(x[k]!==null)integer(x[k],['total_count','completed_at'].includes(k)?0:1);
 for(const k of ['stage_present','manifest_exact','publication_valid'])if(x[k]!==0&&x[k]!==1)throw Error();integer(x.observed_at,0);if(x.desired_count!==null&&integer(x.desired_count,0)>1024)throw Error();
 for(const k of ['manifest_id','manifest_sha256','set_sha256','operator_reference','cancellation_id','cancellation_reference','desired_page','omitted_page','verify_page'])if(x[k]!==null&&(typeof x[k]!=='string'||utf8.encode(x[k]).length>1024))throw Error();
 if(x.manifest_id!==null)uuid(x.manifest_id);if((x.generation===null)!==(x.manifest_id===null))throw Error();
 if(x.generation===null){for(const k of ['expected_generation','manifest_sha256','set_sha256','desired_count','operator_reference','published_at','cancellation_id','cancellation_reference','total_count','desired_terminal_page','omitted_terminal_page','completed_at','desired_page','omitted_page','verify_page'])if(x[k]!==null)throw Error();}
 else{if(x.generation!==(x.expected_generation===null?1:Number(x.expected_generation)+1)||typeof x.manifest_sha256!=='string'||!(/^[0-9a-f]{64}$/).test(x.manifest_sha256)||typeof x.set_sha256!=='string'||!(/^[0-9a-f]{64}$/).test(x.set_sha256))throw Error();integer(x.published_at,0);id(x.operator_reference,256);integer(x.desired_count,0);if((x.cancellation_id===null)!==(x.cancellation_reference===null)||(x.total_count===null)!==(x.desired_terminal_page===null)||(x.total_count===null)!==(x.omitted_terminal_page===null)||x.completed_at!==null&&x.total_count===null)throw Error();if(x.cancellation_id!==null){uuid(x.cancellation_id);id(x.cancellation_reference,256);}}
 return x as Observation;
}
async function observe(database:Database,r:{manifestId:string;generation:number|null},bytes:string|null=null,manifestSha256:string|null=null,setSha256:string|null=null):Promise<Observation>{return observation(await database.withSession('first-primary').prepare(OBSERVE).bind(r.manifestId,r.generation,bytes,manifestSha256,setSha256).first());}
function state(o:Observation):CurrentStatus{return o.current_generation!==o.generation?'superseded':o.cancellation_id!==null?'cancelled':o.completed_at!==null?'complete':o.total_count!==null?'applying':'planning';}
function early(o:Observation):SeoulTargetManifestResult|null{if(o.stage_present)return {status:'staging_retained'};if(o.generation===null)return {status:'manifest_missing'};if(!o.publication_valid)return {status:'uncertain'};const s=state(o);if(s==='superseded'||s==='cancelled')return {status:s,currentStatus:s};return null;}
function result(status:ManifestStatus,o:Observation):SeoulTargetManifestResult{return Object.freeze({status,manifestId:uuid(o.manifest_id),generation:integer(o.generation),currentGeneration:o.current_generation===null?null:integer(o.current_generation),currentStatus:state(o),manifestSha256:String(o.manifest_sha256),setSha256:String(o.set_sha256),publishedAtMs:integer(o.published_at,0)});}
function currentLabel(r:Ref,c:TargetControlObservation):{currentGeneration:number|null;currentStatus:CurrentStatus}{return {currentGeneration:c.currentGeneration,currentStatus:c.currentGeneration!==r.generation||c.currentManifestId!==r.manifestId?'superseded':c.cancelled?'cancelled':c.completed?'complete':c.sealed?'applying':'planning'};}
function stage(operation:'publish'|'page'|'seal'|'cancel'|'verify'|'complete',r:Ref,extra:{expectedGeneration?:number|null;inputBytes?:string;manifestSha256?:string;setSha256?:string;phase?:Phase|'verify';pageNo?:number;afterSpaceId?:string|null;cancellationId?:string;operatorReference?:string}):{token:string;plan:Statement}{
 const token=crypto.randomUUID();return {token,plan:statement(`INSERT INTO ${A}(token,operation,manifest_id,generation,expected_generation,input_bytes,manifest_sha256,set_sha256,phase,page_no,after_space_id,cancellation_id,operator_reference,observed_generation,decided_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,${current},${now})`,[token,operation,r.manifestId,r.generation,extra.expectedGeneration??null,extra.inputBytes??null,extra.manifestSha256??null,extra.setSha256??null,extra.phase??null,extra.pageNo??null,extra.afterSpaceId??null,extra.cancellationId??null,extra.operatorReference??null])};
}
async function batch(database:Database,plans:readonly Statement[],guards:readonly number[]):Promise<readonly unknown[]>{
 if(plans.length>100||plans.some(p=>p.values.length>100||utf8.encode(p.sql).length>100000)||utf8.encode(JSON.stringify({statements:plans})).length+4096>1048576)throw Error('manifest_request_limit');
 const results=array(await database.batch(plans.map(p=>database.prepare(p.sql).bind(...p.values))),100);if(results.length!==plans.length)throw Error();
 for(let i=0;i<results.length;i++){const rows=queryRows(results[i],1);if(guards.includes(i)&&(rows.length!==1||own(rows[0],['complete_guard']).complete_guard!==1))throw Error();}
 return results;
}
const cleanup=(token:string)=>statement(`DELETE FROM ${A} WHERE token=?`,[token]);
function pageValue(o:Observation,p:Phase|'verify'):null|{pageNo:number;lastSpaceId:string|null;cumulativeCount:number;terminal:boolean}{const text=o[p+'_page' as keyof Observation];if(text===null)return null;const x=own(JSON.parse(String(text)),['pageNo','lastSpaceId','cumulativeCount','terminal']);if(x.terminal!==0&&x.terminal!==1)throw Error();return {pageNo:integer(x.pageNo),lastSpaceId:cursor(x.lastSpaceId),cumulativeCount:integer(x.cumulativeCount,0),terminal:Boolean(x.terminal)};}
function planningSql(p:Phase,after:boolean):string{return p==='desired'?`SELECT m.space_id spaceId,(SELECT revision FROM release_seoul_targets WHERE space_id=m.space_id) expectedRevision FROM ${M} m WHERE m.generation=? ${after?'AND m.space_id>?':''} ORDER BY m.space_id LIMIT 33`:`SELECT t.space_id spaceId,t.revision expectedRevision FROM release_seoul_targets t INDEXED BY release_seoul_targets_selected_space WHERE t.selected=1 ${after?'AND t.space_id>?':''} AND NOT EXISTS(SELECT 1 FROM ${M} m WHERE m.generation=? AND m.space_id=t.space_id) ORDER BY t.space_id LIMIT 33`;}
async function planningRows(database:Database,r:Ref,p:Phase,after:string|null):Promise<readonly {spaceId:string;expectedRevision:number|null}[]>{const values=p==='desired'?[r.generation,...after===null?[]:[after]]:[...after===null?[]:[after],r.generation],rows=queryRows(await database.withSession('first-primary').prepare(planningSql(p,after!==null)).bind(...values).all(),33);return rows.map(raw=>{const x=own(raw,['spaceId','expectedRevision']);return Object.freeze({spaceId:id(x.spaceId),expectedRevision:x.expectedRevision===null?null:integer(x.expectedRevision)});});}
async function stepRows(database:Database,r:Ref,after:string|null):Promise<readonly SeoulTargetCommand[]>{const sql=`SELECT command_id commandId,space_id spaceId,expected_revision expectedRevision,selected,operator_reference operatorReference FROM ${S} WHERE generation=? ${after===null?'':'AND space_id>?'} ORDER BY space_id LIMIT 33`,rows=queryRows(await database.withSession('first-primary').prepare(sql).bind(r.generation,...after===null?[]:[after]).all(),33);return rows.map(raw=>{const x=own(raw,['commandId','spaceId','expectedRevision','selected','operatorReference']);if(x.selected!==0&&x.selected!==1)throw Error();return ownTargetCommand({...x,selected:Boolean(x.selected)});});}
const priorFields=(p:TargetPrior)=>p.state==='absent'?{prior_state:'absent'}:{prior_state:'present',prior_revision:p.revision,prior_selected:Number(p.selected),prior_event_id:p.eventId,prior_source_command_id:p.sourceCommandId,prior_record_bytes:p.recordBytes,prior_created_at:p.createdAtMs,prior_source_sha256:p.sourceSha256,prior_transport_sha256:p.transportSha256,prior_payload_bytes:p.payloadBytes,prior_changed_receipt_bytes:p.changedReceiptBytes};
const proofFields=['prior_revision','prior_selected','prior_event_id','prior_source_command_id','prior_record_bytes','prior_created_at','prior_source_sha256','prior_transport_sha256','prior_payload_bytes','prior_changed_receipt_bytes','receipt_bytes'] as const;
const proofRows=`SELECT json_extract(j.value,'$.commandId') command_id,json_extract(j.value,'$.spaceId') space_id,json_extract(j.value,'$.expectedRevision') expected_revision,json_extract(j.value,'$.selected') selected,json_extract(j.value,'$.operatorReference') operator_reference,${proofFields.map(k=>`json_extract(j.value,'$.${k}') ${k}`).join(',')} FROM json_each(a.input_bytes) j`;
const completeProof=`NOT EXISTS(SELECT 1 FROM (${proofRows}) s WHERE NOT (EXISTS(SELECT 1 FROM ${S} step WHERE step.generation=a.generation AND step.space_id=s.space_id AND step.command_id=s.command_id AND step.expected_revision IS s.expected_revision AND step.selected=s.selected AND step.operator_reference=s.operator_reference) AND ${TARGET_COMPLETION_FOR_S_SQL}))`;
const selectedExact=`NOT EXISTS(SELECT 1 FROM ${M} m WHERE m.generation=h.generation AND NOT EXISTS(SELECT 1 FROM release_seoul_targets t WHERE t.space_id=m.space_id AND t.selected=1)) AND (SELECT count(*) FROM (SELECT space_id FROM release_seoul_targets INDEXED BY release_seoul_targets_selected_space WHERE selected=1 ORDER BY space_id LIMIT 1025))=h.desired_count`;
async function observePage(database:Database,r:Ref,p:Phase|'verify',pageNo:number,after:string|null,rows:readonly StepInput[]):Promise<{observation:Observation;exact:boolean;terminal:boolean|null}>{
 const sql=`WITH request(generation,phase,page_no,after_space_id,rows_bytes) AS(VALUES(?,?,?,?,?)) SELECT o.*,EXISTS(SELECT 1 FROM ${P} p WHERE p.generation=o.generation AND p.phase=request.phase AND p.page_no=request.page_no AND p.after_space_id IS request.after_space_id AND p.row_count=json_array_length(request.rows_bytes) AND p.last_space_id IS CASE WHEN p.row_count=0 THEN NULL ELSE json_extract(request.rows_bytes,'$['||(p.row_count-1)||'].spaceId') END AND (p.phase='verify' OR ((SELECT count(*) FROM ${S} s WHERE s.generation=p.generation AND s.page_phase=p.phase AND s.page_no=p.page_no)=p.row_count AND NOT EXISTS(SELECT 1 FROM json_each(request.rows_bytes) j WHERE NOT EXISTS(SELECT 1 FROM ${S} s JOIN ${H} h ON h.generation=s.generation WHERE s.generation=p.generation AND s.page_phase=p.phase AND s.page_no=p.page_no AND s.space_id=json_extract(j.value,'$.spaceId') AND s.command_id=json_extract(j.value,'$.commandId') AND s.expected_revision IS json_extract(j.value,'$.expectedRevision') AND s.selected=CASE p.phase WHEN 'desired' THEN 1 ELSE 0 END AND s.operator_reference=h.operator_reference))))) page_exact,(SELECT terminal FROM ${P} p WHERE p.generation=o.generation AND p.phase=request.phase AND p.page_no=request.page_no) page_terminal FROM (${OBSERVE}) o CROSS JOIN request`;
 const x=own(await database.withSession('first-primary').prepare(sql).bind(r.generation,p,pageNo,after,JSON.stringify(rows),r.manifestId,r.generation,null,null,null).first(),[...observationKeys,'page_exact','page_terminal']);if(x.page_exact!==0&&x.page_exact!==1||x.page_terminal!==null&&x.page_terminal!==0&&x.page_terminal!==1)throw Error();const v={...x};delete v.page_exact;delete v.page_terminal;return {observation:observation(v),exact:Boolean(x.page_exact),terminal:x.page_terminal===null?null:Boolean(x.page_terminal)};
}

/** Inert coordinator bound to one explicitly trusted database adapter. */
export function createSeoulProjectionTargetManifest(database:Database,adapter:'native-d1'|'durable-sql'):SeoulProjectionTargetManifest{
 if(!database||typeof database.prepare!=='function'||typeof database.batch!=='function'||typeof database.withSession!=='function'||!['native-d1','durable-sql'].includes(adapter))throw Error('seoul_target_manifest_adapter_unsupported');
 return Object.freeze({
  async publish(value:unknown):Promise<SeoulTargetManifestResult>{
   let input;try{input=await prepareSeoulTargetManifest(value);}catch{return {status:'invalid_input'};}const c=input.manifest;
   let before:Observation;try{before=await observe(database,{manifestId:c.manifestId,generation:null},input.manifestText,input.manifestSha256,input.setSha256);}catch{return {status:'uncertain'};}
   if(before.stage_present)return {status:'staging_retained'};if(before.generation!==null)return !before.manifest_exact?{status:'manifest_conflict'}:before.publication_valid?result('already_published',before):{status:'uncertain'};
   if(before.current_generation!==c.expectedGeneration)return {status:'generation_conflict'};if(c.expectedGeneration===Number.MAX_SAFE_INTEGER)return {status:'capacity'};
   const r={manifestId:c.manifestId,generation:(c.expectedGeneration??0)+1},w=stage('publish',r,{expectedGeneration:c.expectedGeneration,inputBytes:input.manifestText,manifestSha256:input.manifestSha256,setSha256:input.setSha256});
   const complete=`EXISTS(SELECT 1 FROM ${H} h WHERE h.manifest_id=? AND h.generation=? AND h.manifest_sha256=? AND h.set_sha256=? AND ${current}=h.generation AND ${exactMembers('h')})`,values=[r.manifestId,r.generation,input.manifestSha256,input.setSha256];
   const plans=[w.plan,statement(`INSERT INTO ${H}(generation,manifest_id,expected_generation,manifest_bytes,manifest_sha256,set_sha256,desired_count,operator_reference,published_at) SELECT generation,manifest_id,expected_generation,input_bytes,manifest_sha256,set_sha256,json_array_length(input_bytes,'$.spaceIds'),json_extract(input_bytes,'$.operatorReference'),decided_at FROM ${A} WHERE token=?`,[w.token]),statement(`INSERT INTO ${M}(generation,space_id,ordinal) SELECT a.generation,j.value,CAST(j.key AS INTEGER)+1 FROM ${A} a JOIN json_each(a.input_bytes,'$.spaceIds') j WHERE a.token=?`,[w.token]),statement(`UPDATE ${C} SET current_generation=(SELECT generation FROM ${A} WHERE token=?) WHERE singleton=1 AND current_generation IS (SELECT expected_generation FROM ${A} WHERE token=?)`,[w.token,w.token]),statement(guard(`EXISTS(SELECT 1 FROM ${A} WHERE token=?) AND ${complete}`),[w.token,...values]),cleanup(w.token),statement(guard(`${empty} AND ${complete}`),values)];
   plans.splice(5,0,statement(`SELECT published_at FROM ${H} WHERE generation=? AND manifest_id=?`,[r.generation,r.manifestId]));
   try{const executed=await batch(database,plans,[4,7]),row=own(executed[5],['success','results','meta']);if(!Array.isArray(row.results)||row.results.length!==1)throw Error();const time=integer(own(row.results[0],['published_at']).published_at,0);return {status:'published',...r,currentGeneration:r.generation,currentStatus:'planning',manifestSha256:input.manifestSha256,setSha256:input.setSha256,publishedAtMs:time};}catch{try{const after=await observe(database,{manifestId:c.manifestId,generation:null},input.manifestText,input.manifestSha256,input.setSha256);return !after.stage_present&&after.generation!==null&&after.manifest_exact&&after.publication_valid?result('already_published',after):{status:'uncertain'};}catch{return {status:'uncertain'};}}
  },
  async readManifest(value:unknown):Promise<SeoulTargetManifestResult>{let r;try{r=ref(own(value,refKeys));}catch{return {status:'invalid_input'};}try{const o=await observe(database,r);if(o.stage_present)return {status:'staging_retained'};return o.generation===null?{status:'manifest_missing'}:result('observed',o);}catch{return {status:'uncertain'};}},
  async readPlanningPage(value:unknown):Promise<SeoulTargetManifestResult>{
   let r,p,after;try{const x=own(value,[...refKeys,'phase','afterSpaceId']);r=ref(x);p=phase(x.phase);after=cursor(x.afterSpaceId);}catch{return {status:'invalid_input'};}
   try{const o=await observe(database,r),e=early(o);if(e)return e;if(o.total_count!==null)return {status:'inventory_sealed'};const prior=pageValue(o,p);if(after!==(prior?.lastSpaceId??null)||prior?.terminal)return {status:'page_conflict'};const rows=await planningRows(database,r,p,after),final=await observe(database,r),failure=early(final);if(failure)return failure;if(final.total_count!==null)return {status:'inventory_sealed'};const finalPage=pageValue(final,p);if(after!==(finalPage?.lastSpaceId??null)||finalPage?.terminal)return {status:'page_conflict'};return {...result('planning_page',final),pageNo:(finalPage?.pageNo??0)+1,steps:Object.freeze(rows.slice(0,32)),terminal:rows.length<=32};}catch{return {status:'uncertain'};}
  },
  async appendPlanningPage(value:unknown):Promise<SeoulTargetManifestResult>{
   let input:PageInput;try{const x=own(value,[...refKeys,'phase','pageNo','afterSpaceId','steps']);input=Object.freeze({...ref(x),phase:phase(x.phase),pageNo:integer(x.pageNo),afterSpaceId:cursor(x.afterSpaceId),steps:list(x.steps)});}catch{return {status:'invalid_input'};}
   try{const o=await observe(database,input);if(o.stage_present)return {status:'staging_retained'};if(o.generation===null)return {status:'manifest_missing'};const prior=pageValue(o,input.phase);if(prior&&input.pageNo<=prior.pageNo){const proof=await observePage(database,input,input.phase,input.pageNo,input.afterSpaceId,input.steps);if(proof.observation.stage_present)return {status:'staging_retained'};return proof.exact?{...result('already_recorded',proof.observation),pageNo:input.pageNo,terminal:Boolean(proof.terminal)}:{status:'page_conflict'};}const e=early(o);if(e)return e;if(o.total_count!==null)return {status:'inventory_sealed'};if(input.pageNo!==(prior?.pageNo??0)+1||input.afterSpaceId!==(prior?.lastSpaceId??null)||prior?.terminal)return {status:'page_conflict'};
    const expected=await planningRows(database,input,input.phase,input.afterSpaceId);if(input.steps.length!==Math.min(expected.length,32)||input.steps.some((s,i)=>s.spaceId!==expected[i]!.spaceId||s.expectedRevision!==expected[i]!.expectedRevision))return {status:'page_conflict'};
    const commands=input.steps.map(s=>ownTargetCommand({...s,selected:input.phase==='desired',operatorReference:o.operator_reference})),observations=commands.length?await observeTargetCommands(database,commands):[],owned=[];for(let i=0;i<observations.length;i++){const v=observations[i]!;if(v.stagePresent||v.control.manifestStagePresent)return {status:'staging_retained'};let p:TargetPrior;try{p=await prepareTargetPrior(v);}catch{return {status:'target_state_invalid'};}owned.push({...input.steps[i]!,...priorFields(p)});}
    const w=stage('page',input,{inputBytes:JSON.stringify(owned),phase:input.phase,pageNo:input.pageNo,afterSpaceId:input.afterSpaceId}),terminal=Number(expected.length<=32),cumulative=(prior?.cumulativeCount??0)+input.steps.length;if(!Number.isSafeInteger(cumulative))return {status:'capacity'};
    const complete=`EXISTS(SELECT 1 FROM ${P} p WHERE p.generation=? AND p.phase=? AND p.page_no=? AND p.after_space_id IS ? AND p.row_count=? AND p.cumulative_count=? AND p.terminal=? AND (SELECT count(*) FROM ${S} s WHERE s.generation=p.generation AND s.page_phase=p.phase AND s.page_no=p.page_no)=p.row_count AND NOT EXISTS(SELECT 1 FROM json_each(?) j WHERE NOT EXISTS(SELECT 1 FROM ${S} s WHERE s.generation=p.generation AND s.page_phase=p.phase AND s.page_no=p.page_no AND s.space_id=json_extract(j.value,'$.spaceId') AND s.command_id=json_extract(j.value,'$.commandId') AND s.expected_revision IS json_extract(j.value,'$.expectedRevision'))))`;
    const values=[input.generation,input.phase,input.pageNo,input.afterSpaceId,input.steps.length,cumulative,terminal,JSON.stringify(input.steps)];
    const plans=[w.plan,statement(`INSERT INTO ${P}(generation,phase,page_no,after_space_id,last_space_id,row_count,cumulative_count,terminal,observed_at) SELECT generation,phase,page_no,after_space_id,?,json_array_length(input_bytes),?,?,decided_at FROM ${A} WHERE token=?`,[input.steps.at(-1)?.spaceId??null,cumulative,terminal,w.token]),statement(`INSERT INTO ${S}(generation,space_id,command_id,expected_revision,selected,operator_reference,page_phase,page_no) SELECT a.generation,json_extract(j.value,'$.spaceId'),json_extract(j.value,'$.commandId'),json_extract(j.value,'$.expectedRevision'),CASE a.phase WHEN 'desired' THEN 1 ELSE 0 END,h.operator_reference,a.phase,a.page_no FROM ${A} a JOIN ${H} h ON h.generation=a.generation JOIN json_each(a.input_bytes) j WHERE a.token=?`,[w.token]),statement(guard(complete),values),cleanup(w.token),statement(guard(`${empty} AND ${current}=? AND ${complete}`),[input.generation,...values])];
    try{await batch(database,plans,[3,5]);return {status:'page_recorded',manifestId:input.manifestId,generation:input.generation,currentStatus:'planning',pageNo:input.pageNo,terminal:Boolean(terminal)};}catch{const proof=await observePage(database,input,input.phase,input.pageNo,input.afterSpaceId,input.steps);return !proof.observation.stage_present&&proof.exact?{...result('already_recorded',proof.observation),pageNo:input.pageNo,terminal:Boolean(proof.terminal)}:{status:'uncertain'};}
   }catch{return {status:'uncertain'};}
  },
  async seal(value:unknown):Promise<SeoulTargetManifestResult>{
   let r;try{r=ref(own(value,refKeys));}catch{return {status:'invalid_input'};}
   try{const o=await observe(database,r);if(o.stage_present)return {status:'staging_retained'};if(o.total_count!==null)return result('already_sealed',o);const e=early(o);if(e)return e;const d=pageValue(o,'desired'),p=pageValue(o,'omitted');if(!d?.terminal||!p?.terminal)return {status:'not_complete'};if(!Number.isSafeInteger(d.cumulativeCount+p.cumulativeCount))return {status:'capacity'};const w=stage('seal',r,{}),complete=`EXISTS(SELECT 1 FROM release_seoul_target_manifest_seals WHERE generation=? AND desired_terminal_page=? AND omitted_terminal_page=? AND desired_count=? AND omitted_count=?)`,values=[r.generation,d.pageNo,p.pageNo,d.cumulativeCount,p.cumulativeCount];
    const plans=[w.plan,statement(`INSERT INTO release_seoul_target_manifest_seals(generation,desired_terminal_page,omitted_terminal_page,desired_count,omitted_count,total_count,sealed_at) SELECT generation,?,?,?,?,?,decided_at FROM ${A} WHERE token=?`,[d.pageNo,p.pageNo,d.cumulativeCount,p.cumulativeCount,d.cumulativeCount+p.cumulativeCount,w.token]),statement(guard(complete),values),cleanup(w.token),statement(guard(`${empty} AND ${current}=? AND ${complete}`),[r.generation,...values])];try{await batch(database,plans,[2,4]);return {status:'sealed',...r,currentStatus:'applying'};}catch{const after=await observe(database,r);return !after.stage_present&&after.total_count!==null?result('already_sealed',after):{status:'uncertain'};}
   }catch{return {status:'uncertain'};}
  },
  async cancel(value:unknown):Promise<SeoulTargetManifestResult>{
   let r,cancellationId,operatorReference;try{const x=own(value,[...refKeys,'cancellationId','operatorReference']);r=ref(x);cancellationId=uuid(x.cancellationId);operatorReference=id(x.operatorReference,256);}catch{return {status:'invalid_input'};}
   try{const o=await observe(database,r);if(o.stage_present)return {status:'staging_retained'};if(o.generation===null)return {status:'manifest_missing'};if(o.cancellation_id!==null)return o.cancellation_id===cancellationId&&o.cancellation_reference===operatorReference?result('already_cancelled',o):{status:'manifest_conflict'};const e=early(o);if(e)return e;const w=stage('cancel',r,{cancellationId,operatorReference}),complete=`EXISTS(SELECT 1 FROM release_seoul_target_manifest_cancellations WHERE generation=? AND cancellation_id=? AND operator_reference=?)`,values=[r.generation,cancellationId,operatorReference];const plans=[w.plan,statement(`INSERT INTO release_seoul_target_manifest_cancellations(generation,cancellation_id,operator_reference,cancelled_at) SELECT generation,cancellation_id,operator_reference,decided_at FROM ${A} WHERE token=?`,[w.token]),statement(guard(complete),values),cleanup(w.token),statement(guard(`${empty} AND ${complete}`),values)];try{await batch(database,plans,[2,4]);return {status:'cancelled',...r,currentStatus:'cancelled'};}catch{const after=await observe(database,r);return !after.stage_present&&after.cancellation_id===cancellationId&&after.cancellation_reference===operatorReference?result('already_cancelled',after):{status:'uncertain'};}
   }catch{return {status:'uncertain'};}
  },
  async readSteps(value:unknown):Promise<SeoulTargetManifestResult>{
   let r,after;try{const x=own(value,[...refKeys,'afterSpaceId']);r=ref(x);after=cursor(x.afterSpaceId);}catch{return {status:'invalid_input'};}
   try{const o=await observe(database,r);if(o.stage_present)return {status:'staging_retained'};if(o.generation===null)return {status:'manifest_missing'};if(!o.publication_valid)return {status:'uncertain'};if(o.total_count===null)return {status:'not_sealed'};const rows=await stepRows(database,r,after);
    if(!rows.length){const final=await observe(database,r);if(final.stage_present)return {status:'staging_retained'};if(!final.publication_valid)return {status:'uncertain'};return {...result('steps',final),steps:Object.freeze([]),terminal:true};}
    const observations=await observeTargetCommands(database,rows.slice(0,32)),control=observations[0]!.control,out=[];for(const v of observations){if(v.stagePresent||v.control.manifestStagePresent)return {status:'staging_retained'};if(JSON.stringify(v.control)!==JSON.stringify(control))throw Error();let currentResultValid=false;try{await prepareTargetCompletion(v);currentResultValid=true;}catch{/* Historical receipt validity remains independent of today's result. */}out.push(Object.freeze({...v.command,receiptPresent:v.receiptBytes!==null,historyValid:v.receiptValid,currentResultValid}));}
    return {...result('steps',o),...currentLabel(r,control),steps:Object.freeze(out),terminal:rows.length<=32};
   }catch{return {status:'uncertain'};}
  },
  async verifyPage(value:unknown):Promise<SeoulTargetManifestResult>{
   let r,pageNo,after;try{const x=own(value,[...refKeys,'pageNo','afterSpaceId']);r=ref(x);pageNo=integer(x.pageNo);after=cursor(x.afterSpaceId);}catch{return {status:'invalid_input'};}
   try{const o=await observe(database,r);if(o.stage_present)return {status:'staging_retained'};if(o.generation===null)return {status:'manifest_missing'};const prior=pageValue(o,'verify');if(prior&&pageNo<=prior.pageNo){const commands=await stepRows(database,r,after),proof=await observePage(database,r,'verify',pageNo,after,commands.slice(0,32));if(proof.observation.stage_present)return {status:'staging_retained'};return proof.exact?{...result('already_verified',proof.observation),pageNo,terminal:Boolean(proof.terminal)}:{status:'page_conflict'};}const e=early(o);if(e)return e;if(o.total_count===null)return {status:'not_sealed'};if(o.completed_at!==null)return {status:'already_complete'};if(pageNo!==(prior?.pageNo??0)+1||after!==(prior?.lastSpaceId??null)||prior?.terminal)return {status:'page_conflict'};const commands=await stepRows(database,r,after),observations=commands.length?await observeTargetCommands(database,commands.slice(0,32)):[],proofs:TargetCompletionWitness[]=[];
    for(const observation of observations){if(observation.stagePresent||observation.control.manifestStagePresent)return {status:'staging_retained'};try{proofs.push(await prepareTargetCompletion(observation));}catch{return {status:'not_complete'};}}
    const rows=proofs.map(p=>({...p.command,...priorFields(p.prior),receipt_bytes:p.receiptBytes})),cumulative=(prior?.cumulativeCount??0)+rows.length;if(!Number.isSafeInteger(cumulative))return {status:'capacity'};const terminal=Number(commands.length<=32),w=stage('verify',r,{phase:'verify',pageNo,afterSpaceId:after,inputBytes:JSON.stringify(rows)}),done=`EXISTS(SELECT 1 FROM ${P} WHERE generation=? AND phase='verify' AND page_no=? AND after_space_id IS ? AND row_count=? AND cumulative_count=? AND terminal=?)`,values=[r.generation,pageNo,after,rows.length,cumulative,terminal];
    const plans=[w.plan,statement(guard(`EXISTS(SELECT 1 FROM ${A} a WHERE a.token=? AND ${completeProof})`),[w.token]),statement(`INSERT INTO ${P}(generation,phase,page_no,after_space_id,last_space_id,row_count,cumulative_count,terminal,observed_at) SELECT generation,phase,page_no,after_space_id,?,?,?, ?,decided_at FROM ${A} WHERE token=?`,[rows.at(-1)?.spaceId??null,rows.length,cumulative,terminal,w.token]),statement(guard(`EXISTS(SELECT 1 FROM ${A} a WHERE a.token=? AND ${completeProof}) AND ${done}`),[w.token,...values]),cleanup(w.token),statement(guard(`${empty} AND ${current}=? AND NOT EXISTS(SELECT 1 FROM release_seoul_target_manifest_cancellations WHERE generation=?) AND ${done}`),[r.generation,r.generation,...values])];
    try{await batch(database,plans,[1,3,5]);return {status:'page_verified',...r,currentStatus:'applying',pageNo,terminal:Boolean(terminal)};}catch{const proof=await observePage(database,r,'verify',pageNo,after,commands.slice(0,32));return !proof.observation.stage_present&&proof.exact?{...result('already_verified',proof.observation),pageNo,terminal:Boolean(proof.terminal)}:{status:'uncertain'};}
   }catch{return {status:'uncertain'};}
  },
  async complete(value:unknown):Promise<SeoulTargetManifestResult>{
   let r;try{r=ref(own(value,refKeys));}catch{return {status:'invalid_input'};}
   try{const o=await observe(database,r);if(o.stage_present)return {status:'staging_retained'};if(o.completed_at!==null)return result('already_completed',o);const e=early(o);if(e)return e;if(o.total_count===null)return {status:'not_sealed'};const p=pageValue(o,'verify');if(!p?.terminal||p.cumulativeCount!==o.total_count)return {status:'not_complete'};const w=stage('complete',r,{}),done=`EXISTS(SELECT 1 FROM ${H} h JOIN release_seoul_target_manifest_completions f ON f.generation=h.generation AND f.manifest_sha256=h.manifest_sha256 AND f.set_sha256=h.set_sha256 WHERE h.generation=? AND h.manifest_id=? AND ${current}=h.generation AND NOT EXISTS(SELECT 1 FROM release_seoul_target_manifest_cancellations WHERE generation=h.generation) AND ${selectedExact})`,values=[r.generation,r.manifestId];
    const plans=[w.plan,statement(`INSERT INTO release_seoul_target_manifest_completions(generation,manifest_sha256,set_sha256,verified_terminal_page,step_count,completed_at) SELECT a.generation,h.manifest_sha256,h.set_sha256,?,?,a.decided_at FROM ${A} a JOIN ${H} h ON h.generation=a.generation WHERE a.token=?`,[p.pageNo,p.cumulativeCount,w.token]),statement(guard(done),values),cleanup(w.token),statement(guard(`${empty} AND ${done}`),values)];try{await batch(database,plans,[2,4]);return {status:'completed',...r,currentStatus:'complete'};}catch{const after=await observe(database,r);return !after.stage_present&&after.completed_at!==null?result('already_completed',after):{status:'uncertain'};}
   }catch{return {status:'uncertain'};}
  },
  async observeAgreement(value:unknown):Promise<SeoulTargetManifestResult>{
   let r,set;try{const x=own(value,[...refKeys,'configuredSpaceIds']);r=ref(x);set=await prepareSeoulTargetSet(x.configuredSpaceIds);}catch{return {status:'invalid_input'};}
   try{const o=await observe(database,r),e=early(o);if(e)return e;if(o.completed_at===null)return {status:'not_complete'};if(o.set_sha256!==set.setSha256)return {status:'configuration_mismatch'};
    const manifest=await prepareSeoulTargetManifest({version:1,manifestId:r.manifestId,expectedGeneration:o.expected_generation,operatorReference:o.operator_reference,spaceIds:set.spaceIds});if(manifest.manifestSha256!==o.manifest_sha256)return {status:'uncertain'};
    const sql=`WITH v(manifest_id,generation,set_sha256,set_bytes,manifest_sha256,manifest_bytes) AS (VALUES(?,?,?,?,?,?)) SELECT CASE WHEN ${empty} AND h.generation=${current} AND h.manifest_id=v.manifest_id AND h.manifest_sha256=v.manifest_sha256 AND h.manifest_bytes=v.manifest_bytes AND h.set_sha256=v.set_sha256 AND h.desired_count=json_array_length(v.set_bytes) AND NOT EXISTS(SELECT 1 FROM json_each(v.set_bytes) j WHERE NOT EXISTS(SELECT 1 FROM ${M} m WHERE m.generation=h.generation AND m.ordinal=CAST(j.key AS INTEGER)+1 AND m.space_id=j.value)) AND ${exactMembers('h')} AND ${selectedExact} AND f.generation=h.generation AND f.manifest_sha256=h.manifest_sha256 AND f.set_sha256=h.set_sha256 AND NOT EXISTS(SELECT 1 FROM release_seoul_target_manifest_cancellations x WHERE x.generation=h.generation) THEN 1 ELSE 0 END agreed,f.completed_at,${now} observed_at FROM v LEFT JOIN ${H} h ON h.generation=v.generation LEFT JOIN release_seoul_target_manifest_completions f ON f.generation=h.generation`;
    const x=own(await database.withSession('first-primary').prepare(sql).bind(r.manifestId,r.generation,set.setSha256,set.setText,manifest.manifestSha256,manifest.manifestText).first(),['agreed','completed_at','observed_at']);if(x.agreed!==0&&x.agreed!==1)throw Error();const time=integer(x.observed_at,0);return x.agreed?{status:'agreed',...r,currentGeneration:r.generation,currentStatus:'complete',manifestSha256:manifest.manifestSha256,setSha256:set.setSha256,completedAtMs:integer(x.completed_at,0),observedAtMs:time}:{status:'configuration_mismatch'};
   }catch{return {status:'uncertain'};}
  },
 });
}
