import type {Database} from './types.ts';
import {ownTargetCommand,parseTargetReceipt,targetReceiptMatches,observeTargetCommands,prepareTargetPrior,buildTargetWritePlan,decodeTargetWriteResults,targetRequestWithinLimits,recoverTargetWrite,type SeoulTargetCommand,type SeoulTargetReceipt,type TargetControlObservation,type TargetObservation,type TargetSqlStatement} from './seoul-projection-target-internal.ts';
export type {SeoulTargetCommand,SeoulTargetReceipt} from './seoul-projection-target-internal.ts';
type Failure='invalid_command'|'invalid_input'|'command_conflict'|'target_missing'|'target_state_invalid'|'stale_revision'|'staging_retained'|'request_limit'|'uncertain'|'manifest_controlled'|'manifest_missing'|'step_missing'|'superseded'|'cancelled'|'not_sealed';
type ManifestRef=Readonly<{manifestId:string;generation:number;spaceId:string}>;
type ManifestObservation=Readonly<{manifestId:string;generation:number;currentGeneration:number|null;currentStatus:'planning'|'applying'|'complete'|'cancelled'|'superseded'}>;
export type SeoulTargetResult=Readonly<{status:'committed'|'already_committed';receipt:SeoulTargetReceipt;manifest?:ManifestObservation}>|Readonly<{status:'historical_commit';receipt:SeoulTargetReceipt;control:TargetControlObservation;manifest?:ManifestObservation}>|Readonly<{status:Failure}>;
export interface SeoulProjectionTargetWriter{setTarget(command:unknown):Promise<SeoulTargetResult>;setManifestStep(input:unknown):Promise<SeoulTargetResult>}
const A='release_seoul_target_manifest_attempt',C='release_seoul_target_manifest_control',S='release_seoul_target_manifest_steps',H='release_seoul_target_manifests';
function own(value:unknown,keys:readonly string[]):Record<string,unknown>{if(!value||typeof value!=='object'||(Object.getPrototypeOf(value)!==Object.prototype&&Object.getPrototypeOf(value)!==null))throw Error();const actual=Reflect.ownKeys(value);if(actual.length!==keys.length||actual.some(k=>typeof k!=='string'||!keys.includes(k)))throw Error();const result:Record<string,unknown>={};for(const key of keys){const d=Object.getOwnPropertyDescriptor(value,key);if(!d||!d.enumerable||!('value'in d))throw Error();result[key]=d.value;}return result;}
function reference(value:unknown):ManifestRef{const x=own(value,['manifestId','generation','spaceId']);if(typeof x.manifestId!=='string'||x.manifestId.length!==36||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(x.manifestId)||typeof x.generation!=='number'||!Number.isSafeInteger(x.generation)||x.generation<1||typeof x.spaceId!=='string'||!x.spaceId.length||x.spaceId.length>128||!/^[A-Za-z0-9]/.test(x.spaceId)||/[^A-Za-z0-9._:-]/.test(x.spaceId))throw Error();return Object.freeze({manifestId:x.manifestId,generation:x.generation,spaceId:x.spaceId});}
function manifestObservation(r:ManifestRef,c:TargetControlObservation):ManifestObservation{return Object.freeze({manifestId:r.manifestId,generation:r.generation,currentGeneration:c.currentGeneration,currentStatus:c.currentGeneration!==r.generation||c.currentManifestId!==r.manifestId?'superseded':c.cancelled?'cancelled':c.completed?'complete':c.sealed?'applying':'planning'});}
function earlyControl(r:ManifestRef,c:TargetControlObservation):Failure|null{if(c.currentGeneration!==r.generation||c.currentManifestId!==r.manifestId)return 'superseded';if(c.cancelled)return 'cancelled';if(!c.sealed)return 'not_sealed';return null;}
async function historical(database:Database,c:SeoulTargetCommand,r?:ManifestRef):Promise<SeoulTargetResult>{const recovery=await recoverTargetWrite(database,c);if(recovery.status!=='historical_commit')return {status:'uncertain'};if(r){const manifest=manifestObservation(r,recovery.control);return manifest.currentStatus==='superseded'||manifest.currentStatus==='cancelled'?{status:'historical_commit',receipt:recovery.receipt,control:recovery.control,manifest}:{status:'already_committed',receipt:recovery.receipt,manifest};}return recovery.control.currentGeneration===null?{status:'already_committed',receipt:recovery.receipt}:{status:'historical_commit',receipt:recovery.receipt,control:recovery.control};}
async function run(database:Database,c:SeoulTargetCommand,before:TargetObservation,r?:ManifestRef):Promise<SeoulTargetResult>{
 if(before.stagePresent||before.control.manifestStagePresent)return {status:'staging_retained'};
 if(r){const failure=earlyControl(r,before.control);if(failure)return {status:failure};}
 if(before.receiptBytes){let receipt:SeoulTargetReceipt;try{receipt=parseTargetReceipt(before.receiptBytes);}catch{return {status:'uncertain'};}if(!targetReceiptMatches(receipt,c))return {status:'command_conflict'};if(!before.receiptValid)return {status:'target_state_invalid'};return r?{status:'already_committed',receipt,manifest:manifestObservation(r,before.control)}:before.control.currentGeneration===null?{status:'already_committed',receipt}:{status:'historical_commit',receipt,control:before.control};}
 if(!r&&before.control.currentGeneration!==null)return {status:'manifest_controlled'};
 if(!before.spacePresent)return {status:'target_missing'};if(before.commandSourcePresent)return {status:'target_state_invalid'};
 let prior;try{prior=await prepareTargetPrior(before);}catch{return {status:'target_state_invalid'};}if((prior.state==='present'?prior.revision:null)!==c.expectedRevision)return {status:'stale_revision'};
 let request:readonly TargetSqlStatement[];try{const plan=buildTargetWritePlan(c,prior);request=plan.statements;
  if(r){const token=crypto.randomUUID(),values=[token,r.manifestId,r.generation,c.commandId,c.spaceId,c.expectedRevision,Number(c.selected),c.operatorReference],context=`EXISTS(SELECT 1 FROM ${H} h JOIN ${C} control ON control.singleton=1 AND control.current_generation=h.generation JOIN ${S} s ON s.generation=h.generation WHERE h.manifest_id=? AND h.generation=? AND s.command_id=? AND s.space_id=? AND s.expected_revision IS ? AND s.selected=? AND s.operator_reference=? AND EXISTS(SELECT 1 FROM release_seoul_target_manifest_seals WHERE generation=h.generation) AND NOT EXISTS(SELECT 1 FROM release_seoul_target_manifest_cancellations WHERE generation=h.generation) AND NOT EXISTS(SELECT 1 FROM release_seoul_target_manifest_completions WHERE generation=h.generation))`;
   request=[{sql:`INSERT INTO ${A}(token,operation,manifest_id,generation,command_id,space_id,expected_revision,selected,operator_reference,observed_generation,decided_at) VALUES(?,'apply',?,?,?,?,?,?,?,(SELECT current_generation FROM ${C} WHERE singleton=1),CAST(round(unixepoch('subsec')*1000) AS INTEGER))`,values,mode:'all'},...plan.statements,{sql:`DELETE FROM ${A} WHERE token=?`,values:[token],mode:'all'},{sql:`SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM ${A} LIMIT 1) AND NOT EXISTS(SELECT 1 FROM release_seoul_target_attempt LIMIT 1) AND ${context} THEN 1 ELSE abs(-9223372036854775808) END complete_guard`,values:[r.manifestId,r.generation,c.commandId,c.spaceId,c.expectedRevision,Number(c.selected),c.operatorReference],mode:'all'}];
  }if(!targetRequestWithinLimits(request))return {status:'request_limit'};
 }catch{return {status:'uncertain'};}
 try{const result=decodeTargetWriteResults(await database.batch(request.map(p=>database.prepare(p.sql).bind(...p.values))),c,r?'manifest13':'direct10');return r&&'receipt'in result?{...result,manifest:manifestObservation(r,before.control)}:result;}catch{return historical(database,c,r);}
}
/** Inert trusted same-database primitive. Complete0035 is required even before
 * the first manifest. No route, retry, target list or runtime factory is wired. */
export function createSeoulProjectionTargetWriter(database:Database,adapter:'native-d1'|'durable-sql'):SeoulProjectionTargetWriter{
 if(!database||typeof database.prepare!=='function'||typeof database.batch!=='function'||typeof database.withSession!=='function'||(adapter!=='native-d1'&&adapter!=='durable-sql'))throw Error('seoul_target_writer_adapter_unsupported');
 return Object.freeze({
  async setTarget(value:unknown):Promise<SeoulTargetResult>{let c;try{c=ownTargetCommand(value);}catch{return {status:'invalid_command'};}let before;try{before=(await observeTargetCommands(database,[c]))[0]!;}catch{return {status:'uncertain'};}return run(database,c,before);},
  async setManifestStep(value:unknown):Promise<SeoulTargetResult>{let r;try{r=reference(value);}catch{return {status:'invalid_input'};}
   let c:SeoulTargetCommand;try{const sql=`WITH v(manifest_id,generation,space_id) AS(VALUES(?,?,?)) SELECT (SELECT version FROM release_meta) schema_version,EXISTS(SELECT 1 FROM ${A} LIMIT 1) OR EXISTS(SELECT 1 FROM release_seoul_target_attempt LIMIT 1) stage_present,h.generation,CASE WHEN s.command_id IS NULL THEN NULL ELSE json_object('commandId',s.command_id,'spaceId',s.space_id,'expectedRevision',s.expected_revision,'selected',json(CASE s.selected WHEN 1 THEN 'true' ELSE 'false' END),'operatorReference',s.operator_reference) END command_bytes FROM v LEFT JOIN ${H} h ON h.manifest_id=v.manifest_id AND h.generation=v.generation LEFT JOIN ${S} s ON s.generation=h.generation AND s.space_id=v.space_id`,x=own(await database.withSession('first-primary').prepare(sql).bind(r.manifestId,r.generation,r.spaceId).first(),['schema_version','stage_present','generation','command_bytes']);if(typeof x.schema_version!=='number'||!Number.isSafeInteger(x.schema_version)||x.schema_version<35||(x.stage_present!==0&&x.stage_present!==1))throw Error();if(x.stage_present)return {status:'staging_retained'};if(x.generation===null)return {status:'manifest_missing'};if(x.generation!==r.generation)throw Error();if(x.command_bytes===null)return {status:'step_missing'};if(typeof x.command_bytes!=='string'||x.command_bytes.length>1024)throw Error();c=ownTargetCommand(JSON.parse(x.command_bytes));if(c.spaceId!==r.spaceId)throw Error();}catch{return {status:'uncertain'};}
   let before;try{before=(await observeTargetCommands(database,[c]))[0]!;}catch{return {status:'uncertain'};}return run(database,c,before,r);
  },
 });
}
