import test, {after} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fixture,at} from './db-sqlite.mjs';
import {IdentityService,IdentityDenied} from '../../src/identity.ts';
import {MemoryService,MemoryDenied} from '../../src/memory.ts';
import {Admin} from '../../src/release/admin.ts';
import {receiveLifecycle} from '../../src/release/lifecycle.ts';
import {createSeoulProjectionCapture} from '../../src/release/seoul-projection-capture.ts';
import {parseSeoulAuthoritySourceRow} from '../../src/release/seoul-projection-source-codec.ts';
import {createDurableDatabase} from '../../src/durable-sql/client.ts';
import {SqlDatabaseEngine} from '../../src/durable-sql/engine.ts';

const issuer='https://auth-api.allen.company';
for(const recursive of ['ON','OFF'])for(const command of ['email','domain','deactivate','delete'])test('captured dirty revision survives later ordinary '+command+'; '+recursive,async t=>{
 const f=await setup(t,recursive);api(f,'api:after-capture');const act=command==='email'?await link(f):command==='domain'?domain(f):await scim(f,command),space=command==='email'||command==='domain'?'s2':'so',prior=(await f.raw.prepare('SELECT max(revision) n FROM release_seoul_authority_changes').get()).n;
 (await f.raw.prepare('INSERT INTO release_seoul_dirty_spaces(space_id,dirty_revision,captured_revision) VALUES(?,?,?)').run(space,prior,prior));
 await act('m2');const actual=(await f.raw.prepare('SELECT * FROM release_seoul_dirty_spaces WHERE space_id=?').get(space)),latest=Math.max(...sources(f).map(r=>r.revision));assert.ok(latest>prior);assert.equal(actual.dirty_revision,latest);assert.equal(actual.captured_revision,prior);clean(f);
});
for(const recursive of ['ON','OFF'])test('dirty insert reads a captured revision advanced inside the original command batch; '+recursive,async t=>{
 const f=await setup(t,recursive),act=domain(f),prior=(await f.raw.prepare('SELECT max(revision) n FROM release_seoul_authority_changes').get()).n;assert.ok(prior>1);(await f.raw.prepare('INSERT INTO release_seoul_dirty_spaces(space_id,dirty_revision,captured_revision) VALUES(?,?,1)').run('s2',prior));
 (await f.raw.exec("CREATE TRIGGER advance_captured_during_command AFTER INSERT ON revocations BEGIN UPDATE release_seoul_dirty_spaces SET captured_revision=dirty_revision WHERE space_id='s2'; END"));
 await act();const actual=(await f.raw.prepare("SELECT * FROM release_seoul_dirty_spaces WHERE space_id='s2'").get()),latest=Math.max(...sources(f).map(r=>r.revision));assert.ok(latest>prior);assert.equal(actual.dirty_revision,latest);assert.equal(actual.captured_revision,prior);clean(f);
});
const rows=async (f,table)=>(await f.raw.prepare('SELECT * FROM '+table+' ORDER BY rowid').all());
const sources=f=>rows(f,'release_seoul_authority_changes').filter(r=>r.source_command_id!=='setup-target');
const bodies=f=>sources(f).map(r=>parseSeoulAuthoritySourceRow(r).body);
const stage=['release_seoul_command_scope','release_seoul_command_spaces','release_seoul_command_attempts'];
const observations={};
after(()=>process.stdout.write('command_capture_observations '+JSON.stringify(observations)+'\n'));
async function clean(f){for(const table of stage)assert.equal(rows(f,table).length,0,table);for(const r of f.calls){const first=r.statements.find(s=>s.sql.includes('INSERT INTO release_seoul_command_attempts'));if(first){const kind=first.values[1],seen=observations[kind]??={statements:0,requestBytes:0,sqlBytes:0,sourceBytes:0,totalSourceBytes:0};seen.statements=Math.max(seen.statements,r.statements.length);seen.requestBytes=Math.max(seen.requestBytes,Buffer.byteLength(JSON.stringify(r)));seen.sqlBytes=Math.max(seen.sqlBytes,...r.statements.map(s=>Buffer.byteLength(s.sql)));assert.ok(r.statements.length<=100);assert.ok(Buffer.byteLength(JSON.stringify(r))<=1048576);for(const group of new Set(sources(f).map(s=>s.source_command_id))){const selected=sources(f).filter(s=>s.source_command_id===group);seen.sourceBytes=Math.max(seen.sourceBytes,...selected.map(s=>Buffer.byteLength(s.record_bytes)));seen.totalSourceBytes=Math.max(seen.totalSourceBytes,selected.reduce((sum,s)=>sum+Buffer.byteLength(s.record_bytes),0));}}}assert.equal((await f.raw.prepare('SELECT state FROM release_seoul_projection_state').get()).state,'backfill-required');assert.deepEqual((await f.raw.prepare('PRAGMA foreign_key_check').all()),[]);}
async function setup(t,recursive='ON'){
 const f=await fixture();t.after(()=>f.db.close());f.raw=f.db.raw;
 for(const file of ['0026_seoul-projection-schema.sql','0027_seoul-projection-capture-schema.sql','0028_seoul-projection-bootstrap-schema.sql','0029_seoul-projection-preparation-schema.sql','0030_seoul-projection-workspace-schema.sql','0031_seoul-projection-provider-schema.sql'])(await f.raw.exec(readFileSync(new URL('../../migrations/'+file,import.meta.url),'utf8')));
 const schema=readFileSync(new URL('../../seoul-projection-command-schema.sql',import.meta.url),'utf8'),migration=readFileSync(new URL('../../migrations/0032_seoul-projection-command-schema.sql',import.meta.url),'utf8');assert.equal(migration,'-- Forward SaaS migration 32: seoul-projection-command-schema.sql\n'+schema);(await f.raw.exec(migration));assert.equal((await f.raw.prepare('SELECT version FROM release_meta').get()).version,32);(await f.raw.exec('PRAGMA recursive_triggers='+recursive));
 const storage={sql:{exec(sql,...values){const s=(await f.raw.prepare(sql)),r=s.all(...values),readonly=s.columns().length>0&&/^(SELECT|WITH|PRAGMA)\b/i.test(sql.trim());return {rowsWritten:readonly?0:Number((await f.raw.prepare('SELECT changes() n').get()).n),toArray:()=>r,[Symbol.iterator]:()=>r[Symbol.iterator]()};}},transactionSync(fn){(await f.raw.exec('BEGIN IMMEDIATE'));try{const r=fn();(await f.raw.exec('COMMIT'));return r;}catch(e){(await f.raw.exec('ROLLBACK'));throw e;}}};
 const engine=new SqlDatabaseEngine(storage,{objectName:'sql:staging:control:1'});engine.initialize();(await f.raw.prepare('INSERT INTO durable_sql_state VALUES(1,?,?,?,?,?,?,?)').run('staging','control','control',1,'ready','a'.repeat(64),'b'.repeat(64)));f.calls=[];
 f.adapter=createDurableDatabase({async execute(request){f.calls.push(request);return engine.execute(request);}},{deploymentId:'staging',databaseId:'control',kind:'control',epoch:1});f.capture=createSeoulProjectionCapture(f.adapter,'durable-sql');f.identity=new IdentityService(f.adapter,()=>at,f.capture);f.memory=new MemoryService(f.adapter,()=>at,f.capture);f.admin=new Admin({DB:f.adapter,PUBLIC_ORIGIN:'https://memory.example.com'},()=>at,f.capture);
 for(const [account,sub] of [['alice','alice'],['bob','bob'],['bob','bob-alias']])(await f.raw.prepare('INSERT INTO provider_identities VALUES(?,?,?,?)').run(issuer,sub,account,at));
 for(const id of ['s1','s2','so']){(await f.raw.prepare("INSERT INTO release_seoul_authority_changes(source_command_id,stream_kind,stream_key,event_id,record_bytes,created_at) VALUES('setup-target','target',?,?, '{}',?)").run(id,crypto.randomUUID(),at));(await f.raw.prepare('INSERT INTO release_seoul_targets SELECT ?,1,max(revision) FROM release_seoul_authority_changes').run(id));}
 return f;
}
async function api(f,id,n=1){(await f.raw.prepare("INSERT INTO credentials(id,account_id,membership_id,email_id,kind,token_digest,expires_at,permission) VALUES(?,'bob','m2','e2','api_key',?,?,'read')").run(id,n.toString(16).padStart(64,'0'),at+900000));}
async function link(f){let delivered;await f.identity.beginEmailLink(f.other,'linked@example.com',async d=>{delivered=d;});return ()=>f.identity.completeEmailLink(f.other,delivered.challengeId,delivered.proofToken);}
async function domain(f){(await f.raw.exec(`INSERT INTO domains VALUES('domain','org','example.com',${at+900000},NULL); INSERT INTO domain_managers VALUES('domain','m1',NULL);`));return ()=>f.identity.revokeDomainEmail(f.token,'domain','bob@example.com');}
async function scim(f,kind='deactivate'){const key=await f.admin.issueScimKey(f.token,'org');return target=>kind==='deactivate'?f.admin.scimDeactivate(key.token,'org',target):f.admin.scimDelete(key.token,'org',target);}

for(const recursive of ['ON','OFF'])test('email consumption captures exact new claim for every alias; '+recursive,async t=>{const f=await setup(t,recursive),act=await link(f),id=await act();const core=bodies(f);assert.equal(core.length,2);for(const b of core){assert.equal(b.kind,'email-source');assert.equal(b.accountId,'bob');assert.equal(b.liveClaim.id,id);assert.equal(b.changedClaim,null);assert.deepEqual(b.origin,{kind:'command',commandType:'email-link',receiptId:id});assert.deepEqual(b.effect,{type:'entity-head',disposition:'changed'});}assert.ok((await f.raw.prepare('SELECT id FROM email_consumptions WHERE id=?').get(id)));assert.deepEqual(rows(f,'release_seoul_dirty_spaces').map(r=>r.space_id),['s2']);const before=sources(f);await assert.rejects(act,IdentityDenied);assert.deepEqual(sources(f),before);clean(f);});
for(const recursive of ['ON','OFF'])test('domain manager captures target aliases and physical member/API cascades; '+recursive,async t=>{const f=await setup(t,recursive);api(f,'api:live');await domain(f)();const core=bodies(f);assert.deepEqual(core.map(b=>b.kind).sort(),['credential-source','email-source','email-source','membership-source']);assert.ok(core.every(b=>b.accountId==='bob'));for(const b of core){assert.equal(b.origin.commandType,'domain-email-revoke');assert.ok((await f.raw.prepare("SELECT id FROM revocations WHERE id=? AND kind='domain'").get(b.origin.receiptId)));if(b.kind==='email-source'){assert.equal(b.liveClaim,null);assert.equal(b.changedClaim.id,'e2');assert.equal(b.addressBlocked,true);}else assert.equal(b.effect.occurredAtMs,at);}assert.deepEqual(rows(f,'release_seoul_dirty_spaces').map(r=>r.space_id),['s2','so']);const before=sources(f);await domainAgain(f);assert.deepEqual(sources(f),before);clean(f);});
async function domainAgain(f){await f.identity.revokeDomainEmail(f.token,'domain','bob@example.com');}
for(const recursive of ['ON','OFF'])for(const kind of ['deactivate','delete'])test('SCIM '+kind+' exact changed member and API return/result; '+recursive,async t=>{const f=await setup(t,recursive);api(f,'api:live');const act=await scim(f,kind),result=await act('m2');assert.deepEqual(result,kind==='delete'?undefined:{id:'m2',userName:'bob@example.com',active:0});const core=bodies(f);assert.deepEqual(core.map(b=>b.id).sort(),['api:live','m2']);assert.ok(core.every(b=>b.accountId==='bob'&&b.origin.commandType==='scim-'+kind&&b.origin.receiptId===null&&b.effect.occurredAtMs===at));assert.deepEqual(rows(f,'release_seoul_dirty_spaces').map(r=>r.space_id),['so']);const before=sources(f);if(kind==='delete')await assert.rejects(()=>act('m2'),e=>e.status===404);else assert.deepEqual(await act('m2'),result);assert.deepEqual(sources(f),before);clean(f);});
for(const recursive of ['ON','OFF'])for(const org of [false,true])test('Space creation records only exact new Space and always dirties it; '+recursive+'/'+org,async t=>{const f=await setup(t,recursive),result=await f.memory.createSpace(f.token,{name:'Created',...(org?{organizationId:'org'}:{})});assert.deepEqual(Object.keys(result),['id','name','organizationId','securityMode']);const [b]=bodies(f);assert.equal(sources(f).length,1);assert.deepEqual(b,{version:3,kind:'space-source',id:result.id,accountId:org?null:'alice',organizationId:org?'org':null,securityMode:'managed',createdAtMs:at,origin:{kind:'command',commandType:'space-create',receiptId:null},effect:{type:'entity-head',disposition:'changed'}});assert.deepEqual(rows(f,'release_seoul_dirty_spaces').map(r=>r.space_id),[result.id]);clean(f);});
test('SCIM last owner denied and revoked deletion metadata creates no source',async t=>{const f=await setup(t),deactivate=await scim(f),del=await scim(f,'delete');await assert.rejects(()=>deactivate('m1'),e=>e.status===403);await assert.rejects(()=>del('m1'),e=>e.status===403);(await f.raw.prepare("UPDATE memberships SET revoked_at=? WHERE id='m2'").run(at-1));assert.equal(await del('m2'),undefined);assert.equal(rows(f,'release_scim_deletions').length,1);assert.equal(sources(f).length,0);clean(f);});
test('blocked/ignored/expired email link preserves denial and no source',async t=>{for(const condition of ['blocked','lifecycle','expired']){const f=await setup(t),act=await link(f);if(condition==='blocked')await (domain(f),f.identity.revokeDomainEmail(f.token,'domain','linked@example.com'));if(condition==='lifecycle')(await f.raw.exec("INSERT INTO release_external_email_blocks(account_id,address,created_at) VALUES('bob','linked@example.com',0)"));if(condition==='expired')(await f.db.setClock(()=>at+1000000));await assert.rejects(act);assert.equal(rows(f,'email_consumptions').length,0);assert.equal(sources(f).length,0);clean(f);}});
for(const recursive of ['ON','OFF'])for(const kind of ['email','domain','deactivate','delete','space'])test('late '+kind+' failure rolls back original rows and capture; '+recursive,async t=>{const f=await setup(t,recursive);api(f,'api:live');const act=kind==='email'?await link(f):kind==='domain'?domain(f):kind==='space'?async ()=>f.memory.createSpace(f.token,{name:'Rollback'}):await scim(f,kind);const tables=['spaces','credentials','memberships','account_emails','email_consumptions','email_challenges','revocations','email_blocks','release_scim_deletions','audit_events','release_seoul_authority_changes','release_seoul_authority_heads','release_seoul_dirty_spaces','release_seoul_account_exclusions'];const before=new Map(tables.map(table=>[table,rows(f,table)]));(await f.raw.exec("CREATE TRIGGER command_capture_late BEFORE DELETE ON release_seoul_command_attempts BEGIN SELECT RAISE(ABORT,'command capture late'); END"));await assert.rejects(()=>act('m2'),{message:'command capture late'});for(const table of tables)assert.deepEqual(rows(f,table),before.get(table),table);clean(f);});
test('unrelated revoked address history does not expand domain authorizing scope',async t=>{const f=await setup(t);for(let n=0;n<600;n++)(await f.raw.prepare("INSERT INTO account_emails VALUES(?,'alice','bob@example.com','example.com',?,?)").run('old:'+n,at-2,at-1));await domain(f)();assert.deepEqual(bodies(f).filter(b=>b.kind==='email-source').map(b=>b.accountId),['bob','bob']);assert.equal(rows(f,'release_seoul_account_exclusions').length,0);clean(f);});
test('retained command staging cannot become a new empty-scope witness',async t=>{const f=await setup(t);(await f.raw.exec("INSERT INTO release_seoul_command_attempts(id,command_kind,entity_id,command_at) VALUES('00000000-0000-4000-8000-000000000001','scim-deactivate','absent',0)"));const before=rows(f,'release_seoul_command_attempts'),act=await scim(f);await assert.rejects(()=>act('absent'),{message:'command capture staging is not empty'});assert.deepEqual(rows(f,'release_seoul_command_attempts'),before);assert.equal(sources(f).length,0);});

test('excluded already-revoked SCIM replay and metadata-only delete create no exclusion/source',async t=>{for(const kind of ['deactivate','delete']){const f=await setup(t),act=await scim(f,kind);(await f.raw.prepare('INSERT INTO provider_identities VALUES(?,?,?,?)').run('https://foreign.example','bad','bob',at));(await f.raw.prepare("UPDATE memberships SET revoked_at=? WHERE id='m2'").run(at));await act('m2');assert.equal(sources(f).length,0);assert.equal(rows(f,'release_seoul_account_exclusions').length,0);clean(f);}});

for(const reason of ['unmapped','foreign','keys','policy-bytes','policy-values','policy-count','spaces','space-id','subject','max-subject','source-product'])test('valid domain revoke preserves central success and complete exclusion: '+reason,async t=>{
 const f=await setup(t);api(f,'api:live');
 if(reason==='unmapped')(await f.raw.exec("DROP TRIGGER provider_identities_no_delete; DELETE FROM provider_identities WHERE account_id='bob'"));
 if(reason==='foreign')(await f.raw.prepare('INSERT INTO provider_identities VALUES(?,?,?,?)').run('https://foreign.example','opaque','bob',at));
 if(reason==='keys')for(let n=2;n<=513;n++)api(f,'api:'+n,n);
 if(reason.startsWith('policy-'))(await f.raw.prepare('INSERT INTO release_credential_policies(credential_id,capabilities,space_ids) VALUES(?,?,?)').run('api:live',reason==='policy-bytes'?JSON.stringify(Array(30000).fill('read')):reason==='policy-values'?'["invented"]':'["read"]',reason==='policy-count'?JSON.stringify(Array.from({length:51},(_,i)=>'s:'+i)):null));
 if(reason==='spaces')for(let n=0;n<513;n++)(await f.raw.prepare("INSERT INTO spaces VALUES(?,'Retained',NULL,'org','managed',?,'session:alice')").run('raw:'+n,at));
 if(reason==='space-id')(await f.raw.prepare("INSERT INTO spaces VALUES(?,'Retained',NULL,'org','managed',?,'session:alice')").run('s'.repeat(129),at));
 if(reason==='subject')(await f.raw.prepare('INSERT INTO provider_identities VALUES(?,?,?,?)').run(issuer,'\u2003'.repeat(3),'bob',at));
 if(reason==='max-subject')(await f.raw.prepare('INSERT INTO provider_identities VALUES(?,?,?,?)').run(issuer,'界'.repeat(512),'bob',at)); // A valid maximum UTF-16 subject remains representable without truncation.
 if(reason==='source-product')for(let n=0;n<100;n++)(await f.raw.prepare('INSERT INTO provider_identities VALUES(?,?,?,?)').run(issuer,'alias:'+n+':'+('x'.repeat(100)),'bob',at));
 if(reason==='max-subject'){await domain(f)();assert.equal(rows(f,'release_seoul_account_exclusions').length,0);assert.equal(bodies(f).filter(b=>b.kind==='email-source').length,3);clean(f);return;}
 await domain(f)();assert.equal((await f.raw.prepare("SELECT revoked_at FROM account_emails WHERE id='e2'").get()).revoked_at,at);assert.equal((await f.raw.prepare("SELECT revoked_at FROM credentials WHERE id='api:live'").get()).revoked_at,at);assert.deepEqual(rows(f,'release_seoul_account_exclusions').map(r=>r.account_id),['bob']);assert.ok(bodies(f).every(b=>b.kind==='subject-source-unrepresentable'&&b.accountId==='bob'));assert.equal(rows(f,'release_seoul_dirty_spaces').length,0);clean(f);
});
test('domain without a live claim retains audit/block success without source or historical account scan',async t=>{const f=await setup(t);(await f.raw.prepare("UPDATE account_emails SET revoked_at=? WHERE id='e2'").run(at-1));for(let n=0;n<600;n++)(await f.raw.prepare("INSERT INTO account_emails VALUES(?,'bob','bob@example.com','example.com',?,?)").run('old:'+n,at-2,at-1));await domain(f)();assert.equal(rows(f,'email_blocks').length,1);assert.equal(rows(f,'revocations').length,1);assert.equal(sources(f).length,0);assert.equal(rows(f,'release_seoul_account_exclusions').length,0);clean(f);});
test('large revoked member/API history is excluded before bounded live discovery',async t=>{const f=await setup(t);for(let n=1;n<=600;n++)api(f,'old:'+n,n);(await f.raw.prepare("UPDATE credentials SET revoked_at=? WHERE membership_id='m2'").run(at-1));api(f,'api:live',601);const act=await scim(f);await act('m2');assert.deepEqual(bodies(f).map(b=>b.id).sort(),['api:live','m2']);assert.equal(rows(f,'release_seoul_account_exclusions').length,0);clean(f);});
test('bounded domain and SCIM probes use exact live indexes and raw Space scope',async t=>{for(const kind of ['domain','deactivate']){const f=await setup(t);api(f,'api:live');const act=kind==='domain'?domain(f):await scim(f);await act('m2');const request=f.calls.find(r=>r.statements.some(s=>s.sql.includes('INSERT INTO release_seoul_command_attempts'))),count=request.statements.find(s=>s.sql.includes('SET membership_count=')),plan=(await f.raw.prepare('EXPLAIN QUERY PLAN '+count.sql).all(...count.values)).map(r=>r.detail);assert.ok(plan.some(r=>r.includes(kind==='domain'?'release_seoul_command_live_email_credentials':'release_seoul_workspace_live_credentials')&&r.includes('revoked_at=?')),JSON.stringify(plan));if(kind==='domain'){assert.ok(plan.some(r=>r.includes('release_seoul_command_live_memberships')&&r.includes('revoked_at=?')),JSON.stringify(plan));const claim=request.statements.find(s=>s.sql.includes('SET account_id=(SELECT account_id FROM account_emails'));assert.ok((await f.raw.prepare('EXPLAIN QUERY PLAN '+claim.sql).all(...claim.values)).some(r=>r.detail.includes('one_live_email_claim')));}clean(f);}});
for(const kind of ['email','domain','deactivate','delete','space'])test('execution-time expiration denies original '+kind+' mutation without capture',async t=>{const f=await setup(t);api(f,'api:live');const act=kind==='email'?await link(f):kind==='domain'?domain(f):kind==='space'?async ()=>f.memory.createSpace(f.token,{name:'Expired'}):await scim(f,kind);const method=kind==='delete'?'ordinaryStatements':'ordinaryCommand',original=f.capture[method].bind(f.capture);f.capture[method]=async (...args)=>{(await f.db.setClock(()=>at+(['deactivate','delete'].includes(kind)?31*86400000:1000000)));return original(...args);};await assert.rejects(()=>act('m2'));assert.equal(sources(f).length,0);assert.equal(rows(f,'release_seoul_account_exclusions').length,0);assert.equal((await f.raw.prepare("SELECT revoked_at FROM memberships WHERE id='m2'").get()).revoked_at,null);clean(f);});
test('Space post-read expiration retains committed creation/source and denies the response',async t=>{const f=await setup(t),original=f.capture.ordinaryCommand.bind(f.capture);f.capture.ordinaryCommand=async(...args)=>{const result=await original(...args);(await f.db.setClock(()=>at+1000000));return result;};await assert.rejects(()=>f.memory.createSpace(f.token,{name:'Committed'}),MemoryDenied);assert.equal(bodies(f).length,1);const [b]=bodies(f);assert.ok((await f.raw.prepare('SELECT id FROM spaces WHERE id=?').get(b.id)));clean(f);});

for(const recursive of ['ON','OFF'])for(const eventType of ['email.revoked','email.verified'])test('actual lifecycle consumption IGNORE and copied positive state retain semantics; '+recursive+'/'+eventType,async t=>{const f=await setup(t,recursive),act=await link(f);const event={version:2,id:'publisher:late',sequence:1,issuer,subject:'late-alias',type:eventType,occurredAt:at-1,email:'linked@example.com'};await receiveLifecycle(f.adapter,()=>at,event,JSON.stringify(event),at);(await f.raw.prepare('INSERT INTO provider_identities VALUES(?,?,?,?)').run(issuer,'late-alias','bob',at));if(eventType==='email.revoked'){await assert.rejects(act,IdentityDenied);assert.equal(rows(f,'email_consumptions').length,0);assert.equal((await f.raw.prepare("SELECT count(*) n FROM account_emails WHERE address='linked@example.com'").get()).n,0);assert.equal(sources(f).length,0);}else{const id=await act(),core=bodies(f);assert.equal(core.length,3);assert.ok(core.every(b=>b.liveClaim.id===id&&b.effect.type==='entity-head'&&b.effect.disposition==='changed'));assert.deepEqual(core.find(b=>b.subject==='late-alias').lifecycle,{state:'event',eventId:event.id,sequence:1,kind:eventType,occurredAtMs:at-1});}clean(f);});
test('0032 preserves every populated0031 row and pre-existing object',async t=>{const f=await fixture();t.after(()=>f.db.close());f.raw=f.db.raw;for(const file of ['0026_seoul-projection-schema.sql','0027_seoul-projection-capture-schema.sql','0028_seoul-projection-bootstrap-schema.sql','0029_seoul-projection-preparation-schema.sql','0030_seoul-projection-workspace-schema.sql','0031_seoul-projection-provider-schema.sql'])(await f.raw.exec(readFileSync(new URL('../../migrations/'+file,import.meta.url),'utf8')));(await f.raw.prepare("INSERT INTO release_seoul_authority_changes(source_command_id,stream_kind,stream_key,event_id,record_bytes,created_at) VALUES('retained','credential','old','00000000-0000-4000-8000-000000000001','{}',?)").run(at));const objects=(await f.raw.prepare("SELECT name,type,sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' ORDER BY name").all()),snapshot=async table=>(await f.raw.prepare('SELECT * FROM '+table).all()).map(r=>JSON.stringify(r)).sort(),before=new Map(objects.filter(o=>o.type==='table'&&o.name!=='release_meta').map(o=>[o.name,snapshot(o.name)]));(await f.raw.exec(readFileSync(new URL('../../migrations/0032_seoul-projection-command-schema.sql',import.meta.url),'utf8')));for(const [table,data] of before)assert.deepEqual(snapshot(table),data,table);for(const o of objects)assert.deepEqual((await f.raw.prepare('SELECT name,type,sql FROM sqlite_master WHERE name=?').get(o.name)),o);assert.equal((await f.raw.prepare('SELECT version FROM release_meta').get()).version,32);assert.deepEqual((await f.raw.prepare('PRAGMA foreign_key_check').all()),[]);});

for(const kind of ['email','deactivate','delete','space'])test('unsupported mappings preserve exact '+kind+' central result with affected account exclusion',async t=>{const f=await setup(t),account=kind==='space'?'alice':'bob',act=kind==='email'?await link(f):kind==='space'?async ()=>f.memory.createSpace(f.token,{name:'Still created',organizationId:'org'}):await scim(f,kind);(await f.raw.prepare('INSERT INTO provider_identities VALUES(?,?,?,?)').run('https://foreign.example','opaque',account,at));const result=await act('m2');if(kind==='email')assert.ok((await f.raw.prepare('SELECT id FROM email_consumptions WHERE id=?').get(result)));if(kind==='space')assert.ok((await f.raw.prepare('SELECT id FROM spaces WHERE id=?').get(result.id)));if(kind==='deactivate')assert.deepEqual(result,{id:'m2',userName:'bob@example.com',active:0});if(kind==='delete')assert.ok((await f.raw.prepare("SELECT membership_id FROM release_scim_deletions WHERE membership_id='m2'").get()));assert.deepEqual(rows(f,'release_seoul_account_exclusions').map(r=>r.account_id),[account]);assert.ok(bodies(f).every(b=>b.kind==='subject-source-unrepresentable'&&b.accountId===account));assert.equal(rows(f,'release_seoul_dirty_spaces').length,0);clean(f);});
test('personal PAT/session-only state is not a SCIM membership child and constructor rejects other database capture',async t=>{const f=await setup(t);assert.throws(()=>new MemoryService(f.db,()=>at,f.capture),{message:'seoul_capture_database_mismatch'});const bare=new IdentityService(f.adapter,()=>at);assert.ok(await bare.getAccount(f.other));api(f,'api:live');const act=await scim(f);await act('m2');assert.equal((await f.raw.prepare("SELECT revoked_at FROM credentials WHERE id='session:bob'").get()).revoked_at,null);assert.equal((await f.raw.prepare("SELECT revoked_at FROM credentials WHERE id='key:alice'").get()).revoked_at,null);assert.deepEqual(bodies(f).map(b=>b.id).sort(),['api:live','m2']);clean(f);});
test('retained block receipt never hides a true later live-claim domain revocation',async t=>{const f=await setup(t),bare=new IdentityService(f.adapter,()=>at);await bare.unlinkEmail(f.other,'e2');const oldReceipt=(await f.raw.prepare("SELECT id FROM revocations WHERE kind='self' AND email_id='e2'").get()).id;(await f.raw.prepare("INSERT INTO account_emails VALUES('new:e2','bob','bob@example.com','example.com',?,NULL)").run(at));(await f.raw.prepare("INSERT INTO memberships VALUES('new:m2','org','bob','new:e2','member',?,NULL)").run(at+100000));(await f.raw.prepare("INSERT INTO credentials(id,account_id,membership_id,email_id,kind,token_digest,expires_at,permission) VALUES('new:api','bob','new:m2','new:e2','api_key',?,?,'read')").run('f'.repeat(64),at+100000));const act=domain(f);(await f.raw.prepare("INSERT INTO email_blocks(address,domain_id,revocation_id,created_at) VALUES('bob@example.com','domain',?,?)").run(oldReceipt,at));await act();assert.equal((await f.raw.prepare("SELECT revocation_id FROM email_blocks WHERE address='bob@example.com'").get()).revocation_id,oldReceipt);const core=bodies(f);assert.equal(core.length,4);assert.ok(core.every(b=>b.origin.receiptId!==oldReceipt));assert.deepEqual(core.filter(b=>b.kind==='email-source').map(b=>b.changedClaim.id),['new:e2','new:e2']);assert.deepEqual(core.filter(b=>b.kind!=='email-source').map(b=>b.id).sort(),['new:api','new:m2']);clean(f);});
