import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {fixture,at} from './db-sqlite.mjs';
import {createDurableDatabase} from '../../src/durable-sql/client.ts';
import {SqlDatabaseEngine} from '../../src/durable-sql/engine.ts';
import {createSeoulProjectionPreparer} from '../../src/release/seoul-projection-preparer.ts';
import {prepareSeoulHeadCandidate} from '../../src/release/seoul-projection-source-codec.ts';

const schema=new URL('../../seoul-projection-target-manifest-schema.sql',import.meta.url),migration=new URL('../../migrations/0035_seoul-projection-target-manifest-schema.sql',import.meta.url),moduleUrl=new URL('../../src/release/seoul-projection-target-writer.ts',import.meta.url);
const uuid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const command=(n,expectedRevision=null,selected=true,spaceId='s1')=>({commandId:uuid(n),spaceId,expectedRevision,selected,operatorReference:'fixture:operator'});
const tableNames=['release_seoul_authority_changes','release_seoul_authority_heads','release_seoul_targets','release_seoul_target_receipts','release_seoul_dirty_spaces','release_seoul_prepared_sources','release_seoul_projection_events','release_seoul_projection_deliveries','release_seoul_projection_lock','release_seoul_published_snapshots','release_seoul_target_attempt'];
const rows=async (f,name)=>(await f.raw.prepare('SELECT * FROM '+name+' ORDER BY rowid').all()).map(r=>({...r}));
const snapshot=f=>Object.fromEntries(tableNames.map(n=>[n,rows(f,n)]));
const oldMigrations=['0026_seoul-projection-schema.sql','0027_seoul-projection-capture-schema.sql','0028_seoul-projection-bootstrap-schema.sql','0029_seoul-projection-preparation-schema.sql','0030_seoul-projection-workspace-schema.sql','0031_seoul-projection-provider-schema.sql','0032_seoul-projection-command-schema.sql','0033_seoul-projection-provider-v1-schema.sql','0034_seoul-projection-target-schema.sql'];
async function setup(t,recursive='ON',install=true,mode='durable-sql'){
 let now=at;const f=await fixture({clock:()=>now});t.after(()=>f.db.close());f.raw=f.db.raw;f.advance=ms=>{now+=ms;};
 for(const file of oldMigrations)(await f.raw.exec(readFileSync(new URL('../../migrations/'+file,import.meta.url),'utf8')));
 assert.equal((await f.raw.prepare('SELECT version FROM release_meta').get()).version,34);(await f.raw.exec('PRAGMA recursive_triggers='+recursive));f.calls=[];f.batches=0;f.reads=0;
 if(!install)return f;
 assert.ok(existsSync(schema),'target schema file exists');assert.equal(readFileSync(migration,'utf8'),'-- Forward SaaS migration 35: seoul-projection-target-manifest-schema.sql\n'+readFileSync(schema,'utf8'));(await f.raw.exec(readFileSync(migration,'utf8')));assert.equal((await f.raw.prepare('SELECT version FROM release_meta').get()).version,35);
 const storage={sql:{exec(sql,...values){const statement=(await f.raw.prepare(sql)),result=statement.all(...values),readonly=statement.columns().length>0&&/^(SELECT|WITH|PRAGMA)\b/i.test(sql.trim());return {rowsWritten:readonly?0:Number((await f.raw.prepare('SELECT changes() n').get()).n),toArray:()=>result,[Symbol.iterator]:()=>result[Symbol.iterator]()};}},transactionSync(fn){(await f.raw.exec('BEGIN IMMEDIATE'));try{const r=fn();(await f.raw.exec('COMMIT'));return r;}catch(e){(await f.raw.exec('ROLLBACK'));throw e;}}};
 f.engine=new SqlDatabaseEngine(storage,{objectName:'sql:staging:control:1'});f.engine.initialize();(await f.raw.prepare('INSERT INTO durable_sql_state VALUES(1,?,?,?,?,?,?,?)').run('staging','control','control',1,'ready','a'.repeat(64),'b'.repeat(64)));
 const identity={deploymentId:'staging',databaseId:'control',kind:'control',epoch:1};
 const execute=async request=>{f.calls.push(structuredClone(request));const batch=request.statements.length>1;if(batch){f.batches++;await f.beforeBatch?.(request);}else{f.reads++;await f.beforeRead?.(request);}const result=mode==='durable-sql'?f.engine.execute(request):storage.transactionSync(async ()=>request.statements.map(async s=>{const q=(await f.raw.prepare(s.sql)),r=q.all(...s.values);return {success:true,results:r,meta:{changes:0}};}));f.maximumResponseBytes=Math.max(f.maximumResponseBytes??0,Buffer.byteLength(JSON.stringify(result)));if(batch)await f.afterCommit?.(request,result);else await f.afterRead?.(request,result);return result;};
 const owned=new WeakMap();async function prepare(sql,values=[]){const statement={bind(...parameters){return prepare(sql,parameters);},async first(){return (await execute({identity,statements:[{sql,values,mode:'first'}]}))[0].results[0]??null;},async all(){return (await execute({identity,statements:[{sql,values,mode:'all'}]}))[0];},async run(){return this.all();}};owned.set(statement,{sql,values,mode:'all'});return statement;}
 f.adapter=mode==='durable-sql'?createDurableDatabase({execute},identity):{prepare,batch(statements){return execute({identity,statements:statements.map(s=>owned.get(s))});},withSession(){return {prepare};}};assert.ok(existsSync(moduleUrl),'target writer module exists');const {createSeoulProjectionTargetWriter}=await import(moduleUrl);f.writer=createSeoulProjectionTargetWriter(f.adapter,mode);return f;
}
async function clean(f){assert.deepEqual(rows(f,'release_seoul_target_manifest_attempt'),[]);assert.deepEqual(rows(f,'release_seoul_target_attempt'),[]);assert.deepEqual((await f.raw.prepare('PRAGMA foreign_key_check').all()),[]);assert.equal((await f.raw.prepare('SELECT state FROM release_seoul_projection_state').get()).state,'backfill-required');}
const sourceByEvent=async (f,event)=>({...(await f.raw.prepare('SELECT revision,source_command_id,stream_kind,stream_key,event_id,record_bytes,created_at FROM release_seoul_authority_changes WHERE event_id=?').get(event))});


const manifestTables=['manifests','manifest_members','manifest_control','manifest_pages','manifest_steps','manifest_seals','manifest_completions','manifest_cancellations','manifest_attempt'].map(s=>'release_seoul_target_'+s);
const manifest=(n,spaceIds=[],expectedGeneration=null)=>({version:1,manifestId:uuid(n),expectedGeneration,operatorReference:'fixture:operator',spaceIds});
const ref=(n,generation=1)=>({manifestId:uuid(n),generation});
async function coordinator(f,mode='durable-sql'){const {createSeoulProjectionTargetManifest}=await import('../../src/release/seoul-projection-target-manifest.ts');return createSeoulProjectionTargetManifest(f.adapter,mode);}

async function inventory(m,n,generation=1){for(const phase of ['desired','omitted']){let afterSpaceId=null,pageNo=1;for(;;){const page=await m.readPlanningPage({...ref(n,generation),phase,afterSpaceId});assert.equal(page.status,'planning_page');const result=await m.appendPlanningPage({...ref(n,generation),phase,pageNo,afterSpaceId,steps:page.steps.map((s,i)=>({...s,commandId:uuid(n*10000+(phase==='desired'?0:5000)+pageNo*32+i)}))});assert.equal(result.status,'page_recorded');if(result.terminal)break;afterSpaceId=page.steps.at(-1).spaceId;pageNo++;}}assert.equal((await m.seal(ref(n,generation))).status,'sealed');}

const allSnapshot=f=>({...snapshot(f),...Object.fromEntries(manifestTables.map(n=>[n,rows(f,n)]))});
const prepareOne=async(f,m,n=100)=>{await m.publish(manifest(n,['s1']));await inventory(m,n);};
for(const mode of ['native-d1','durable-sql'])for(const recursive of ['ON','OFF'])test('obsolete direct preflight and bare old target/source/head paths are fenced; '+mode+' '+recursive,async t=>{
 const f=await setup(t,recursive,true,mode);await f.writer.setTarget(command(1));const old=f.calls.find(c=>c.statements.length===10),m=await coordinator(f,mode);await m.publish(manifest(100,['s1']));const before=allSnapshot(f);assert.throws(()=>f.engine.execute(old),/manifest|current context/);await assert.rejects(async()=>(await f.raw.exec("UPDATE release_seoul_targets SET selected=selected")),/manifest|current context/);await assert.rejects(async()=>(await f.raw.exec("UPDATE release_seoul_authority_heads SET payload_sha256='"+'a'.repeat(64)+"' WHERE stream_kind='target'")),/manifest|current context/);await assert.rejects(async()=>(await f.raw.prepare("INSERT INTO release_seoul_authority_changes(source_command_id,stream_kind,stream_key,event_id,record_bytes,created_at) VALUES(?,'target','s1',?,'{}',?)").run(uuid(200),uuid(201),at)),/manifest|current context/);assert.deepEqual(allSnapshot(f),before);assert.equal((await f.writer.setTarget(command(1))).status,'historical_commit');clean(f);
});
for(const mode of ['native-d1','durable-sql'])for(const action of ['supersede','cancel'])test('late '+action+' aborts one13 attempt and fresh absence stays uncertain; '+mode,async t=>{
 const f=await setup(t,'ON',true,mode),m=await coordinator(f,mode);await prepareOne(f,m);const beforeSources=rows(f,'release_seoul_authority_changes');f.beforeBatch=async request=>{if(request.statements.length!==13)return;f.beforeBatch=undefined;if(action==='supersede')await m.publish(manifest(101,['s1'],1));else await m.cancel({...ref(100),cancellationId:uuid(199),operatorReference:'cancel:test'});};const result=await f.writer.setManifestStep({...ref(100),spaceId:'s1'});assert.equal(result.status,'uncertain');assert.deepEqual(rows(f,'release_seoul_authority_changes'),beforeSources);assert.equal(f.calls.filter(c=>c.statements.length===13).length,1);clean(f);
});
for(const mode of ['native-d1','durable-sql'])test('committed13 then superseded lost ACK returns separate historical receipt; '+mode,async t=>{
 const f=await setup(t,'OFF',true,mode),m=await coordinator(f,mode);await prepareOne(f,m);f.afterCommit=async request=>{if(request.statements.length!==13)return;f.afterCommit=undefined;await m.publish(manifest(101,[],1));throw Error('lost ACK after supersession');};const result=await f.writer.setManifestStep({...ref(100),spaceId:'s1'});assert.equal(result.status,'historical_commit');assert.equal(result.manifest.currentStatus,'superseded');assert.equal(result.manifest.currentGeneration,2);assert.equal(rows(f,'release_seoul_target_receipts').length,1);assert.equal(f.calls.filter(c=>c.statements.length===13).length,1);clean(f);
});
for(const mode of ['native-d1','durable-sql'])for(const recursive of ['ON','OFF'])test('verified unchanged source remains stable while real preparation finalizes exact head; '+mode+' '+recursive,async t=>{
 const f=await setup(t,recursive,true,mode);await f.writer.setTarget(command(1));const m=await coordinator(f,mode);await prepareOne(f,m);const written=await f.writer.setManifestStep({...ref(100),spaceId:'s1'});assert.equal(written.receipt.outcome,'unchanged');assert.equal((await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null})).status,'page_verified');const prep=await createSeoulProjectionPreparer(f.adapter,mode).prepare(1);assert.equal(prep.status,'prepared');assert.equal(rows(f,'release_seoul_authority_heads')[0].payload_sha256,prep.sourceChangeSha256);assert.equal((await m.complete(ref(100))).status,'completed');assert.equal((await m.observeAgreement({...ref(100),configuredSpaceIds:['s1']})).status,'agreed');assert.equal((await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null})).status,'already_verified');clean(f);
});
for(const mode of ['native-d1','durable-sql'])for(const table of ['release_seoul_target_manifest_attempt','release_seoul_target_attempt'])test('consumed13 cleanup IGNORE rolls back entire target mutation; '+mode+' '+table,async t=>{
 const f=await setup(t,'OFF',true,mode),m=await coordinator(f,mode);await prepareOne(f,m);const before=allSnapshot(f);(await f.raw.exec('CREATE TRIGGER injected_ignore BEFORE DELETE ON '+table+' BEGIN SELECT RAISE(IGNORE); END'));assert.equal((await f.writer.setManifestStep({...ref(100),spaceId:'s1'})).status,'uncertain');assert.deepEqual(allSnapshot(f),before);assert.equal(f.calls.filter(c=>c.statements.length===13).length,1);clean(f);
});
for(const mode of ['native-d1','durable-sql'])for(const [table,action]of [['release_seoul_target_manifests','INSERT'],['release_seoul_target_manifest_members','INSERT'],['release_seoul_target_manifest_control','UPDATE'],['release_seoul_target_manifest_attempt','DELETE']])test('publication detects ignored '+table+' '+action+'; '+mode,async t=>{
 const f=await setup(t,'ON',true,mode),m=await coordinator(f,mode),before=allSnapshot(f);(await f.raw.exec('CREATE TRIGGER injected_ignore BEFORE '+action+' ON '+table+' BEGIN SELECT RAISE(IGNORE); END'));assert.equal((await m.publish(manifest(100,['s1']))).status,'uncertain');assert.deepEqual(allSnapshot(f),before);assert.equal(f.batches,1);clean(f);
});
test('page exact replay, conflicting child and lost acknowledgement preserve immutable IDs',async t=>{
 const f=await setup(t),m=await coordinator(f);await m.publish(manifest(100,['s1','s2']));const input={...ref(100),phase:'desired',pageNo:1,afterSpaceId:null,steps:[{spaceId:'s1',commandId:uuid(200),expectedRevision:null},{spaceId:'s2',commandId:uuid(201),expectedRevision:null}]};f.afterCommit=()=>{throw Error('lost page ACK');};assert.equal((await m.appendPlanningPage(input)).status,'already_recorded');f.afterCommit=undefined;assert.equal((await m.appendPlanningPage(input)).status,'already_recorded');assert.equal((await m.appendPlanningPage({...input,steps:[input.steps[0],{...input.steps[1],commandId:uuid(202)}]})).status,'page_conflict');assert.equal(rows(f,'release_seoul_target_manifest_steps').length,2);clean(f);
});
test('missing desired Space retains exact step and becomes applicable after independent Space creation',async t=>{
 const f=await setup(t),m=await coordinator(f);await m.publish(manifest(100,['later']));await inventory(m,100);assert.equal((await f.writer.setManifestStep({...ref(100),spaceId:'later'})).status,'target_missing');assert.equal((await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null})).status,'not_complete');(await f.raw.prepare("INSERT INTO spaces SELECT ?,'Later Space',account_id,organization_id,security_mode,created_at,actor_credential_id FROM spaces WHERE id='s1'").run('later'));assert.equal((await f.writer.setManifestStep({...ref(100),spaceId:'later'})).status,'committed');clean(f);
});
for(const recursive of ['ON','OFF'])test('all occupied durable manifest rows reject replacement/update/delete; '+recursive,async t=>{
 const f=await setup(t,recursive),m=await coordinator(f);await m.publish(manifest(100,['s1']));await inventory(m,100);await f.writer.setManifestStep({...ref(100),spaceId:'s1'});await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null});await m.complete(ref(100));await m.cancel({...ref(100),cancellationId:uuid(199),operatorReference:'cancel:test'});const before=allSnapshot(f);for(const name of manifestTables.filter(n=>n!=='release_seoul_target_manifest_attempt')){await assert.rejects(async()=>(await f.raw.exec('UPDATE '+name+' SET '+(name.endsWith('_control')?'singleton=singleton':'generation=generation'))),/immutable|predecessor/);await assert.rejects(async()=>(await f.raw.exec('DELETE FROM '+name)),/retained/);if(rows(f,name).length)await assert.rejects(async()=>(await f.raw.exec('INSERT OR REPLACE INTO '+name+' SELECT * FROM '+name+' LIMIT 1')),/manifest|current context/);}assert.deepEqual(allSnapshot(f),before);
});
test('whole35 installer transaction rolls back DDL and metadata after injected late failures',async t=>{
 for(const where of ['ddl','postflight']){const f=await setup(t,'ON',false),objects=(await f.raw.prepare("SELECT name,type,sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' ORDER BY name").all());(await f.raw.exec('BEGIN IMMEDIATE'));await assert.rejects(async()=>{(await f.raw.exec(readFileSync(migration,'utf8')));if(where==='ddl')(await f.raw.exec('CREATE TABLE spaces(id TEXT)'));else (await f.raw.exec('SELECT abs(-9223372036854775808)'));});(await f.raw.exec('ROLLBACK'));assert.equal((await f.raw.prepare('SELECT version FROM release_meta').get()).version,34);assert.deepEqual((await f.raw.prepare("SELECT name,type,sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' ORDER BY name").all()),objects);assert.deepEqual((await f.raw.prepare('PRAGMA foreign_key_check').all()),[]);}
});

test('K1057 selected omissions plus1057 retained false rows reconcile by indexed keyset pages',async t=>{
 const f=await setup(t,'OFF',true,'durable-sql'),selected=1057,negative=1057;for(let i=0;i<selected+negative;i++){const space='legacy:'+String(i).padStart(5,'0');(await f.raw.prepare("INSERT INTO spaces SELECT ?,'Legacy Space',account_id,organization_id,security_mode,created_at,actor_credential_id FROM spaces WHERE id='s1'").run(space));assert.equal((await f.writer.setTarget(command(30000+i,null,i<selected,space))).status,'committed');f.calls.length=0;}
 const measures={maxRequestBytes:0,maxStatementBytes:0,maxStatements:0,maxParameters:0,planningPages:0,verificationPages:0,steps:0},plans=[];const measure=async request=>{measures.maxRequestBytes=Math.max(measures.maxRequestBytes,Buffer.byteLength(JSON.stringify(request)));measures.maxStatements=Math.max(measures.maxStatements,request.statements.length);for(const s of request.statements){measures.maxStatementBytes=Math.max(measures.maxStatementBytes,Buffer.byteLength(s.sql));measures.maxParameters=Math.max(measures.maxParameters,s.values.length);if(s.sql.includes('expectedRevision FROM release_seoul_targets t INDEXED BY release_seoul_targets_selected_space'))plans.push((await f.raw.prepare('EXPLAIN QUERY PLAN '+s.sql).all(...s.values)).map(x=>x.detail).join('\n'));}f.calls.length=0;};f.beforeBatch=measure;f.beforeRead=measure;
 const m=await coordinator(f);await m.publish(manifest(100,['s1']));await inventory(m,100);let afterSpaceId=null;for(;;){const page=await m.readSteps({...ref(100),afterSpaceId});assert.equal(page.status,'steps');for(const s of page.steps){assert.equal((await f.writer.setManifestStep({...ref(100),spaceId:s.spaceId})).status,'committed');measures.steps++;}if(page.terminal)break;afterSpaceId=page.steps.at(-1).spaceId;}
 afterSpaceId=null;let pageNo=1;for(;;){const page=await m.readSteps({...ref(100),afterSpaceId}),v=await m.verifyPage({...ref(100),pageNo,afterSpaceId});assert.equal(v.status,'page_verified');measures.verificationPages++;if(v.terminal)break;afterSpaceId=page.steps.at(-1).spaceId;pageNo++;}
 assert.equal((await m.complete(ref(100))).status,'completed');assert.equal((await m.observeAgreement({...ref(100),configuredSpaceIds:['s1']})).status,'agreed');assert.equal(measures.steps,selected+1);assert.equal((await f.raw.prepare('SELECT count(*) n FROM release_seoul_targets WHERE selected=0').get()).n,selected+negative);assert.equal(rows(f,'release_seoul_target_manifest_seals')[0].total_count,selected+1);
 assert.ok(plans.some(p=>/SCAN t USING INDEX release_seoul_targets_selected_space/.test(p)));assert.ok(plans.some(p=>/SEARCH t USING INDEX release_seoul_targets_selected_space \(space_id>\?\)/.test(p)));assert.ok(plans.every(p=>p.includes('release_seoul_target_manifest_members')));assert.ok(measures.maxRequestBytes+4096<1048576);assert.ok(measures.maxStatementBytes<100000);assert.ok(measures.maxParameters<=100);measures.planningPages=(await f.raw.prepare("SELECT count(*) n FROM release_seoul_target_manifest_pages WHERE phase<>'verify'").get()).n;t.diagnostic('Manifest indexed K>1024 bounds '+JSON.stringify({...measures,maxResponseBytes:f.maximumResponseBytes,selected,retainedFalse:negative}));clean(f);
});

for(const mode of ['native-d1','durable-sql'])for(const operation of ['page','seal','verify','complete','cancel'])for(const cleanup of [false,true])test('ignored '+operation+' '+(cleanup?'cleanup':'physical row')+' leaves no partial record; '+mode,async t=>{
 const f=await setup(t,'OFF',true,mode),m=await coordinator(f,mode);await m.publish(manifest(100));let invoke,table;
 if(operation==='page'){table='release_seoul_target_manifest_pages';invoke=()=>m.appendPlanningPage({...ref(100),phase:'desired',pageNo:1,afterSpaceId:null,steps:[]});}
 else{if(operation!=='seal')await inventory(m,100);else for(const phase of ['desired','omitted'])await m.appendPlanningPage({...ref(100),phase,pageNo:1,afterSpaceId:null,steps:[]});if(operation==='complete')await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null});table='release_seoul_target_manifest_'+({seal:'seals',verify:'pages',complete:'completions',cancel:'cancellations'}[operation]);invoke=operation==='seal'?()=>m.seal(ref(100)):operation==='verify'?()=>m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null}):operation==='complete'?()=>m.complete(ref(100)):()=>m.cancel({...ref(100),cancellationId:uuid(199),operatorReference:'cancel:test'});}
 const before=allSnapshot(f),batches=f.batches;(await f.raw.exec('CREATE TRIGGER injected_ignore BEFORE '+(cleanup?'DELETE ON release_seoul_target_manifest_attempt':'INSERT ON '+table)+' BEGIN SELECT RAISE(IGNORE); END'));assert.equal((await invoke()).status,'uncertain');assert.equal(f.batches,batches+1);assert.deepEqual(allSnapshot(f),before);clean(f);
});
for(const recursive of ['ON','OFF'])test('same and foreign retained stage blocks every method before historical decisions; '+recursive,async t=>{
 const f=await setup(t,recursive),m=await coordinator(f);await f.writer.setTarget(command(1));const old=f.calls.find(c=>c.statements.length===10);f.beforeBatch=()=>{throw Error('transport did not settle');};assert.equal((await m.publish(manifest(100))).status,'uncertain');f.beforeBatch=undefined;const publish=f.calls.filter(c=>c.statements.length>1).at(-1),stage=publish.statements[0];f.engine.execute({...publish,statements:[stage]});const before=allSnapshot(f),calls=[()=>m.publish(manifest(100)),()=>m.readManifest(ref(100)),()=>m.readPlanningPage({...ref(100),phase:'desired',afterSpaceId:null}),()=>m.appendPlanningPage({...ref(100),phase:'desired',pageNo:1,afterSpaceId:null,steps:[]}),()=>m.seal(ref(100)),()=>m.readSteps({...ref(100),afterSpaceId:null}),()=>m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null}),()=>m.complete(ref(100)),()=>m.cancel({...ref(100),cancellationId:uuid(199),operatorReference:'cancel:test'}),()=>m.observeAgreement({...ref(100),configuredSpaceIds:[]}),()=>f.writer.setTarget(command(1)),()=>f.writer.setManifestStep({...ref(100),spaceId:'s1'})];for(const call of calls)assert.equal((await call()).status,'staging_retained');for(const foreign of [false,true]){const next=structuredClone(stage);if(foreign)next.values[0]=uuid(200);next.sql=next.sql.replace('INSERT INTO','INSERT OR REPLACE INTO');assert.throws(()=>f.engine.execute({...publish,statements:[next]}));}assert.throws(()=>f.engine.execute({...old,statements:[old.statements[0]]}),/manifest/);assert.deepEqual(allSnapshot(f),before);
});
for(const mode of ['native-d1','durable-sql'])test('ignored one page child rolls back its same-count page record; '+mode,async t=>{
 const f=await setup(t,'ON',true,mode),m=await coordinator(f,mode);await m.publish(manifest(100,['s1','s2']));const before=allSnapshot(f);(await f.raw.exec("CREATE TRIGGER ignore_second_step BEFORE INSERT ON release_seoul_target_manifest_steps WHEN NEW.space_id='s2' BEGIN SELECT RAISE(IGNORE); END"));assert.equal((await m.appendPlanningPage({...ref(100),phase:'desired',pageNo:1,afterSpaceId:null,steps:[{spaceId:'s1',commandId:uuid(200),expectedRevision:null},{spaceId:'s2',commandId:uuid(201),expectedRevision:null}]})).status,'uncertain');assert.deepEqual(allSnapshot(f),before);clean(f);
});
test('maximum32 target proofs stay inside actual read and write envelopes',async t=>{
 const f=await setup(t,'ON',true,'durable-sql'),ids=Array.from({length:32},(_,i)=>'s'+String(i).padStart(3,'0')+'x'.repeat(124));for(let i=0;i<ids.length;i++){(await f.raw.prepare("INSERT INTO spaces SELECT ?,'Maximum Space',account_id,organization_id,security_mode,created_at,actor_credential_id FROM spaces WHERE id='s1'").run(ids[i]));assert.equal((await f.writer.setTarget({...command(300+i,null,true,ids[i]),operatorReference:'a'.repeat(256)})).status,'committed');}
 const m=await coordinator(f);await m.publish({...manifest(100,ids),operatorReference:'b'.repeat(256)});await inventory(m,100);for(const spaceId of ids)assert.equal((await f.writer.setManifestStep({...ref(100),spaceId})).status,'committed');assert.equal((await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null})).status,'page_verified');assert.equal((await m.complete(ref(100))).status,'completed');const requests=f.calls.filter(c=>c.statements.length>1);const metrics={requestBytes:Math.max(...requests.map(c=>Buffer.byteLength(JSON.stringify(c)))),responseBytes:f.maximumResponseBytes,sourceBytes:Math.max(...rows(f,'release_seoul_authority_changes').map(r=>Buffer.byteLength(r.record_bytes))),sqlBytes:Math.max(...requests.flatMap(c=>c.statements.map(s=>Buffer.byteLength(s.sql)))),parameters:Math.max(...requests.flatMap(c=>c.statements.map(s=>s.values.length)))};assert.ok(metrics.requestBytes+4096<1048576);assert.ok(metrics.responseBytes<1048576);assert.ok(metrics.sqlBytes<100000);assert.ok(metrics.parameters<=100);t.diagnostic('Manifest maximum32 real proofs '+JSON.stringify(metrics));clean(f);
});

test('readSteps labels history from its final coherent target/control observation',async t=>{
 const f=await setup(t),m=await coordinator(f);await prepareOne(f,m);await f.writer.setManifestStep({...ref(100),spaceId:'s1'});await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null});await m.complete(ref(100));let raced=false;
 f.beforeRead=async request=>{if(raced||!request.statements[0].sql.includes('ordinal'))return;raced=true;f.beforeRead=undefined;await m.publish(manifest(101,[],1));await inventory(m,101,2);await f.writer.setManifestStep({...ref(101,2),spaceId:'s1'});};const page=await m.readSteps({...ref(100),afterSpaceId:null});assert.equal(raced,true);assert.equal(page.currentStatus,'superseded');assert.equal(page.currentGeneration,2);assert.equal(page.steps[0].historyValid,true);assert.equal(page.steps[0].currentResultValid,false);clean(f);
});
for(const shape of ['header-only','missing-member','wrong-hash'])test('legally staged '+shape+' is not complete historical publication proof',async t=>{
 const f=await setup(t),m=await coordinator(f),input=manifest(100,['s1','s2']);f.beforeBatch=()=>{throw Error('unknown initial transport');};assert.equal((await m.publish(input)).status,'uncertain');f.beforeBatch=undefined;const request=structuredClone(f.calls.find(c=>c.statements.length>1)),prefix=shape==='header-only'?2:4;if(shape==='missing-member')request.statements[2].sql+=' AND CAST(j.key AS INTEGER)=0';if(shape==='wrong-hash')request.statements[0].values[6]='f'.repeat(64);f.engine.execute({...request,statements:request.statements.slice(0,prefix)});(await f.raw.exec('DELETE FROM release_seoul_target_manifest_attempt'));assert.equal((await m.publish(input)).status,'uncertain');assert.equal(f.calls.filter(c=>c.statements.length>1).length,1);
});

for(const mode of ['native-d1','durable-sql'])test('ordinary digest CHECKs with NUL suffix cannot suppress unrelated historical receipt or escape read bounds; '+mode,async t=>{
 const f=await setup(t,'ON',true,mode),first=await f.writer.setTarget(command(1)),later=await f.writer.setTarget(command(2,1,false)),source=sourceByEvent(f,later.receipt.resultingEventId),candidate=await prepareSeoulHeadCandidate(source),bad='a'.repeat(64)+'\0'+'x'.repeat(524288);(await f.raw.exec('BEGIN IMMEDIATE'));(await f.raw.prepare('INSERT INTO release_seoul_prepared_sources VALUES(?,?,?,?)').run(2,source.event_id,bad,'e'.repeat(64)));(await f.raw.prepare("INSERT INTO release_seoul_projection_events(event_id,source_revision,event_kind,stream_kind,stream_key,source_sha256,space_id,snapshot_seq,issued_at,expires_at,payload_bytes,payload_sha256) VALUES(?,2,'head','target','s1',?,NULL,NULL,NULL,NULL,?,?)").run(source.event_id,bad,candidate.eventText,'e'.repeat(64)));(await f.raw.prepare('INSERT INTO release_seoul_projection_deliveries(event_id) VALUES(?)').run(source.event_id));(await f.raw.prepare('UPDATE release_seoul_authority_heads SET payload_sha256=? WHERE revision=2').run(bad));(await f.raw.exec('COMMIT'));assert.deepEqual((await f.raw.prepare('PRAGMA foreign_key_check').all()),[]);const length=(await f.raw.prepare('SELECT length(payload_sha256) text_length,length(CAST(payload_sha256 AS BLOB)) byte_length FROM release_seoul_authority_heads WHERE revision=2').get());assert.equal(length.text_length,64);assert.equal(length.byte_length,524353);
 const {recoverTargetWrite}=await import('../../src/release/seoul-projection-target-internal.ts');const result=await recoverTargetWrite(f.adapter,command(1)),request=f.calls.at(-1),raw=(await f.raw.prepare(request.statements[0].sql).all(...request.statements[0].values)),bytes=Buffer.byteLength(JSON.stringify([{success:true,results:raw,meta:{changes:0}}]));t.diagnostic('NUL digest checked-storage read '+JSON.stringify({mode,rawResponseBytes:bytes,textLength:length.text_length,byteLength:length.byte_length,status:result.status}));assert.equal(result.status,'historical_commit');assert.deepEqual(result.receipt,first.receipt);assert.ok(bytes<1048576);clean(f);
});

test('agreement reports immutable completion time from its final coherent read',async t=>{
 const f=await setup(t),m=await coordinator(f);await m.publish(manifest(100));await inventory(m,100);await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null});f.advance(200);await m.complete(ref(100));f.advance(500);const agreed=await m.observeAgreement({...ref(100),configuredSpaceIds:[]});assert.equal(agreed.status,'agreed');assert.equal(agreed.completedAtMs,at+200);assert.equal(agreed.observedAtMs,at+700);clean(f);
});
test('empty historical step page takes a final current observation after supersession',async t=>{
 const f=await setup(t),m=await coordinator(f);await m.publish(manifest(100));await inventory(m,100);let raced=false;f.beforeRead=async request=>{if(raced||!request.statements[0].sql.startsWith('SELECT command_id commandId'))return;raced=true;f.beforeRead=undefined;await m.publish(manifest(101,[],1));};const page=await m.readSteps({...ref(100),afterSpaceId:null});assert.equal(raced,true);assert.equal(page.currentStatus,'superseded');assert.equal(page.currentGeneration,2);assert.deepEqual(page.steps,[]);clean(f);
});
test('planning suggestion reports supersession observed after inventory enumeration',async t=>{
 const f=await setup(t),m=await coordinator(f);await m.publish(manifest(100,['s1']));let raced=false;f.beforeRead=async request=>{if(raced||!request.statements[0].sql.startsWith('SELECT m.space_id spaceId'))return;raced=true;f.beforeRead=undefined;await m.publish(manifest(101,[],1));};const page=await m.readPlanningPage({...ref(100),phase:'desired',afterSpaceId:null});assert.equal(raced,true);assert.equal(page.status,'superseded');clean(f);
});
test('agreement independently binds canonical manifest digest as well as configured set digest',async t=>{
 const f=await setup(t),m=await coordinator(f);f.beforeBatch=()=>{throw Error('unknown transport');};await m.publish(manifest(100));f.beforeBatch=undefined;const request=structuredClone(f.calls.find(c=>c.statements.length>1));request.statements[0].values[6]='f'.repeat(64);f.engine.execute({...request,statements:request.statements.slice(0,4)});(await f.raw.exec('DELETE FROM release_seoul_target_manifest_attempt'));await inventory(m,100);await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null});await m.complete(ref(100));assert.equal((await m.observeAgreement({...ref(100),configuredSpaceIds:[]})).status,'uncertain');
});
for(const kind of ['planning','steps'])test('malformed accessor row arrays are rejected without invocation in '+kind+' reads',async t=>{
 const f=await setup(t,'ON',true,'native-d1'),m=await coordinator(f,'native-d1');await m.publish(manifest(100,['s1']));if(kind==='steps')await inventory(m,100);let invoked=0;f.afterRead=(request,response)=>{if(!request.statements[0].sql.startsWith(kind==='planning'?'SELECT m.space_id spaceId':'SELECT command_id commandId'))return;const value=response[0].results[0],rows=[];Object.defineProperty(rows,'0',{enumerable:true,get(){invoked++;return value;}});response[0].results=rows;};const value=kind==='planning'?await m.readPlanningPage({...ref(100),phase:'desired',afterSpaceId:null}):await m.readSteps({...ref(100),afterSpaceId:null});assert.equal(value.status,'uncertain');assert.equal(invoked,0);clean(f);
});
for(const mode of ['native-d1','durable-sql'])for(const operation of ['direct','planning'])test('new malformed prepared digest beneath pending head is rechecked inside '+operation+' transaction; '+mode,async t=>{
 const f=await setup(t,'ON',true,mode),first=await f.writer.setTarget(command(1)),source=sourceByEvent(f,first.receipt.resultingEventId),candidate=await prepareSeoulHeadCandidate(source),bad='a'.repeat(64)+'\0x',m=await coordinator(f,mode);if(operation==='planning')await m.publish(manifest(100,['s1']));let before;
 f.beforeBatch=async ()=>{f.beforeBatch=undefined;(await f.raw.exec('BEGIN IMMEDIATE'));(await f.raw.prepare('INSERT INTO release_seoul_prepared_sources VALUES(?,?,?,?)').run(1,source.event_id,bad,'e'.repeat(64)));(await f.raw.prepare("INSERT INTO release_seoul_projection_events(event_id,source_revision,event_kind,stream_kind,stream_key,source_sha256,space_id,snapshot_seq,issued_at,expires_at,payload_bytes,payload_sha256) VALUES(?,1,'head','target','s1',?,NULL,NULL,NULL,NULL,?,?)").run(source.event_id,bad,candidate.eventText,'e'.repeat(64)));(await f.raw.prepare('INSERT INTO release_seoul_projection_deliveries(event_id) VALUES(?)').run(source.event_id));(await f.raw.exec('COMMIT'));before=allSnapshot(f);};
 const result=operation==='direct'?await f.writer.setTarget(command(2,1,false)):await m.appendPlanningPage({...ref(100),phase:'desired',pageNo:1,afterSpaceId:null,steps:[{spaceId:'s1',commandId:uuid(200),expectedRevision:1}]});assert.equal(result.status,operation==='direct'?'target_state_invalid':'uncertain');assert.deepEqual(allSnapshot(f),before);assert.equal(rows(f,'release_seoul_authority_heads')[0].payload_sha256,null);clean(f);
});
test('seal terminal-child guards seek complete generation phase page keys',async t=>{
 const f=await setup(t),triggers=(await f.raw.prepare("SELECT name,sql FROM sqlite_master WHERE type='trigger' AND name LIKE 'target_manifest_seal_terminal%children'").all());assert.ok(triggers.length);for(const trigger of triggers){const predicate=trigger.sql.slice(trigger.sql.indexOf(' WHEN ')+6,trigger.sql.indexOf(' BEGIN ')).replaceAll('NEW.generation','1').replaceAll('NEW.desired_terminal_page','1').replaceAll('NEW.omitted_terminal_page','1'),plan=(await f.raw.prepare('EXPLAIN QUERY PLAN SELECT '+predicate).all()).map(r=>r.detail).join('\n');t.diagnostic(trigger.name+' '+plan);assert.match(plan,/SEARCH p USING INDEX [^\n]+\(generation=\? AND phase=\? AND page_no=\?\)/);assert.doesNotMatch(plan,/SEARCH p USING INDEX [^\n]+\(generation=\?\)/);}
});
for(const mode of ['native-d1','durable-sql'])test('prepared transport digest NUL suffix is independently bounded and historical recovery stays valid; '+mode,async t=>{
 const f=await setup(t,'OFF',true,mode),first=await f.writer.setTarget(command(1)),source=sourceByEvent(f,first.receipt.resultingEventId),candidate=await prepareSeoulHeadCandidate(source),bad='e'.repeat(64)+'\0'+'x'.repeat(524288);(await f.raw.exec('BEGIN IMMEDIATE'));(await f.raw.prepare('INSERT INTO release_seoul_prepared_sources VALUES(?,?,?,?)').run(1,source.event_id,candidate.sourceChangeSha256,bad));(await f.raw.prepare("INSERT INTO release_seoul_projection_events(event_id,source_revision,event_kind,stream_kind,stream_key,source_sha256,space_id,snapshot_seq,issued_at,expires_at,payload_bytes,payload_sha256) VALUES(?,1,'head','target','s1',?,NULL,NULL,NULL,NULL,?,?)").run(source.event_id,candidate.sourceChangeSha256,candidate.eventText,bad));(await f.raw.prepare('INSERT INTO release_seoul_projection_deliveries(event_id) VALUES(?)').run(source.event_id));(await f.raw.prepare('UPDATE release_seoul_authority_heads SET payload_sha256=? WHERE revision=1').run(candidate.sourceChangeSha256));(await f.raw.exec('COMMIT'));const {recoverTargetWrite}=await import('../../src/release/seoul-projection-target-internal.ts'),result=await recoverTargetWrite(f.adapter,command(1));assert.equal(result.status,'historical_commit');assert.deepEqual(result.receipt,first.receipt);assert.equal((await f.writer.setTarget(command(2,1,false))).status,'target_state_invalid');const q=f.calls.at(-1).statements[0],raw=(await f.raw.prepare(q.sql).all(...q.values)),bytes=Buffer.byteLength(JSON.stringify(raw));assert.ok(bytes<4096);t.diagnostic('Independent transport NUL bounded response '+bytes);clean(f);
});
for(const operation of ['direct','planning'])test('new malformed prepared transport digest beneath pending head is rechecked in '+operation,async t=>{
 const f=await setup(t),first=await f.writer.setTarget(command(1)),source=sourceByEvent(f,first.receipt.resultingEventId),candidate=await prepareSeoulHeadCandidate(source),bad='e'.repeat(64)+'\0x',m=await coordinator(f);if(operation==='planning')await m.publish(manifest(100,['s1']));let before;f.beforeBatch=async ()=>{f.beforeBatch=undefined;(await f.raw.exec('BEGIN IMMEDIATE'));(await f.raw.prepare('INSERT INTO release_seoul_prepared_sources VALUES(?,?,?,?)').run(1,source.event_id,candidate.sourceChangeSha256,bad));(await f.raw.prepare("INSERT INTO release_seoul_projection_events(event_id,source_revision,event_kind,stream_kind,stream_key,source_sha256,space_id,snapshot_seq,issued_at,expires_at,payload_bytes,payload_sha256) VALUES(?,1,'head','target','s1',?,NULL,NULL,NULL,NULL,?,?)").run(source.event_id,candidate.sourceChangeSha256,candidate.eventText,bad));(await f.raw.prepare('INSERT INTO release_seoul_projection_deliveries(event_id) VALUES(?)').run(source.event_id));(await f.raw.exec('COMMIT'));before=allSnapshot(f);};const result=operation==='direct'?await f.writer.setTarget(command(2,1,false)):await m.appendPlanningPage({...ref(100),phase:'desired',pageNo:1,afterSpaceId:null,steps:[{spaceId:'s1',commandId:uuid(200),expectedRevision:1}]});assert.equal(result.status,operation==='direct'?'target_state_invalid':'uncertain');assert.deepEqual(allSnapshot(f),before);clean(f);
});
for(const mode of ['native-d1','durable-sql'])for(const operation of ['seal','verify','complete','cancel'])test('lost '+operation+' acknowledgement performs one fresh read and no mutation retry; '+mode,async t=>{
 const f=await setup(t,'OFF',true,mode),m=await coordinator(f,mode);await m.publish(manifest(100));
 if(operation==='seal')for(const phase of ['desired','omitted'])await m.appendPlanningPage({...ref(100),phase,pageNo:1,afterSpaceId:null,steps:[]});else await inventory(m,100);
 if(operation==='complete')await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null});
 let readsAtCommit,batchesAtCommit;f.afterCommit=()=>{readsAtCommit=f.reads;batchesAtCommit=f.batches;throw Error('lost committed phase acknowledgement');};
 const result=operation==='seal'?await m.seal(ref(100)):operation==='verify'?await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null}):operation==='complete'?await m.complete(ref(100)):await m.cancel({...ref(100),cancellationId:uuid(199),operatorReference:'cancel:test'});
 assert.equal(result.status,({seal:'already_sealed',verify:'already_verified',complete:'already_completed',cancel:'already_cancelled'})[operation]);assert.equal(f.batches,batchesAtCommit);assert.equal(f.reads,readsAtCommit+1);clean(f);
});
for(const mode of ['native-d1','durable-sql'])for(const action of ['supersede','cancel'])test('late '+action+' after verified pages prevents final completion; '+mode,async t=>{
 const f=await setup(t,'ON',true,mode),m=await coordinator(f,mode);await prepareOne(f,m);await f.writer.setManifestStep({...ref(100),spaceId:'s1'});await m.verifyPage({...ref(100),pageNo:1,afterSpaceId:null});let raced=false;
 f.beforeBatch=async request=>{if(!request.statements.some(s=>s.sql.startsWith('INSERT INTO release_seoul_target_manifest_completions')))return;raced=true;f.beforeBatch=undefined;if(action==='supersede')await m.publish(manifest(101,['s1'],1));else await m.cancel({...ref(100),cancellationId:uuid(199),operatorReference:'cancel:test'});};
 assert.equal((await m.complete(ref(100))).status,'uncertain');assert.equal(raced,true);assert.deepEqual(rows(f,'release_seoul_target_manifest_completions'),[]);assert.equal((await m.observeAgreement({...ref(100),configuredSpaceIds:['s1']})).status,action==='supersede'?'superseded':'cancelled');clean(f);
});
test('safe generation exhaustion returns capacity without attempting an unsafe successor',async t=>{
 const f=await setup(t,'ON',true,'native-d1'),m=await coordinator(f,'native-d1');
 // A bounded adapter observation models the unattainably long immutable generation history.
 // This checks the public capacity branch; it does not claim to construct that history.
 f.afterRead=(_request,result)=>{result[0].results[0].current_generation=Number.MAX_SAFE_INTEGER;};
 assert.equal((await m.publish(manifest(100,[],Number.MAX_SAFE_INTEGER))).status,'capacity');assert.equal(f.batches,0);assert.equal(f.reads,1);clean(f);
});
for(const field of ['token','operatorReference','spaceId'])test('new manifest SQL scalar domains reject embedded NUL in '+field,async t=>{
 const f=await setup(t),m=await coordinator(f);f.beforeBatch=()=>{throw Error('capture uncommitted request');};await m.publish(manifest(100,['s1']));f.beforeBatch=undefined;const request=structuredClone(f.calls.find(c=>c.statements.length>1));if(field==='token')request.statements[0].values[0]+='\0x';else{const body=JSON.parse(request.statements[0].values[5]);if(field==='operatorReference')body.operatorReference='operator\0suffix';else body.spaceIds=['s1\0suffix'];request.statements[0].values[5]=JSON.stringify(body);}assert.throws(()=>f.engine.execute({...request,statements:request.statements.slice(0,field==='token'?1:2)}));clean(f);
});
