import test from 'node:test';import assert from 'node:assert/strict';import {fixture,at} from './db.mjs';
import {MemoryStore} from '../../src/release/memory.ts';import {hmac} from '../../src/release/util.ts';
let Admin;try{({Admin}=await import('../../src/release/admin.ts'));}catch{}
for(const name of ['key-scopes','key-space','step-up','step-up-session','dns-proof','dns-wrong','signed-revocation','bad-signature','scim-scope'])test(name,async()=>{
 assert.ok(Admin,'admin implementation missing');const {db,token,other}=await fixture();let delivered;
 const fetcher=async(url,init)=>{return Response.json({Status:0,Answer:[{name:'_memory-verification.example.com.',type:16,data:'"'+(name==='dns-wrong'?'incorrect':proof)+'"'}]});};let proof='';
 const env={DB:db,PUBLIC_ORIGIN:'https://memory.example.com',EMAIL:{send:async message=>{delivered=message;return {messageId:'cf-test-mail'};}},MAIL_FROM:'memory@example.com',IDENTITY_WEBHOOK_SECRET:'s'.repeat(64),fetch:fetcher};const admin=new Admin(env,()=>at);const store=new MemoryStore(db,()=>at);
 try{
 if(name.startsWith('key')){const key=await admin.issueKey(token,{label:'Collector',capabilities:['create'],spaceIds:['s1'],expiresInDays:30});const m=await store.create(key.token,'s1',{body:'allowed'},'create');assert.ok(m.id);if(name==='key-scopes')await assert.rejects(()=>store.get(key.token,'s1',m.id),e=>e.status===403);if(name==='key-space')await assert.rejects(()=>store.create(key.token,'so',{body:'denied'},'bad'),e=>e.status===403);}
 if(name.startsWith('step')){db.raw.exec("UPDATE credentials SET reauthenticated_at=NULL WHERE id='session:alice'");const challenge=await admin.startReauth(token,'e1');assert.ok(delivered);const code=delivered.text.match(/Proof: ([A-Za-z0-9_-]+)/)[1];if(name==='step-up-session')await assert.rejects(()=>admin.completeReauth(other,challenge.id,code),e=>e.status===403);else{await admin.completeReauth(token,challenge.id,code);assert.equal(db.raw.prepare("SELECT reauthenticated_at t FROM credentials WHERE id='session:alice'").get().t,at);await assert.rejects(()=>admin.completeReauth(token,challenge.id,code),e=>e.status===403);}}
 if(name.startsWith('dns')){const challenge=await admin.beginDomain(token,'org','example.com');proof=challenge.value;if(name==='dns-wrong')await assert.rejects(()=>admin.verifyDomain(token,challenge.id),e=>e.code==='dns_proof_missing');else{const domain=await admin.verifyDomain(token,challenge.id);assert.equal(domain.name,'example.com');assert.equal(db.raw.prepare('SELECT count(*) n FROM domain_managers').get().n,1);}}
 if(name.includes('revocation')||name==='bad-signature'){db.raw.exec(`INSERT INTO provider_identities VALUES('https://auth-api.allen.company','sub-alice','alice',${at})`);const raw=JSON.stringify({id:'event1',issuer:'https://auth-api.allen.company',subject:'sub-alice',type:'email.revoked',email:'alice@example.com'});const timestamp=String(at/1000);const signature=await hmac(env.IDENTITY_WEBHOOK_SECRET,timestamp+'.'+raw);const request=()=>new Request('https://memory.example.com/webhooks/identity',{method:'POST',body:raw,headers:{'x-memory-timestamp':timestamp,'x-memory-signature':name==='bad-signature'?'x':signature}});if(name==='bad-signature')await assert.rejects(()=>admin.identityWebhook(request()),e=>e.status===401);else{await admin.identityWebhook(request());await admin.identityWebhook(request());assert.equal(db.raw.prepare("SELECT count(*) n FROM active_memberships WHERE account_id='alice'").get().n,0);assert.equal(db.raw.prepare('SELECT count(*) n FROM release_webhook_events').get().n,1);}}
 if(name==='scim-scope'){const key=await admin.issueScimKey(token,'org');await admin.scimDeactivate(key.token,'org','m2');assert.equal(db.raw.prepare("SELECT revoked_at FROM memberships WHERE id='m2'").get().revoked_at,at);assert.equal(db.raw.prepare("SELECT disabled_at FROM accounts WHERE id='bob'").get().disabled_at,null);await assert.rejects(()=>admin.scimDeactivate(key.token,'other-org','m1'),e=>e.status===401);}
 }finally{db.close();}
});
for(const kind of ['account.disabled','email.revoked'])test('identity revocation before first local sign-in: '+kind,async()=>{
 const {db}=await fixture();const secret='z'.repeat(64);try{
 const admin=new Admin({DB:db,IDENTITY_WEBHOOK_SECRET:secret},()=>at),raw=JSON.stringify({id:'before-sign-in',issuer:'https://auth-api.allen.company',subject:'not-mapped-yet',type:kind,...(kind==='email.revoked'?{email:'future@example.com'}:{})}),timestamp=String(at/1000);
 await admin.identityWebhook(new Request('https://memory.example/webhooks/identity',{method:'POST',body:raw,headers:{'x-memory-timestamp':timestamp,'x-memory-signature':await hmac(secret,timestamp+'.'+raw)}}));
 if(kind==='account.disabled')assert.throws(()=>db.raw.prepare('INSERT INTO workspace_sign_ins(id,issuer,subject) VALUES(?,?,?)').run('late-login','https://auth-api.allen.company','not-mapped-yet'),/revoked/);
 else{db.raw.prepare('INSERT INTO provider_identities VALUES(?,?,?,?)').run('https://auth-api.allen.company','not-mapped-yet','alice',at);assert.throws(()=>db.raw.prepare('INSERT INTO account_emails(id,account_id,address,domain,verified_at) VALUES(?,?,?,?,?)').run('late-email','alice','future@example.com','example.com',at),/revoked/);}
 }finally{db.close();}
});
