import test from 'node:test';import assert from 'node:assert/strict';import {fixture,at} from './db.mjs';
let createRelease;try{({createRelease}=await import('../../src/release/extension.ts'));}catch{}
async function rpc(response){const text=await response.text();return response.headers.get('content-type')?.includes('text/event-stream')?JSON.parse(text.split('\n').find(line=>line.startsWith('data: ')).slice(6)):JSON.parse(text);}
for(const name of ['rest-write-retry','rest-unknown-blocked','rest-query','mcp-mutations-need-key','mcp-retry','mcp-notification','mcp-get','mcp-scope','csrf-origin','ready-not-ga'])test('http '+name,async()=>{
 assert.ok(createRelease,'HTTP extension missing');const {db,token,key}=await fixture();const ext=createRelease({DB:db,PUBLIC_ORIGIN:'https://memory.example.com',REQUEST_LIMITER:{async limit(){return {success:true};}}},{clock:()=>at});const req=(path,data,method='POST',headers={})=>new Request('https://memory.example.com'+path,{method,headers:{'content-type':'application/json',accept:'application/json, text/event-stream',...headers},...(data===undefined?{}:{body:JSON.stringify(data)})});
 try{if(name==='rest-unknown-blocked'){assert.equal((await ext.route(req('/v1/spaces/s1/unknown',{}),token)).status,404);return;}if(name==='ready-not-ga'){assert.equal((await ext.publicRoute(req('/ready',undefined,'GET'))).status,503);return;}if(name==='csrf-origin'){assert.equal((await ext.publicRoute(req('/ready',undefined,'GET',{origin:'https://evil.test'}))).status,403);return;}
 if(name==='rest-write-retry'||name==='rest-query'){const data={body:'한국어 검색 실험',operationId:'one'};const a=await(await ext.route(req('/v1/spaces/s1/memories',data),token)).json();if(name==='rest-write-retry'){const b=await(await ext.route(req('/v1/spaces/s1/memories',data),token)).json();assert.equal(a.id,b.id);assert.equal(db.raw.prepare('SELECT count(*) n FROM memories').get().n,1);}else{const result=await(await ext.route(req('/v1/spaces/s1/memories?query=한국어',undefined,'GET'),token)).json();assert.equal(result.results[0].id,a.id);}return;}
 if(name==='mcp-get'){assert.equal((await ext.route(req('/mcp',undefined,'GET'),token)).status,405);return;}if(name==='mcp-notification'){const r=await ext.route(req('/mcp',{jsonrpc:'2.0',method:'notifications/initialized'}),token);assert.equal(r.status,202);assert.equal(await r.text(),'');return;}
 const data={jsonrpc:'2.0',id:7,method:'tools/call',params:{name:'memory_add',arguments:{spaceId:'s1',body:'MCP 기억',...(name==='mcp-mutations-need-key'?{}:{operationId:'mcp-one'})}}};const a=await rpc(await ext.route(req('/mcp',data),name==='mcp-scope'?key:token));if(name==='mcp-mutations-need-key'){assert.equal(a.result.isError,true);assert.equal(db.raw.prepare('SELECT count(*) n FROM memories').get().n,0);}else{assert.equal(a.result.isError,false);if(name==='mcp-retry'){await rpc(await ext.route(req('/mcp',data),token));assert.equal(db.raw.prepare('SELECT count(*) n FROM memories').get().n,1);}}
 }finally{db.close();}
});
