import test from 'node:test';import assert from 'node:assert/strict';import {Script} from 'node:vm';import {fixture,at} from './db.mjs';import {MemoryStore} from '../../src/release/memory.ts';import {createRelease} from '../../src/release/extension.ts';import {digest,readBytes} from '../../src/release/util.ts';import {recordMetric} from '../../src/release/telemetry.ts';import {managementScript,managementHtml} from '../../src/release/console.ts';
for(const name of ['write-revocation-race','retry-after-revocation','cross-space-revision','cross-space-supersedes','byte-limit','read-only-pool-erasure','oauth-migration-scopes','update-only-receipt','restore-only-receipt','receipt-no-fake-timestamp','shared-pool','malformed-json','bad-operation-key','metric-redaction','ui-script-parses'])test('security '+name,async()=>{
 const {db,token,other,key}=await fixture();const store=new MemoryStore(db,()=>at);try{
 if(name==='write-revocation-race'){const original=db.batch.bind(db);db.batch=async statements=>{db.raw.exec("UPDATE credentials SET revoked_at="+at+" WHERE id='session:alice'");return original(statements);};await assert.rejects(()=>store.create(token,'s1',{body:'must not commit'},'race'),e=>e.status===403);assert.equal(db.raw.prepare('SELECT count(*) n FROM memories').get().n,0);return;}
 if(name==='cross-space-revision'||name==='cross-space-supersedes'){const foreign=await store.create(other,'s2',{body:'private'},'foreign');await assert.rejects(()=>name==='cross-space-revision'?store.update(token,'s1',foreign.id,{body:'attack',expectedRevision:1},'attack'):store.create(token,'s1',{body:'attack',supersedesMemoryId:foreign.id},'attack'),e=>e.status===409);assert.equal((await store.get(other,'s2',foreign.id)).body,'private');return;}
 if(name==='byte-limit'){await assert.rejects(()=>store.create(token,'s1',{body:'가'.repeat(6000)},'large'),e=>e.status===400);return;}
 if(name==='oauth-migration-scopes'){const raw=Buffer.from('{}').toString('base64url')+'.'+Buffer.from(JSON.stringify({scope:'memory:read memory:write'})).toString('base64url')+'.signature';db.raw.prepare("INSERT INTO credentials(id,account_id,kind,token_digest,expires_at,permission) VALUES('oauth:test','alice','session',?,?,'write')").run(await digest(raw),at+600000);db.raw.exec(`INSERT INTO release_credential_policies(credential_id,capabilities,space_ids) VALUES('oauth:test','["read","create","update","delete","export"]',NULL)`);const ext=createRelease({DB:db,REQUEST_LIMITER:{limit:async()=>({success:true})}},{clock:()=>at});await ext.signedIn({}, {token:raw},true);const caps=JSON.parse(db.raw.prepare("SELECT capabilities FROM release_credential_policies WHERE credential_id='oauth:test'").get().capabilities);assert.deepEqual(caps,['read','create','update']);return;}
 if(name==='metric-redaction'){let payload;recordMetric({METRICS:{writeDataPoint:p=>payload=p}},new Request('https://example.test/auth/callback?code=PRIVATE',{headers:{authorization:'Bearer PRIVATE'}}),200,12);const text=JSON.stringify(payload);assert.ok(!text.includes('PRIVATE'));assert.ok(!text.includes('callback'));assert.deepEqual(payload.blobs,['auth','GET','200']);return;}
 if(name==='ui-script-parses'){assert.doesNotThrow(()=>new Script(managementScript));assert.ok(!/on(?:click|submit)=/i.test(managementHtml));assert.ok(!managementScript.includes('innerHTML'));assert.ok(!managementScript.includes('localStorage'));return;}
 if(name==='malformed-json'){const ext=createRelease({DB:db,PUBLIC_ORIGIN:'https://example.test',REQUEST_LIMITER:{limit:async()=>({success:true})}},{clock:()=>at});const r=await ext.route(new Request('https://example.test/v1/spaces/s1/memories',{method:'POST',headers:{'content-type':'application/json'},body:'{' }),token);assert.equal(r.status,400);return;}
 if(name==='bad-operation-key'){await assert.rejects(()=>store.create(token,'s1',{body:'valid'},'../../attack'),e=>e.status===400);return;}
 if(name==='shared-pool'){db.raw.exec(`INSERT INTO spaces VALUES('so2','Team 2',NULL,'org','managed',${at},'session:alice')`);await store.create(token,'so',{body:'one'},'one');await store.create(token,'so2',{body:'two'},'two');assert.equal(db.raw.prepare("SELECT units FROM release_usage_counters WHERE pool_id='org:org'").get().units,2);return;}
 if(name==='receipt-no-fake-timestamp'){db.raw.exec(`UPDATE release_credential_policies SET capabilities='["create"]' WHERE credential_id='key:alice'`);const r=await store.create(key,'s1',{body:'append'},'append');assert.equal(r.representation,'receipt');assert.ok(!('createdAt' in r));return;}
 const memory=await store.create(token,'s1',{body:'original'},'create');
 if(name==='retry-after-revocation'){db.raw.exec("UPDATE credentials SET revoked_at="+at+" WHERE id='session:alice'");await assert.rejects(()=>store.create(token,'s1',{body:'original'},'create'),e=>e.status===403);return;}
 if(name==='read-only-pool-erasure'){db.raw.exec("UPDATE release_pools SET state='read_only',monthly_units=0 WHERE id='account:alice'");await store.remove(token,'s1',memory.id,1,'delete');await store.erase(token,'s1',memory.id,2,memory.id,'erase');assert.equal(db.raw.prepare('SELECT body FROM memories WHERE id=?').get(memory.id).body,'[erased]');return;}
 if(name==='update-only-receipt'||name==='restore-only-receipt'){db.raw.exec(`UPDATE release_credential_policies SET capabilities='["update"]' WHERE credential_id='key:alice'`);if(name==='restore-only-receipt')await store.remove(token,'s1',memory.id,1,'delete');const r=await(name==='update-only-receipt'?store.update(key,'s1',memory.id,{body:'changed',expectedRevision:1},'change'):store.restore(key,'s1',memory.id,2,'restore'));assert.equal(r.representation,'receipt');assert.ok(!('body'in r));return;}
 throw Error('Unimplemented test case');
 }finally{db.close();}
});
