/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: a2083acb2deff20be7e65022ad221df9)
interface __BaseEnv_Env {
	MEMORY: AgentMemoryNamespace;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	AUTH_API_URL: "https://auth-api.allen.company";
	AUTH_WEB_URL: "https://auth.allen.company";
	MEMORY_RESOURCE_URL: "https://memory.allenlim.net";
	LEGACY_AUTH_AUDIENCE_CUTOFF: "2026-08-13T06:00:00Z";
	DEFAULT_SCOPE: "";
	MEMORY_API_KEY_REGISTRY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_API_URL" | "AUTH_WEB_URL" | "MEMORY_RESOURCE_URL" | "LEGACY_AUTH_AUDIENCE_CUTOFF" | "DEFAULT_SCOPE" | "MEMORY_API_KEY_REGISTRY">> {}
}
