/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: d8156bea3701e3f47f348a94e83cdc0c)
interface __BaseEnv_Env {
	MEMORY: AgentMemoryNamespace;
	AUTH_API_URL: "https://auth-api.allen.company";
	AUTH_WEB_URL: "https://auth.allen.company";
	DEFAULT_SCOPE: "";
	MEMORY_API_KEY_REGISTRY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_API_URL" | "AUTH_WEB_URL" | "DEFAULT_SCOPE" | "MEMORY_API_KEY_REGISTRY">> {}
}
